### ISSUE TITLE
use Nlua  KeraLua in unity 

### ISSUE THREAD

**Issue by sonygod** [NLua/NLua#122]
I try to compile Nlua and keralua to dll and then put  to  Plugins  forlder in unity ,got the error :

EntryPointNotFoundException: luanet_registryindex
KeraLua.Lua.LuaNetRegistryIndex ()
NLua.LuaIndexes.get_Registry ()
NLua.Lua.Init ()
NLua.Lua..ctor ()
TestBehaviour.Awake () (at Assets/Example/TestBehaviour.cs:25)

any help?

**Comment by refaelsh** [comment]
Hi,
I am having the same problem.
What do You mean by "download the lua52.dll binaries from readme"?
Can You please elaborate?
Thanks :-)
