### ISSUE TITLE
[unity] null !=Null

### ISSUE THREAD

**Issue by sonygod** [NLua/NLua#132]
local rb = Main_Main.mMain.cube:GetComponent("Rigidbody")
		Debug.Log(rb) //null
		Debug.Log(nil)//Null    (not null)
		Debug.Log(rb == nil)//false

   how to fixed that?

  current only can  	Debug.Log(rb:ToString() == "null").

**Comment by isaacbrodsky** [comment]
If you can call ToString on an object it must not actually be null. My guess is that rb is some object whose ToString is returning the string "null". That doesn't look like an NLua issue to me.

I'm not sure about the second issue about UnderlyingSystemType.

**Comment by sonygod** [comment]
use toString() fixed
