### ISSUE TITLE
[Question] Add support to Globals AutoComplete

### ISSUE THREAD

**Issue by TheAifam5** [NLua/NLua#135]
Hi,
is possible to add support for Globals AutoComplete for function "DoString" and (maybe, i not tested) "DoFile" ?

**Comment by viniciusjarina** [comment]
What is Globals AutoComplete ?

**Comment by TheAifam5** [comment]
https://github.com/NLua/NLua/blob/master/Core/NLua/Lua.cs#L90
https://github.com/NLua/NLua/blob/master/Core/NLua/Lua.cs#L258

**Comment by viniciusjarina** [comment]
Hi @TheAifam5 I am not sure what mean by "add support for Globals AutoComplete for function "DoString"" :cry:

**Comment by TheAifam5** [comment]
So... "Globals" not working when you load a file(DoFile), or script(DoString)..., but if you put manually in C# script, works maybe work..
