### ISSUE TITLE
Lua and IIS/WCF no-go

### ISSUE THREAD

**Issue by apleweghostery** [NLua/NLua#137]
I'm working with Aerospike, which uses Lua to do map/reduce and other things. Anyways, when I try to run the Aeropsike sample code in a simple WCF service I get the dreaded dll errors:

Unable to load DLL 'lua52': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   at KeraLua.NativeMethods.LuaLNewState()
   at NLua.Lua..ctor()
   at Aerospike.Client.LuaInstance..ctor() in c:\AerospikeClient\aerospike-client-csharp-3.0.12\AerospikeClient\Lua\LuaInstance.cs:line 32
   at Aerospike.Client.LuaCache.GetInstance() in c:\AerospikeClient\aerospike-client-csharp-3.0.12\AerospikeClient\Lua\LuaCache.cs:line 34
   at Aerospike.Client.QueryAggregateExecutor.RunThreads() in c:\AerospikeClient\aerospike-client-csharp-3.0.12\AerospikeClient\Query\QueryAggregateExecutor.cs:line 65
   at Aerospike.Client.QueryAggregateExecutor.Run(Object obj) in c:\AerospikeClient\aerospike-client-csharp-3.0.12\AerospikeClient\Query\QueryAggregateExecutor.cs:line 55

I've made sure that all the OS stuff is the same (explicitly importing the 64 bit version for a 64 bit build, etc), and when I get it wrong the build fails. When I get it right the build succeeds and everything's fine until it tries to invoke Lua. I've also tested this outside of Aerospike (i.e. simple WCF that tries to run some Lua script), same issue. I can post sample code if you'd like, but basically this happens any time I instantiate a Lua instance (i.e. Lua li = new Lua()) in a WCF or .net Web Application.

**Comment by apleweghostery** [comment]
Adding, a bit more detail from the constructor call:

   at KeraLua.NativeMethods.LuaLNewState()
   at KeraLua.Lua.LuaLNewState()
   at NLua.LuaLib.LuaLNewState()
   at NLua.Lua..ctor()

My next step is to make sure the correct permissions are assigned to the Lua .dlls unless there are any other (and probably better) ideas.

**Comment by isaacbrodsky** [comment]
I could take a look at this later if you could post a sample project. I'm guessing either the Lua DLL couldn't be found or can't be loaded for some reason. Maybe architecture mismatch, or a missing dependency (e.g. Visual C runtime?)

**Comment by apleweghostery** [comment]
I've looked and I'm pretty sure I have the Visual C runtime installed (I'm using VS2013 btw), but just to be sure which dll should be in System32? I noticed that when I built my application the Lua52.dll didn't end up in the temporary .net folders (i.e. [sysroot]/Microsoft.Net/[version]/Temporary ASP.NET Files...). I think VS might be having an issue copying the .dll?

**Comment by apleweghostery** [comment]
Here's a link to download all the code (this includes the aerospike stuff and all the relevant nuget packages including NLua): https://www.dropbox.com/s/p8qaijxoe2axh9g/aerospike-client-csharp-3.0.12.zip?dl=0

**Comment by isaacbrodsky** [comment]
I'm not sure which version of the C runtime the Lua DLL requires. If you add a DLL (as a file) to a project in Visual Studio by default that doesn't copy it. You might need to set the DLL to copy to output.

**Comment by apleweghostery** [comment]
Yeah, I have that option set to "true".

**Comment by viniciusjarina** [comment]
Hi @apleweghostery are you able to create a Console Application with NLua?
Did you download the library or installed from NuGet?

Thank you.

**Comment by apleweghostery** [comment]
Yes, console apps work fine. In both instances (console and web) I used nuget to install the package. Once I started getting errors, I added the source projects so I could see if there was anything else going on, but it looks like it mostly boils down to some issue with IIS and Lua51.dll/Lua52.dll. On the permissions front I tried doing my code in "release" mode (so it doesn't use the temporary .net folders) and put the Lua52.dll in the bin directory manually and set permissions manually. That, so far anyways, hasn't worked either.

**Comment by apleweghostery** [comment]
...Adding, I'm running Windows 8.1, 64 bit.

**Comment by isaacbrodsky** [comment]
I was able to get the same exception, although using IIS express, and a 32-bit build (the projects didn't seem to build in 64 bit.) I was able to fix that by manually moving lua52.dll into the bin\Debug folder for the AerospikeWCFClient project. Was this the project you were trying to use NLua from?

You could also try placing the correct version of lua52.dll in c:\windows, if this resolves your issue then I think that would confirm that the issue is the placement of the DLL.

**Comment by apleweghostery** [comment]
Hmmm... I'll have to play with this in the morning my time, but I thought the .dll should load in the AerospikeWCF project. The Client (theoretically, anyways) shouldn't care at all about the .dll as it's calling the "GetData" function in the WCF service. Anyways, I'll follow your steps and see what happens. Thanks!

**Comment by sonygod** [comment]
I got the same issue , Windows 7, 64 bit. 

and everything  seem to be ok but lua52.dll, I don't know where to get the right dll,I have many version 

and then copy to  windows/  windows/system32   ..ect  but got the same error: luanet_registryindex

**Comment by viniciusjarina** [comment]
Hi @sonygod you can't use lua52.dll from Lua Binaries you need to use the lua52 from NLua.

Is basically the same code, NLua version added a few methods to work with NLua

**Comment by viniciusjarina** [comment]
@apleweghostery I am not sure if this could be issue, but check if your service is allowed to do P/Invoke.
If you are sure you can do P/Invoke
* Check if you have installed vcredist 2013 x86/x64
If you want to make NLua work with x64 and x86 you can add a folder right next to NLua and KeraLua.dll x64 and x86 and copy the lua52.dll (from NLua README) into this folder. (This is exactly what the NuGet version does).
If you can't P/Invoke (due security restrictions) you will need to use NLua_Safe (C# only implementation this is about 10x slower)

**Comment by apleweghostery** [comment]
I think I'll start with NLua_Safe and, assuming it works, if performance is really an issue (the Aerospike cluster should be doing most of the heavy-lifting) then I'll hammer some more on getting P/Invoke to work. Thanks!

**Comment by apleweghostery** [comment]
NLua_Safe is working for me now. I will revisit if, for some reason, performance becomes an issue. Thanks!

**Comment by viniciusjarina** [comment]
Good :)
