### ISSUE TITLE
Can't get NLua working on Windows 7 x86

### ISSUE THREAD

**Issue by XanatosX** [NLua/NLua#139]
I've downloadet the Win32 Build from the readme.md.

I Linket the Nlua.dll (.Net4.0) to my project and drag dropt the lua52.dll from the zip archive as content file copy always.

Everytime i start to compile the project i get an error at the first line of code:

Lua test = new Lua();

DLLNotFoundExeption it seems like visual studio don't find the lua52.dll.

I can't find my mistake.

**Comment by viniciusjarina** [comment]
* Check if your project is running in 32-bit
* Check you have vcredist 2013 installed

Try to install from NuGet 

Thank you

**Comment by XanatosX** [comment]
Thanks a lot for you help. Installing the vcredist 2013 solved the problem.

**Comment by viniciusjarina** [comment]
@XanatosX  Great! :smile:

**Comment by UweKeim** [comment]
For anyone interested: The files of the VC Runtime 2013 have a "12" inside their filename.

E.g.

- "msvcp120.dll"
- "msvcr120.dll"
