### ISSUE TITLE
How to change  LUA_PATH_DEFAULT in KeraLua?

### ISSUE THREAD

**Issue by sonygod** [NLua/NLua#140]
How to change  LUA_PATH_DEFAULT in KeraLua?

only I can find LUA_PATH_DEFAULT property  in KopiLua, lua.cs,but KeraLua have no ,

any guide?

**Comment by viniciusjarina** [comment]
KeraLua will use underneath the original Lua, so  take a look at lua.org documentation.

**Comment by sonygod** [comment]
Okay .that  mean can not Chang the cpath for  required

**Comment by viniciusjarina** [comment]
This might help

http://stackoverflow.com/a/5761649/198353
