### ISSUE TITLE
can not use luanet.ctype in KeraLua but KopiLua

### ISSUE THREAD

**Issue by sonygod** [NLua/NLua#141]
can not use luanet.ctype in KeraLua but KopiLua?

is that right?

**Comment by sonygod** [comment]
Luanet.ctype(Transform) 

KeraLua return     ProxyType(UnityEngine.Transform)

KopiLua  return UnityEngine.Transform

**Comment by viniciusjarina** [comment]
you can use in both versions

**Comment by sonygod** [comment]
No ,they return the difference type ,

**Comment by viniciusjarina** [comment]
This test seems to be passing in all platforms https://github.com/NLua/NLua/blob/84a593fec030f43b5c80ce634f7f07ce8376d178/tests/LuaTests.cs#L2018

**Comment by sonygod** [comment]
No it's have no errors ,but have the difference return type only ,so ,I can not use the ctype …

**Comment by viniciusjarina** [comment]
Please write a Unit test and send a PR if is not working properly for you :wink: 

Thank you.

**Comment by sonygod** [comment]
Kera

![ker](http://lb2.net/di/IWE2/ker.jpg)


KOIP

![kop](http://lb2.net/di/NKSR/kop.jpg)

**Comment by sonygod** [comment]
the picture  show return difference  type 

KeraLua return ProxyType(UnityEngine.Transform)

KopiLua return UnityEngine.Transform
