### ISSUE TITLE
[Question]where can I download lua52.so lua52.a for Nlua?

### ISSUE THREAD

**Issue by sonygod** [NLua/NLua#142]
where can I download lua52.so lua52.a for Nlua?

**Comment by viniciusjarina** [comment]
README.md contains the Download of each platform. :)

**Comment by sonygod** [comment]
But not include the *.so file for unity ,

**Comment by sonygod** [comment]
So 'we can not use that link for unity  which only have DLL…can not compiled in unity Android build

**Comment by viniciusjarina** [comment]
:) is inside the KeraLua .dll as EmbdeddResource :wink: 

This build is designed to target Xamarin.Android :) I think you can't try to extract from KeraLua.dll the lua52.so
