### ISSUE TITLE
Can I call GetComponent() function from Lua?

### ISSUE THREAD

**Issue by thebestmacone** [NLua/NLua#143]
viniciusjarina commented on Oct 20, 2014

you just need to use the luanet.ctype method

gameObject:GetComponent (luanet.ctype (Transform))

Does it really work? In my case it returns late bound error!

**Comment by Mervill** [comment]
This is an issue with template functions I'm still investigating, for now it's best to use the string based version of `GetComponent`:

```Lua
gameObject:GetComponent ("Transform")
```

It *is* slower, obviously, but it will work until I have more time to investigate this issue.

**Comment by thebestmacone** [comment]
I'll try, thanks!
