### ISSUE TITLE
[Unity] can't set value to filed

### ISSUE THREAD

**Issue by sonygod** [NLua/NLua#144]
import 'System'
	import 'UnityEngine'
	import 'Assembly-CSharp'
	
	local cube = GameObject.CreatePrimitive(PrimitiveType.Cube)
	
	Debug.Log(cube.name);//work
	cube.name = "read"//fail

the error show

	EntryPointNotFoundException: luanet_isstring_strict
	KeraLua.Lua.LuaNetIsStringStrict (IntPtr luaState, Int32 index) (at Assets/KeraLua/Lua.cs:186)
	NLua.LuaLib.LuaNetIsStringStrict (LuaState luaState, Int32 index) (at Assets/NLua/LuaLib/LuaLib.cs:279)
	NLua.CheckType.CheckLuaType (LuaState luaState, Int32 stackPos, System.Type paramType) (at Assets/NLua/CheckType.cs:155)
	NLua.ObjectTranslator.GetAsType (LuaState luaState, Int32 stackPos, System.Type paramType) (at Assets/NLua/ObjectTranslator.cs:724)
	NLua.MetaFunctions.TrySetMember (LuaState luaState, IReflect targetType, System.Object target, BindingFlags bindingType, System.String& detailMessage) (at Assets/NLua/Metatables.cs:855)
	NLua.MetaFunctions.SetFieldOrPropertyInternal (LuaState luaState) (at Assets/NLua/Metatables.cs:754)
	NLua.MetaFunctions.SetFieldOrProperty (LuaState luaState) (at Assets/NLua/Metatables.cs:738)
	(wrapper native-to-managed) NLua.MetaFunctions:SetFieldOrProperty (KeraLua.LuaState)
	KeraLua.Lua.LuaNetPCall (IntPtr luaState, Int32 nArgs, Int32 nResults, Int32 errfunc) (at Assets/KeraLua/Lua.cs:204)
	NLua.LuaLib.LuaPCall (LuaState luaState, Int32 nArgs, Int32 nResults, Int32 errfunc) (at Assets/NLua/LuaLib/LuaLib.cs:299)
	NLua.Lua.DoFile (System.String fileName) (at Assets/NLua/Lua.cs:521)

**Comment by viniciusjarina** [comment]
Where did you get lua52.dll from?

**Comment by sonygod** [comment]
https://github.com/Mervill/Unity3D-NLua

**Comment by viniciusjarina** [comment]
So open issue there :) 
https://github.com/Mervill/Unity3D-NLua/issues
NLua/NLua version is fine.

**Comment by sonygod** [comment]
I recheck the lua52.dll file and found that there is a  lua52.dll in windows forlder ,it's wrong .and it's not a bug ,sorry

**Comment by dpull** [comment]
try https://github.com/dpull/UnityLua
