### ISSUE TITLE
WeakReferences

### ISSUE THREAD

**Issue by CWolfs** [NLua/NLua#147]
Is there any plan to introduce WeakReferences into NLua? I feel it would be a very useful addition.

**Comment by viniciusjarina** [comment]
How exactly this would help/work ?
:)

**Comment by CWolfs** [comment]
Basically, by allowing C# to store a WeakReference to, for instance, a table. Even though it's stored in C# it would still allow the Lua garbage collector to clear the table up. This would be very useful for when, like in my case, a C# EventManager is storing LuaTables but want the Lua GC to clear up the object when it falls completely out of Lua scope.

Currently, when it falls completely out of scope in Lua the Lua GC would not clean the table up since the reference is still held in C#.

If WeakReferences were available, I could use a WeakTable / WeakReference<T> and run null checks to see if the table has been cleaned up by Lua. Then I could clean this out of the EventManager without having to run a call from Lua like 'EventManager:unregister(self)'.

**Comment by CWolfs** [comment]
ELuant implements one like this https://github.com/cdhowie/Eluant/blob/master/Eluant/LuaWeakReference.cs and here https://github.com/cdhowie/Eluant/blob/master/Eluant/LuaRuntime.cs#L1392

**Comment by CWolfs** [comment]
Any thoughts on this? =)
