### ISSUE TITLE
Sandbox the CLR in executed scripts?

### ISSUE THREAD

**Issue by AngeloG** [NLua/NLua#148]
Is it doable? I've tried making an `AppDomain` in my application in order to filter out some of the permissions, but as it turns out you need to give it full trust to execute unmanaged code, which kind of defeats the purpose.

I can null out the `io` and `os` packages, as well as the entire CLR, but I'd rather keep the CLR and have it under a controllable domain with a permission set.

**Comment by viniciusjarina** [comment]
Hello @AngeloG 

I think the best option to create Sandboxed environment is to use Lua itself.

Taka a look at this http://lua-users.org/wiki/SandBoxes and
https://github.com/OpenRA/OpenRA/blob/bleed/lua/sandbox.lua

OpenRA is using NLua and is using pure lua solution to sandbox their scripts.

Thank you.

**Comment by AngeloG** [comment]
Thanks for the suggestion, I'll check it out!

**Comment by AngeloG** [comment]
Just checked out OpenRA's implementation, and it appears they also disable `require`, which is used by `LoadCLRPackage()` in NLua. This wouldn't give me access to the CLR, which is a problem in my case.

Also, `setfenv` is nil in Lua 5.2, so their implementation isn't very useful for me as far as I can see.

Would it be possible to patch NLua to use an `AppDomain` for the CLR packages, so that we can set our own permission set on those?

**Comment by viniciusjarina** [comment]
Hey @AngeloG Mayba. But I am not sure if this is the better approach.

I think sandbox using plain Lua would be more easy and simple. You could try to define your set of APIs and avoid any other code loading or filesystem access. Also you could disable require after use LoadCLRPacket right? I am not sure.

**Comment by AngeloG** [comment]
I could disable `require` after `LoadCLRPackage()`, that's correct. But then there's still a full-trust execution on any use of CLR classes (eg. `File.OpenWrite()` and such)

**Comment by AngeloG** [comment]
Something else I could do is write wrapper objects for common uses of the CLR, and have those classes handle the permissions, but that would require me to write a lot of wrapper classes (in a custom API, so to say).

I'm going to take a closer look at the NLua code later tonight and see what my choices are.
