### ISSUE TITLE
[Question] lua53.dll compiled with VS2010

### ISSUE THREAD

**Issue by stenya** [NLua/NLua#149]
Hello!

I downloaded lua52.dll from this link:
Win32: Download [![dwn_w32][8]][7]
[7]: https://www.dropbox.com/s/jkr1pnwvqw6w0r8/NLua.Win32.zip

But, current version of lua52.dll is compiled with VS2013 (requires MSVCR120.dll and MSVCP120.dll).
I want to have it compiled with VS2010.

Where I can get an sources of lua52.dll in order to recompile it myself?
Or may-be, there is a already compiled version for vs2010?

Thanks.

**Comment by viniciusjarina** [comment]
Hello @stenya unfortunately yes.

The good news is, build Lua52 is quite easy using the NLua/lua repo
You will need to install CMake.
Just use https://github.com/NLua/NLua/blob/master/run_all.win32.bat (and be sure to update the submodules first).  Call this .bat from you VS Command Line.
