### ISSUE TITLE
How to call AddComponent() from Lua?

### ISSUE THREAD

**Issue by toxicwolf** [NLua/NLua#152]
AddComponent(string name) is deprecated and throws an exception, is there a way to pass a C# function a type parameter from Lua ( AddComponent< T >() )?

**Comment by viniciusjarina** [comment]
What is AddComponent ?

**Comment by toxicwolf** [comment]
Sorry, I should have specified, it's a Unity GameObject instance method.

**Comment by viniciusjarina** [comment]
@toxicwolf  I think you could ask here https://github.com/Mervill/Unity3D-NLua :wink:

**Comment by toxicwolf** [comment]
Will do. Although I'm interested on a more general level if it's possible to pass type parameters to C# methods - Unity or otherwise.

**Comment by viniciusjarina** [comment]
Yes you can :) you need to use ctype.

**Comment by toxicwolf** [comment]
I'm sorry, could you be more specific?

Just to be clear about what I'm asking, say I defined the following C# method:
```c#
public void DoSomething<T>() {
}
```
How would I call that from Lua, passing it the generics type parameter?

**Comment by viniciusjarina** [comment]
If you just call DoSomething NLua will try to match the types

Take a look at TestGenerics

https://github.com/NLua/NLua/blob/84a593fec030f43b5c80ce634f7f07ce8376d178/tests/LuaTests.cs#L559


;)

**Comment by toxicwolf** [comment]
I can see how that works for methods with a signature like DoSomething<T>(T
value), but I still don't understand how it would work for my example.

**Comment by viniciusjarina** [comment]
Which error you got?

**Comment by toxicwolf** [comment]
DoSomething() -> InvalidOperationException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true

DoSomething(String) and DoSomething(luanet.ctype(String)) -> LuaScriptException: invalid arguments to method: MyClass.DoSomething

**Comment by viniciusjarina** [comment]
What if you try to workaround like this
public void DoSomethingWrap <T> (T arg)
{
      DoSomething<T> ();
}

and call DoSomethingWrap ('param')
?
