### ISSUE TITLE
An unhandled exception of type 'NLua.Exceptions.LuaScriptException'

### ISSUE THREAD

**Issue by shawning** [NLua/NLua#165]
I've messed with this for several hours now and the documentation you have on the readme didn't help at all. I'm GUESSING this is something I'm doing incorrectly but no idea where else to find help. 

If I'm not going about getting a resolution the correct way please let me know and point me in the correct direction please!

My code is simple:

---- BEGIN CODE ----
using System;

using NLua;

namespace NLUATest
{
    class NLUATest
    {
        public static void Main(string[] args)
        {
            Lua state = new Lua();

            string file = "../../test.lua";

            state.LoadFile(file);

            state.Close();

            Console.ReadKey();
        } // public static void Main(string[] args)
    } // class NLUATest
} // namespace NLUATest

---- END CODE ----

I'm using the .NET Pure C# download and I've added the NLua.dll and KopiLua.dll to my References in my project. (I'm using the 4.5 versions but I also tried the 4.0 versions).

![untitled](https://cloud.githubusercontent.com/assets/3653461/8342654/62a6620a-1a93-11e5-95d1-82fb61abb49f.png)

I get the following error message when trying to "Start" from within Visual Studio 2013.

---- BEGIN ERROR MESSAGE ----

An unhandled exception of type 'NLua.Exceptions.LuaScriptException' occurred in NLua.dll

Additional information: ../../test.lua:1: '=' expected near '»'

---- END ERROR MESSAGE ----

Thanks so much!

**Comment by isaacbrodsky** [comment]
That error indicates there is something wrong with the Lua file you are trying to execute, specifically, there is some sort of syntax error around line 1. What's the content of test.lua?

**Comment by shawning** [comment]
Sadly it is simply a Hello World file:

---- Begin test.lua ----
print("Hello world!")
---- End test.lua ----

Thanks you Isaac, by the way!

**Comment by isaacbrodsky** [comment]
Hi,

That is puzzling. My guess would be there's something wrong with the way the file is saved. Can you verify you're loading the right file? If you load it with File.ReadAllText("../../test.lua"), does it have the right content? Are there any unicode characters in the file?

As for experimenting with NLua, my suggestion is to experiment with state.DoString(string) instead. e.g.:
  state.DoString("print('Hello world from Lua')");

or

  state["a"] = "Hello world";
  state.DoString("print(a)");

state.LoadFile will load and compile the file, giving you a LuaFunction you can execute. DoFile loads the file and immediately executes it.

Isaac

**Comment by shawning** [comment]
Isaac,

That was the issue! I used a simple text editor to create the 'test.lua' file and it ran no problem. I can't believe I didn't think of that.

Thanks so much for your help!

Shawn
