### ISSUE TITLE
Website has invalid code "as double"

### ISSUE THREAD

**Issue by gwicksted** [NLua/NLua#166]
Double is not a nullable type.  Can either use "double?" type or change the "as" to a cast.

Current code:
var res = state.DoString ("return 10 + 3*(5 + 2)")[0] as double;

Option a:
var res = state.DoString ("return 10 + 3*(5 + 2)")[0] as double?;

Option b:
var res = (double)state.DoString ("return 10 + 3*(5 + 2)")[0];

**Comment by viniciusjarina** [comment]
Thank @gwicksted 

Also, did you know the web-site is at gh-pages branch. You can send a PR if you want ;) 

Thank you again

**Comment by gwicksted** [comment]
Ah!  That's where it is!

**Comment by gwicksted** [comment]
PR #167
