### ISSUE TITLE
Invalid arguments to method call

### ISSUE THREAD

**Issue by Fraysa** [NLua/NLua#168]
Here's my .lua script:

```
addText("Hey, press the Next button!");
sendNext();

addText("Cool, right?");
sendOk();
```

I do the following to run it:

```
var lua = new Lua();

lua.RegisterFunction("addText", this.GetType().GetMethod("AddText"));
lua.RegisterFunction("sendNext", this.GetType().GetMethod("AddText"));
lua.RegisterFunction("sendOk", this.GetType().GetMethod("AddText"));

lua.DoFile("C:\test.lua");
```

However, I'm still getting the error listed in the title, why's that?

If it helps, I'm using a thread to run lua.DoFile.

**Comment by isaacbrodsky** [comment]
Could you post the definition for the AddText method? Also which line of Lua is generating the error would be helpful.

**Comment by Fraysa** [comment]
Hey, I just added the "this" keyword after "addText" and that did the trick! Thanks.

**Comment by openJCD** [comment]
> Hey, I just added the "this" keyword after "addText" and that did the trick! Thanks.

I know this issue is closed, but which "addText" are you talking about? Where did you place your "this" keywords? I just ran into this issue myself, so i was wondering what you mean here.
