### ISSUE TITLE
Script finish execution

### ISSUE THREAD

**Issue by Fraysa** [NLua/NLua#169]
Is there a script finish execution event or something similar? I'm running the script using a thread and I want to know when the script finished so I can abort the thread. I can't use Thread.Join because I can't hold the main thread.

**Comment by viniciusjarina** [comment]
You could trigger a C# event from the Lua script

**Comment by Fraysa** [comment]
Can yuh show me an example?

**Comment by viniciusjarina** [comment]
https://gist.github.com/viniciusjarina/b97adde7cb7c0870e52e

This might work :wink:
