### ISSUE TITLE
Globals not loading?

### ISSUE THREAD

**Issue by Fraysa** [NLua/NLua#170]
I have the following lua script:

```
host = "localhost";
schema = "velox";
username = "root";
password = "";
```

When I do:

```
lua = new Lua().DoFile(path);
```

And then:

```
lua["host"];
```

It returns null, as if the global wasn't loaded. Why's that?

**Comment by viniciusjarina** [comment]
DoFile () will return the values returned from the script :wink: 
You should do

    lua = new Lua();
    lua.DoFile(path);
    lua ["host"];
