### ISSUE TITLE
Registering functions like "something:something" in C#?

### ISSUE THREAD

**Issue by rag3rac3r** [NLua/NLua#173]
Hi, and excuse me for the possibly bad title.

I have spent a long time looking around to see if it is possible to use the Lua.RegisterFunction() to create functions that can be used in lua-scripts like "Lua:LuaFunction"/"Lua.LuaFunction".

Couldn't find any information, so i'm resorting to asking here directly if it is possible?

If not, would it be possible to add it?

**Comment by ncarlson** [comment]
Hi,
Would you mind providing more information on the issue you're having? Perhaps provide a code example or two. Thanks
