### ISSUE TITLE
LuaTables can't be passed in a C# varargs function (InvalidCastException)

### ISSUE THREAD

**Issue by Tenrys** [NLua/NLua#174]
I posted an issue about this, and it was a bit vague. Now it's all clear: LuaTables can't be passed in a C# varargs function.

![print({}) throws an InvalidCastException error.](http://tenrys.montoyo.net/ShareX/2015-07-25_21-54-58.png)
`print({}) throws an InvalidCastException error.`

![](http://tenrys.montoyo.net/ShareX/2015-07-26_17-09-26.png)

Is there any way to fix this? All I'm trying to do is make a print function in C# that would basically have the same functionality of the basic print function in Lua, but make it print somewhere else than in the console.

**Comment by Tenrys** [comment]
I've found that LuaTables are trying to get converted to an Object in Metatables.cs. So maybe run TableToArray with the LuaTable being passed?

**Comment by Tenrys** [comment]
Still nothing?

**Comment by Tenrys** [comment]
Please, I really could use some help. Even a "you can't fix this" would suffice me.

**Comment by isaacbrodsky** [comment]
Could you post an example of the Lua script and the method it's trying to call? I wasn't able to reproduce this.

**Comment by Tenrys** [comment]
The Lua script is just me using my own print function from C# (print) with a table. So print({}).

The method can just be an empty method.

```C#
public void Print(params object[] args)
{

}
```

**Comment by isaacbrodsky** [comment]
Hm, I wasn't able to reproduce as you describe, but the following code does crash:

```
        // In TestClass:
        public void MethodWithObjectParams(params object[] args)
        {
            Console.WriteLine("Method with object array params");
        }
```

```
		/*
        * Tests calling of an object's method with LuaTable to object params.
        */
		[Test]
		public void CallObjectMethodObjectParams ()
		{
			using (Lua lua = new Lua ()) {
                TestClass t1 = new TestClass();
				lua ["netobj"] = t1;
                lua.DoString ("a = {[123] = 456, ['abc'] = 'def'}");
                lua.DoString ("netobj:MethodWithObjectParams('aff', a)");
                lua.DoString ("netobj:MethodWithObjectParams(a)");
                lua.DoString ("netobj:MethodWithObjectParams({})");
                lua.DoString ("netobj:MethodWithObjectParams(5)");
                lua.DoString ("netobj:MethodWithObjectParams({{}})"); // <-- This line crashes
                Assert.True (lua ["a"] is LuaTable);
			}
		}
```

**Comment by Tenrys** [comment]
This isn't how I do it.
I don't have my code right now because I'm not on my computer, but I do it like this:

```C#
// my Class (LuaEnv)
...
public void Print(params object[] args)
{

}
...

// my program code
...

private static Lua lua = new Lua();

...

public void DoLuaStuff()
{
   lua.RegisterFunction("print", typeof(LuaEnv):GetMethod("Print"))
}
```

**Comment by Tenrys** [comment]
Any news on that?

**Comment by Tenrys** [comment]
Alright, I followed your advice and that fixed it for me. Does that fix break anything? I may do a pull request.

**Comment by Tenrys** [comment]
It seems that print({}, anything) jinxes it with that error: invalid arguments to method call.
print("a", {}) works fine though.

**Comment by Tenrys** [comment]
Apparently, the argument count is not matching.
print({}, "h"} returns 2 arguments with 2 arguments expected, which doesn't run.
print("h", {}) returns 3 arguments with 2 arguments expected, which runs fine.
How to fix?

**Comment by Tenrys** [comment]
The fix mentioned above is not a fix. Things are still wrong.

**Comment by whc2001** [comment]
It's hilarious to see an issue closed without any solution after four years. I am also encountering this problem. After some investigation looks like the cause of the problem is here:

https://github.com/NLua/NLua/blob/1ed41045a15ed4bfd88adb8204996f627c2d167d/src/Metatables.cs#L1477

When the parameter passed in is a table, it somehow tries to unfold the table and populate the items into the parameter of the function, rather than passing it whole as a `LuaTable` instance. As a test if I comment out the code block, the custom log function does what I wanted, but that certainly is not the solution since there are other code sections also referencing this method.
