### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Fraysa** [NLua/NLua#175]
I have a few questions regarding NLua.

1. How can I use an enum that's defined in my application? For example, I want to use the enum "Fruits", and use it in the Lua script like so:

``
addFruit(Fruits.Banana);
``

2. What's the "best" way to define functions? I'm currently doing:

``
            this.Lua.RegisterFunction(name, this, this.GetType().GetMethod("name", flags));
``

3. I have a method that returns IEnumerable<Lobby>. I want to use that in Lua just like I would use an array. I define it like so:

``
lobbies = getLobbies();

for i = 1, #lobbies do
	addText(lobbies[i].Name);
end
``

That's not enough, how can I make it work?

Thank you!

**Comment by viniciusjarina** [comment]
Hello @Fraysa 

Thank you for your questions,  :wink: good to see people using this library.

1- to use enum you can use the luanet.enum method (example: https://github.com/codefoco/NLuaBox/blob/00af36aa480281ae33835173430a806c54c2f9dc/Resources/source/OutputViewController.lua#L41 )

2-to iterate through IEnumerable you need to use luanet.each method https://github.com/codefoco/NLuaBox/blob/master/Resources/source/ScriptsDataSource.lua#L166
