### ISSUE TITLE
Error "A .NET exception occured in user-code" when load any assembly 

### ISSUE THREAD

**Issue by sergeyzalunin** [NLua/NLua#176]
```
using (Lua context = new Lua())
{
     context.LoadCLRPackage();
     string  script = string.Format("package.cpath = \"{0}\" .. package.cpath", @"C:\net assembly directory\?.dll;");
     context.DoString(script);
     context.DoString("luanet.load_assembly('NotMyNetAssembly')"); // Here, I get the error ""A .NET exception occured in user-code
}
```
All assemblies compiled in same architecture 'x64'.
How can I load any assembly?

**Comment by viniciusjarina** [comment]
Hello @sergeyzalunin cpath is only used to load native libraries
The load_assembly will use Assembly.Load and will check the assemblies from the current directory, the module directory and the PATH. you can change your path, move your .dll to the exe directory, or patch NLua and write a luanet.load_assembly_from using Assembly.LoadFrom

**Comment by sergeyzalunin** [comment]
Thank you @viniciusjarina. Your answer was helpful. I patched NLua and using Assembly.LoadFrom. 
```
if (File.Exists(assemblyName))
	assembly = Assembly.LoadFile(assemblyName);
else
{
	#if NETFX_CORE
		assembly = Assembly.Load (new AssemblyName (assemblyName));
	#else
		assembly = Assembly.Load(assemblyName);
	#endif
}
```

**Comment by viniciusjarina** [comment]
:wink: cool
