### ISSUE TITLE
Froze when calling `NLua.Lua(LuaState)`

### ISSUE THREAD

**Issue by zacx-z** [NLua/NLua#178]
When I used `NLua.Lua(LuaState)` constructor, the program froze on Unity. The code was:

``` csharp
luaState = LuaLib.LuaLNewState();
lua = new NLua.Lua (luaState);
```

I commented all other code and the program still froze. It should happen right in the constructor.

I want to access `luaState` because I want to program coroutine on the interpreter side. It will be great if NLua supports `LuaResume` and checking status code (which might be LUA_YIELD).

**Comment by viniciusjarina** [comment]
Hello @ladace do you know if this only happens on Unity ?

**Comment by ladace** [comment]
I tried to test this code in Xamarin Studio, by replacing `lua = new NLua.Lua()` with the code above. It crashed and Xamarin reported this: `PANIC: unprotected error in call to Lua API (attempt to index a nil value)`.

**Comment by viniciusjarina** [comment]
This is odd..can you gist your test? Thank you

**Comment by Hromon** [comment]
I got this error too.
![image](https://user-images.githubusercontent.com/29508584/89100845-36f15f00-d403-11ea-85f0-1442891d051f.png)
