### ISSUE TITLE
Failing to call base class extension methods

### ISSUE THREAD

**Issue by Hexalotl** [NLua/NLua#181]
I ran into an issue where NLua failed to call the extension methods found in a derived class. Poking around inside of GeneralExtension.cs I saw that the method GetExtensionMethods has a potential problems. An extension method is only added to the list if "method.GetParameters () [0].ParameterType == type" is true. This makes it so extension methods of the base class are excluded. Instead the check can be:

where (method.GetParameters () [0].ParameterType == type || type.IsSubclassOf(method.GetParameters()[0].ParameterType))

This will make it so base class extension methods are available as well.

**Comment by viniciusjarina** [comment]
Hi @Dynameter can you send a PR with the patch + a test 🙏

**Comment by aravol** [comment]
it might be better to check whether `type.IsAssignableFrom(method.GetParameters() [0].ParameterType)` as the `IsSubclassOf` doesn't properly respect generic covariance and contravariance

**Comment by viniciusjarina** [comment]
cc @Dynameter 

@aravol  can you send a PR ?
