### ISSUE TITLE
Null exception when invoking method with no returns as `Func<object[]>`

### ISSUE THREAD

**Issue by aravol** [NLua/NLua#183]
- Compiling on .NET 4.5.1 with Visual Studio 2015.
- Utilizing NLua_Safe assembly from NuGet, version 1.3.2.1

Attempting to invoke a Lua function which does not return anything, but is stored in .NET as a `Func<object[]>`. This function is able to be saved and even invoked correctly, however immediately after being invoked a `NullReferenceException` is thrown with the following stacktrace:

> NLua.dll!NLua.Method.LuaDelegate.CallFunction(object[] args, object[] inArgs, int[] outArgs)
> NLua_generatedcode!LuaGeneratedClass1.CallFunction()
> Testbed.exe!Testbed.Program.CallFunction() Line 29

The source code to reproduce this issue is as follows:

```
using System;
using NLua;

namespace Testbed
{
    static class Program
    {
        private static Func<object[]> _obj;

        [STAThread]
        private static void Main()
        {
            var lua = new Lua();
            lua.RegisterFunction("RegisterFunction", new Action<Func<object[]>>(RegisterFunction).Method);
            lua.RegisterFunction("CallFunction", new Action(CallFunction).Method);
            lua.DoString(
@"RegisterFunction(
    function()
        print(""Hello World!"")
    end
)

CallFunction()");
            Console.ReadKey(true);
        }

        private static void CallFunction()
        {
            _obj?.Invoke();
        }

        private static void RegisterFunction(Func<object[]> obj)
        {
            _obj = obj;
        }
    }
}
```

**Comment by viniciusjarina** [comment]
Why register a function if you can simple give a name to it and call :-) ?

**Comment by aravol** [comment]
This was primarily an example - the specific use case is the possibility of using NLua to sandbox a modding API for a game, in which case callbacks will abound. This is both the shortest-reproductive code as well as me getting my feet wet with registering and invoking callbacks.

I think I found where in source this is happening, but having some issues building due to a missing Lua52.dll - will make a merge when I get that worked out.

**Comment by viniciusjarina** [comment]
Cool :)  remeber lua is submodule from KeraLua .. so ideally just use `git submodule update --init --recursive`

**Comment by viniciusjarina** [comment]
But my point is if you gonna call your function from Lua, you don't need to register them. The register method should be used to register C# method to be called from Lua, :wink:

**Comment by aravol** [comment]
Submodules updated recursively, still not getting the DLL. Is it something that normally needs to be installed externally? This may be due for another issue to include a page on build procedures in the readme ;3

**Comment by viniciusjarina** [comment]
do you have CMake installed? Try to run `run_all.win64.bat`
