### ISSUE TITLE
Require from Lua environment?

### ISSUE THREAD

**Issue by bbor** [NLua/NLua#185]
Hi,
I'm trying to get NLua to work from a Lua environment that's embedded inside another app (64-bit Windows), but I can't get it happening. 
I can build the NLua DLLs, but if I try to "require()" them from the Lua environment I get a message that the specified procedure could not be found. I assume that means there's no `luaopen_xxx` function exported for the Lua package loader to call.
Is there another way I can get them loaded? Or does NLua only work when running the Lua environment inside .NET?
Thanks for your help.

**Comment by bbor** [comment]
Well I guess I found my answer, it's not expected to work.

LuaInterface 1.5.3 might have worked, since it had that luanet.dll. However, the binaries that I've been able to find are x86 only, and I can't track down the pre-2.x source code anywhere to build it myself. So I guess there's no way to call out to .NET from a vanilla Lua environment (LuaJIT, actually).

**Comment by viniciusjarina** [comment]
@bbor This application is using which version of Lua? is using as a static library already linked? or is using as a dll? 

Thanks

**Comment by bbor** [comment]
It's using LuaJIT 2.1.0, dynamically linked.
