### ISSUE TITLE
How to compile NLua without PInvoke

### ISSUE THREAD

**Issue by SirusDoma** [NLua/NLua#186]
I just found out this project today
By looking at the readme doc, it's seems easy to use and powerful

However, I'm stuck with C# and .NET 2.0 at the moment.
I use LinqBridge to get Linq features, also I prefer something clean without PInvoke
So my question is how do i compile the project without PInvoke and re-target .NET to 2.0?

I know it might arise some errors upon re-targeting .NET to 2.0, but I'm sure I could handle it with LinqBridge to aid the System.Linq dependency and a little bit modification.

Thanks in advance!

**Comment by viniciusjarina** [comment]
Hello @SirusDoma 

Just get the latest version, and use the `KopiLua` instead `KeraLua`

KopiLua is plain C# and has not any PInvoke calls

Thanks
