### ISSUE TITLE
Calling generic method

### ISSUE THREAD

**Issue by SirusDoma** [NLua/NLua#187]
How do I call generic method inside Lua?
For example, I can do this in C#:

```
// Something like this
MyObject object = HelperClass.Load<MyObject>("test");

// Or initiate generic class
var object = new MyObject<int>();
```

Any ideas?
Thanks in advance!

**Comment by nvirth** [comment]
If no better idea from anyone, I would write a C# wrapper function for it, and use Reflection to call the generic method.
We've been used this wrapper approach when we had to subscribe/unsubscribe for events from lua, and it worked well.

**Comment by SirusDoma** [comment]
It's an old question and I think no one have any idea to achieve this goal.
and I still don't have the solution for this..
