### ISSUE TITLE
Runtime example in example

### ISSUE THREAD

**Issue by BennyEmmers** [NLua/NLua#190]
In the example : _Retrieving Lua functions _ the next line will give an runtime exception  : var res = (int)scriptFunc.Call (3, 5).First ();
The conversion from obj to int is not correct. Using:   var res = Convert.ToInt32( scriptFunc.Call(3, 5).First()); then it will work
Btw very nice work ! Thank you :+1:

**Comment by viniciusjarina** [comment]
Thanks. This happens because numeric types are boxed as Double, so you will need to first cast to `double` then `int`, or use `Convert` 😉
