### ISSUE TITLE
Runtime is very sluggish after updating after about a year

### ISSUE THREAD

**Issue by DaedalusGame** [NLua/NLua#191]
I started using this library about a year ago. Not sure as to the exact date as my first commit to my main repo was in September 2015 and it was already a part of it back then. Recently, about 2 months ago I tried upgrading for that sweet operator and delegate stuff, but found the binaries on the main website unable to run, so I went with grabbing the packages from NuGet as suggested in one of the other issues.
There just ended up being one problem with those new packages: They're about 600x slower. The problem persists even to this day, when I downgraded from newest (downloaded today) to the version i had been using yielded a speed increase from several seconds of execution to barely anything.

**Comment by viniciusjarina** [comment]
Hello @DaedalusGame 

Are you using the plain C# version (Safe) or the P/Invoke version ?

**Comment by DaedalusGame** [comment]
I appear to be using the P/Invoke version from NuGet, which is the one that isn't titled "(safe)"

**Comment by viniciusjarina** [comment]
Well not much has changed  to give a 600x slower performance :cry: 

Can you profile and see where exactly this performance issue is coming from

**Comment by DaedalusGame** [comment]
Okay I was lazy with this stuff and only tested a single run when I said it wasn't reproducible, now I'm back with some more data:

for (int i = 0; i < 1000; i++)
lua.DoString(@"blah:TestFunction();blah:TestFunction();blah:TestFunction();blah:TestFunction();blah:TestFunction();blah:TestFunction();");

for 10 iterations, 13ms on the old version, 15ms on the newest version.
for 1000 iterations, 44ms on the old version, 145ms on the newest version.
for 1000000 iterations, 22 seconds on the old version, 2 minutes and 13 seconds on the new version.

TestFunction is a public, non-static method on a C# class which simply performs an arithmetic operation with no return value.

**Comment by viniciusjarina** [comment]
@DaedalusGame well this could be a regression, do you have any idea where is the bottleneck ?

Thank you

**Comment by Zenroth** [comment]
@DaedalusGame Did you have a chance to look into this any further? Or could you possibly provide a link to an archive of your older NLUA copy? I'd love to take a look at it, given we're also seeing some strange performance around lua, that didn't use to exist.

**Comment by DaedalusGame** [comment]
sorry, i didn't have any chance to look into it further, but i do still have my old NLUA copy. I will dig it up and throw it here, assuming I don't violate the license in doing so :)

**Comment by Zenroth** [comment]
Thanks, I appreciate you taking the time to respond, and check if its alright to repost.

**Comment by DaedalusGame** [comment]
looks like the answer is that I was using 1.3.0.0 of both KeraLua and NLua
https://www.nuget.org/packages/NLua/1.3.0
I remember that a newer version also changed case sensitivity of member names (it used to be insensitive)
