### ISSUE TITLE
Problem porting LuaInterface to NLua

### ISSUE THREAD

**Issue by JeroenLeiden** [NLua/NLua#197]
I have a problem replacing LuaInterface with NLua.
In my project I have functions that accept string parameters, but the lua scripts that use the functions sometimes give numbers.
With LuaInterface the numbers were just converted to strings and everything worked.
With NLua the numbers don't get converted, I get the error invalid arguments to method call
Example code :

```
    public void TestFunction(string parameter)
    {
        MessageBox.Show(parameter);
    }

    private void Form1_Load(object sender, EventArgs e)
    {
        Type type = GetType();
        MethodInfo methodInfo = type.GetMethod("TestFunction");

        LuaInterface.Lua luaInterface = new LuaInterface.Lua();
        luaInterface.RegisterFunction("TestFunction", this, methodInfo);

        NLua.Lua nLua = new NLua.Lua();
        nLua.RegisterFunction("TestFunction", this, methodInfo);

        luaInterface.DoString("TestFunction(\"Hello world from luaInterface\")");

        nLua.DoString("TestFunction(\"Hello world from NLua\")");

        luaInterface.DoString("TestFunction(1)");

        nLua.DoString("TestFunction(2)");
    }
```

It's not really an option to change the code or scripts at all places so that each parameter is always a string or always a number because there are already many scripts in use that are not allowed to break.
Is it possible to get NLua to convert numbers to strings automaticly?

**Comment by viniciusjarina** [comment]
What is the error triggered calliing `TestFunction`? 
Also, why not create a `TestFunction(int x) { TestFunction(x.ToString()) }` ?

**Comment by JeroenLeiden** [comment]
A LuaScriptException with the message "invalid arguments to method call".

I've solved it by changing
public void TestFunction(string parameter)
to
public void TestFunction(object parameter)
and using parameter.ToString()

Work for changing all functions that can be called from lua was a few hours, but all the scripts that are in use still work without changes.
