### ISSUE TITLE
Implicit operator is not working via lua

### ISSUE THREAD

**Issue by SirusDoma** [NLua/NLua#199]
Hi, I tried to instantiate an object with following constructor:

```
Foo(string, Bar)
```

While `Bar` has implicit operator to another class, let's say it's `CObject` class.
When I instantiate `Foo` In .NET like..

```
var foo = new Foo("Test", new CObject());
```

It doesn't have problem, but if I do it in Lua:

```
local foo = Foo('Test', CObject())
```

It's throw me an error on .NET, it says "Foo does not contain constructor(.ctor) argument match"
Well, is it possible to use implicit operator in Lua?

**Comment by viniciusjarina** [comment]
I think `op_Implicit` is not implemented

I can't implement now (due lack of timing to do this) but I will try to do it later and I close this issue when is done.

Thank you @SirusDoma

**Comment by SirusDoma** [comment]
Thanks for reply and take your time
