### ISSUE TITLE
The ObjectTranslatorPool throw exception when destroy&create Lua frequently in multithread

### ISSUE THREAD

**Issue by dayongxie** [NLua/NLua#200]
The exception is throwed at function Add, when create an Lua instance.
 `ArgumentException ("An item with the same key has already been added. ", "luaState");`

**Comment by AntonNep** [comment]
@dayongxie, have you tried using a version containing NLua concurrency fix (#196)?

**Comment by dayongxie** [comment]
Yes the version I used already include the commit of the fix(#196)
I think there is a situation would cause the exception:
When a thread destroy a luastate,  just then another thread create a luastate, the later luastate may be have the same address as the earlier,  if the later luastate call ObjectTranslatorPool.Add  before the earlier luastate remove from ObjectTranslatorPool, the exception will throw.

**Comment by 666marat666** [comment]
I was able to reproduce the same today also with last build.

**Comment by kalin-toshev** [comment]
Yes, I looked at the Lua.Close and it seems that luaState is closed *before* it's removed from the (global) object translator pool. The fix I think would be to change the order of these in Lua.Close (Lua.cs) to avoid situation, where a new state is created (with the same address) before it's removed from the global dictionary.

**Comment by kalin-toshev** [comment]
I created a new pull request with a fix for this.

**Comment by Artum** [comment]
Notice that there are some more exceptions in multi-threaded execution. I've opened a ticket for that:
#247
