### ISSUE TITLE
unprotected error in call to Lua API (0)

### ISSUE THREAD

**Issue by imrenuijen** [NLua/NLua#201]
I am using NLua in my application and it runs great except after a while I get the error: "unprotected error in call to Lua API (0)". I get the error in Visual Studio 2015 at invoking an eventhandler in my C# code. I looked at Lua error codes is 0 equals to NIME_OK. If this is really the meaning of the error message can I ignore the exception and further more how can I ignore that exception?

**Comment by viniciusjarina** [comment]
Hi @imrenuijen do you have way to repro that in a small program? or even better an unit test?

If so, can you make a PR ;-) I will take a look as soon I have time

Thank you.

**Comment by imrenuijen** [comment]
Hello Vinicius,

I have looked further into the problem with concurrency using async functions in Javascript. I thought I need to write custom JavaScript for it to function or that it might only be possible to do it using a combination of JavaScript and server side code. By looking for JavaScript in combination with Mutex I found a library for Mutex in JavaScript. Below is an example with the intention of the app I wrote in Angular:


// JavaScript source code
var mutex = new Mutex();

var n = 100;
var arr = [];
var arr2 = [];

// initial array which is populated before the rest of the events
for (var i = 0; i < n; i++) {
    var obj = { status: false, timestamp: Date.now() };
    arr.push(obj);
}

setTimeout(function(){
    // Fake result from a server
    for (var i = 0; i < n; i++) {
        arr2[i].status = false;
        arr2[i].timestamp = Date.now();
    }

    // updating array with result from server checking if current result is newer than server result
    for (var i = 0; i < n; i++) {
        mutex.lock(function () {
            if (arr[i].timestamp < arr2[i].timestamp) {
                arr2[i].status = false;
                arr2[i].timestamp = Date.now();
            }
            mutex.unlock();
        });
    }
}, 0);

// pressing a button on html page
setTimeout(function () {
    mutex.lock(function () {
        arr[50].status = true;
        arr[50].timestamp = Date.now();
        mutex.unlock();
    });
}, 300); // adjusting number to check when status is true


for (var i = 0; i < n; i++) {
    console.log(i);
    console.log(arr[i]);
}

I hope hearing from you soon,

Imre Nuijen
