### ISSUE TITLE
unexpected behaviour expecting number instead of boolean argument #2 math.pow

### ISSUE THREAD

**Issue by imrenuijen** [NLua/NLua#202]
I have the following function below:

local function handleButtonChangedBoard(sender, e)
    for i=0, 7 do
        buttons[i] = bit32.band(e.Buttons, math.pow (2, i)) > 0
    end
end

The function works fine for almost a day and when repeatedly calling this function after a while I get an error suggesting that the value of i becomes a boolean.

**Comment by viniciusjarina** [comment]
Without a repro is really hard to tell what is going on, thank you for reporting anyway.
