### ISSUE TITLE
Invalid path for post-build-event when working on different computers

### ISSUE THREAD

**Issue by UweKeim** [NLua/NLua#204]
### Scenario

**PC 1:** A [SVN](https://en.wikipedia.org/wiki/Apache_Subversion)-based solution using NLua is located in "C:\MyProjects"
**PC 2:** The same SVN-based solution using NLua is located in "D:\Projects
### Steps
1. Add the NLua NuGet package on PC 1.
2. Commit the solution to SVN on PC 1.
3. Check out solution via SVN on PC 2.
4. Build solution on PC 2.
### Error

XCOPY complains with return code 4 about a path not found.

The post build event looks like this:

``` xml
<PostBuildEvent>
    xcopy /s /y "C:\MyProjects\MyProject\packages\NLua.1.3.2.1\lib\native\*.*" "$(TargetDir)"
</PostBuildEvent>
```

I.e. there is an _absolute_ path contained.
### Reason

_(This is some guessing, since I do not know NuGet and PowerShell in-depth)_

The file `install.ps1` inside the NuGet package of NLua contains these lines:

``` powershell
# Append our post build command if it's not already there
if (!$currentPostBuildCmd.Contains($LibLuaPostBuildCmd)) {
    $project.Properties.Item("PostBuildEvent").Value += $LibLuaPostBuildCmd
}
```

To my understanding the comparison inside `install.ps1` skips the addition of the correct post build event for PC 2, because it sees the path in the post build event, although it is a path that is correct on PC 1 only.
### Solution

If my above asumption is correct, I would suggest do to either one of the following:
- `install.ps1` should remove the post build event call path on PC 2 that came from PC 1 and replace it with the path on PC 2. -or-
- `install.ps1` should never add a full path but only a relative path.

Actually, I would strongly prefer the second option.
### Summary

Hopefully my explanation is understandable and I did not understand the whole behaviour wrong.

Maybe I'm doing something completely wrong to get the above behaviour. If yes, I would be happy to get some hints.

**Comment by mpp** [comment]
I've got the same problem.
I set manually the relative path with:
`xcopy /s /y "$(SolutionDir)packages\NLua.1.3.2.1\lib\native\*.*" "$(TargetDir)"`

**Comment by Eegee** [comment]
The PostBuildEvent of @mpp ( $(SolutionDir)packages... ) is the solution and should be used as such IMHO.

**Comment by viniciusjarina** [comment]
No longer using Postbuild event. Using the custom MSBuild .targets. The NuGet should work fine now.
