### ISSUE TITLE
Class methods in C# are strings in Lua

### ISSUE THREAD

**Issue by soccermitchy** [NLua/NLua#205]
When I try to do this:

``` csharp
class UsedInLua
{
    static void DoStuff(string message)
    {
        Console.WriteLine(message);
    }
}
public static class Program {
    private Lua state = new Lua();
    static void Main(string[] args)
    {
        state.LoadCLRPackage();
        state.DoString(@"import('MyProgramNamespace')
                       print(type(UsedInLua().DoStuff))");
    }
}
```

I get 'string' as the output from it, showing that methods in a class are strings.
Am I doing this right?
(not my exact code but it's close enough to what i'm doing to get the point across)

**Comment by fusspawn** [comment]
the . notation is for static functions and properties.  use : for instance methods 

`UsedInLua():DoStuff()`

Or at least that seems to work for me.

**Comment by soccermitchy** [comment]
Just tried that, I get "attempt to call method 'DoStuff' (a string value)"

**Comment by igniuss** [comment]
If its a static class, you should use a period, not a ':', I think that's the issue you're having.

**Comment by soccermitchy** [comment]
I have the same error either way I do it

**Comment by igniuss** [comment]
What about if you do UsedInLua.DoStuff("test"); ? That should work just fine, as long as UsedInLua is accessible inside your lua runtime. I'm not sure why the void is returning as a string though..

**Comment by soccermitchy** [comment]
Just tried it, not working. I'll just give you the actual code that I'm using for it...
(This is for a GTA5 mod, hence stuff like the 'using GTA;')
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using GTA;
using NLua;

namespace GTACoOp
{
    class LuaClient
    {
        static void sendNotification(string message, bool flashing = false)
        {
            UI.Notify(message, flashing);
        }
    }
    class LuaScript // just doing it this way because I'm going to have multiple places 
                    // where scripting is used and I want it to be loaded the same
                    // every time
    {
        private Lua state = new Lua();
        private string script;

        public LuaScript(string runScript)
        {
            script = runScript;
            state.LoadCLRPackage();
        }

        public void Run()
        {
            try
            {
                state.DoString(script, "script");
            }
            catch (Exception e) // Using errors as my output because where this is 
                // being run in the code, notifications from UI.Notify are my only output
                // other than errors.
            {
                List<String> logFileContents = new List<String>();
                logFileContents.Add(e.ToString());
                File.AppendAllLines("scripts/TinyMP.log", logFileContents);
            }
        }
    }
}

// Then I'm doing this:
// LuaScript script = new LuaScript('import("GTACoOp') LuaClient().sendNotification'Hello')")
// script.Run()
```

**Comment by soccermitchy** [comment]
It also does the same thing if I put this inside the constructor:
```csharp
LuaClient client = new LuaClient();
state["LuaClient"] = client;
```

**Comment by igniuss** [comment]
`new LuaScript('import("GTACoOp') LuaClient().sendNotification'Hello')") ` shouldn't work though..
`new LuaScript('import('GTACoOp'); LuaClient.sendNotification("Hello")` I think that's how you're supposed to do it. Could be mistaken though.

**Comment by soccermitchy** [comment]
@igniuss Neither worked, just tried it with both. This time i'm getting `unknown member name sendNotification` though

**Comment by Twanaar** [comment]
I have the same error, and can't found a workarround:

init:
          _LuaState = new Lua();
            _LuaState.LoadCLRPackage();
            _LuaState.DoString(@" 
                                import ('NinjaTrader.Custom', 'NinjaTrader.Strategy.StrategyInterfaceExtern')
                               ", "Import");

i'm try all of this:

            _Lua.GetLuaState()["obj"] = this;

            var l = this.GetType().GetMethod("LuaGetIndicatorOutput");

            System.Reflection.MethodBase mb = l;

            if(mb != null)
            {
                _Lua.GetLuaState().RegisterFunction("LuaGetIndicatorOutput", this, mb);
            }

in lua:
function TestFunc(val1, val2) 
   val=obj:LuaGetIndicatorOuput() 
   if val > val2 then 
        return val1 + 1 
      else 
       return val2 - 1 
   end 
end

then calling it with:
_Lua.GetLuaState().DoString(@"TestFunc(10, 50)");

i have 
NLua.Exceptions.LuaScriptException: [string "FuncRegister"]:1: attempt to call method 'LuaGetIndicatorOuput' (a string value)

if i'm use calling with obj:LuaGetIndicatorOuput() 

and if i'm use function registred by RegisterFunction

NLua.Exceptions.LuaScriptException: [string "FuncRegister"]:1: attempt to call method 'LuaGetIndicatorOuput' (a nill error)

**Comment by viniciusjarina** [comment]
cant repro.
