### ISSUE TITLE
io.open() "a" mode produces "Invalid argument" error

### ISSUE THREAD

**Issue by agalapovs** [NLua/NLua#206]
io.open(filename, "a") gives "Invalid argument to method call" error.

``` lua
output = [[C:\Users\user\logging.txt]]
log, error, msg = io.open(output, "a")
if log then
    log:write("test")
    log:close()
else
    echo(msg)
end
```

Note that "w", "w+", "r" and "r+" don't give such an error.

NLUA: 1.3.2

**Comment by viniciusjarina** [comment]
What happen when you do the same using the plain Lua?
This shouldn't be affected by NLua, `io.open` will call the native implementation of Lua 😕

**Comment by agalapovs** [comment]
Tested with LUA 5.3.3 and 5.2.3 on Wndows platform - works like a charm.
I was wondering if somebody has a similar problem. I don't exclude some wanky behavior in my wrapper.

**Comment by viniciusjarina** [comment]
I've bumped the upstream Lua to 5.3.5 that should fix the issue.
