### ISSUE TITLE
Where is Install/Build instructions for linux?

### ISSUE THREAD

**Issue by dcanoh** [NLua/NLua#209]
Hello, could put the instructions for users of GNU / Linux?

I would like to test this library, greetings.

**Comment by felaugmar** [comment]
Hey man, I'll try to help you.

Well, for use through Linux, you need to use [mono](http://www.mono-project.com/), that's the implementation of .NET platform for Linux and OS X, With this, you can run code for .NET, like C#.

If you're programming at Linux, I recommend you use [monodevelop](http://www.monodevelop.com/), but it's not so powerful and amazing like Visual Studio are, but is a good alternative.

**Comment by dariocanoh** [comment]
OK, I need mono installed. 

Thank you very much i'll try install it.
