### ISSUE TITLE
Passing multiple arguments from Lua call to C# function.

### ISSUE THREAD

**Issue by NewbProgramming** [NLua/NLua#213]
Like if I wanted to make an Lua version of Console.WriteLine:

WriteLine("{1} says '{0}'", "Hello World!", "NewbProgramming") -- in Lua

What do I do to get arg1 and arg2 and so on?

private void Lua_WriteLine() { // C#
    List<string> argument_list = new List<string>();
    // Get args here.
   // Order converted params.
   string write = string.Join(" ", argument_list);

   Console.WriteLine("Lua> {0}", write);
}

P.S.
I know I can do:
print(string.format("Lua> %s says '%s'", "NewbProgramming", "Hello World!")) -- Lua
to achieve the same result, it's not my point though.
Also with Numbers (double), Boolean, and Strings. Just these three is fine.

**Comment by viniciusjarina** [comment]
You can using `param` args from C#
