### ISSUE TITLE
NLua.Exceptions.LuaException when using NLua.Lua(LuaState) constructor

### ISSUE THREAD

**Issue by theconezone** [NLua/NLua#214]
This code snippet

```
using NLua;

namespace Test {

    class Program {

        static int PanicCallback(KeraLua.LuaState luaState) {
            string reason = string.Format("unprotected error in call to Lua API ({0})", LuaLib.LuaToString(luaState, -1));
            throw new NLua.Exceptions.LuaException(reason);
        }

        static void Main(string[] args) {

            KeraLua.LuaState internalState = LuaLib.LuaLNewState();
            LuaLib.LuaLOpenLibs(internalState);
            KeraLua.LuaNativeFunction panicCallback = new KeraLua.LuaNativeFunction(PanicCallback);
            LuaLib.LuaAtPanic(internalState, panicCallback);
            new Lua(internalState);
            KeraLua.Lua.LuaClose(internalState);
        }

    }

}

```

causes this exception:

> Unhandled Exception: NLua.Exceptions.LuaException: unprotected error in call to Lua API (attempt to index a nil value)
>    at Test.Program.PanicCallback(LuaState luaState) in Program.cs:line 9
>    at KeraLua.NativeMethods.LuaSetTable(IntPtr luaState, Int32 index)
>    at KeraLua.Lua.LuaSetTable(IntPtr luaState, Int32 index) in NLua\Core\KeraLua\src\KeraLua\Lua.cs:line 91
>    at NLua.LuaLib.LuaSetTable(LuaState luaState, Int32 index) in NLua\Core\NLua\LuaLib\LuaLib.cs:line 174
>    at NLua.Lua.Init() in NLua\Core\NLua\Lua.cs:line 323
>    at NLua.Lua..ctor(LuaState lState) in NLua\Core\NLua\Lua.cs:line 306
>    at Test.Program.Main(String[] args) in Program.cs:line 18

If anyone has a workaround or explanation for why this happens, it would be appreciated.

**Comment by theconezone** [comment]
Found the issue. Lua.Init() expects the "luanet" global to be defined, but it is not defined unless we do not pass in our state. There are two ways to fix this.

Define "luanet" ourselves when passing in the state, or modifying Lua.Init and changing

```
if (_StatePassed == false) {
	LuaLib.LuaNewTable (luaState);
	LuaLib.LuaSetGlobal (luaState, "luanet");
}
```

to

```
LuaLib.LuaNewTable (luaState);
LuaLib.LuaSetGlobal (luaState, "luanet");
```

I chose the first method, because I don't want to maintain my own version of NLua.

**Comment by viniciusjarina** [comment]
It seems you should use `KeraLua` only there is Nuget now only for KeraLua, so you don't need the entire NLua overhead.

**Comment by theconezone** [comment]
Hey @viniciusjarina -- thanks for the response. I believe you misunderstand though. The example I posted was just intended to illustrate how to recreate the bug in the NLua constructor.

Here is an example showing that the issue is still present, actually using NLua interop:

```
using System;
using NLua;
using KeraLua;

namespace NLuaTest
{

    //from the example
    public class SomeClass
    {

        public string MyProperty { get; private set; }

        public SomeClass(string param1 = "defaulValue")
        {

            MyProperty = param1;

        }

    }

    public class Program
    {

        public static void Main(string[] args)
        {

            using (KeraLua.Lua internalState = new KeraLua.Lua(true))
            using (NLua.Lua state = new NLua.Lua(internalState))
            {

                state["obj"] = new SomeClass("Param");
                state.DoString(@"print(obj.MyProperty)");

            }

        }

    }

}

```

Here is an example showing a workaround:

```
using System;
using NLua;
using KeraLua;

namespace NLuaTest
{

    //from the example
    public class SomeClass
    {

        public string MyProperty { get; private set; }

        public SomeClass(string param1 = "defaulValue")
        {

            MyProperty = param1;

        }

    }

    public class Program
    {

        public static void Main(string[] args)
        {

            using (KeraLua.Lua internalState = new KeraLua.Lua(true))
            {

                internalState.NewTable();
                internalState.SetGlobal("luanet");

                using (NLua.Lua state = new NLua.Lua(internalState))
                {

                    state["obj"] = new SomeClass("Param");
                    state.DoString(@"print(obj.MyProperty)");

                }

            }

        }

    }

}

```

While I suppose it's not necessary to be able to pass in a KeraLua state, it is a public constructor and this issue should probably be addressed. I believe if the NLua constructor were to define the global table "luanet" if it doesn't exist will be sufficient.

**Comment by viniciusjarina** [comment]
Not sure why this ctor is arround. Probably legacy from LuaInterface days.
Silly question, why do you need to create your own KeraLua.Lua object ?

**Comment by theconezone** [comment]
That's actually a very good question. You can just get the internal Lua state from the property. Maybe the property didn't exist at the time, or I just didn't notice it?

I can't think of any initialization that would need to occur before NLua's state is created. Maybe just removing the constructor is in order? Anyway, just wanted to make sure you were aware the issue still existed.

**Comment by viniciusjarina** [comment]
I will remove the ctor. Also I am planning to make NLua.Lua class inherit from KeraLua.Lua so will be possible to use FromIntPtr and throw away ObjectTranslatorPool, but the public API should remain the same 😉

**Comment by alandoherty** [comment]
Just want to weigh in, encountered this same problem as I wanted to create a KeraLua state with reduces libraries (no file IO/os access). While I can just remove the globals after the fact, the code is ran quite frequently so wanted to experiment with increasing throughput. I still want to use some part of the wrappers that NLua provides, without having to support the entire luanet bridge and Lua -> CLR functionality.

This bug was initially quite confusing, KeraLua also suffers from not importing the luaopen_* (afaik) references and I can't a function to open certain references.

In the end I had to do this:

```csharp
static class ExtendedNativeMethods
{
	[DllImport("lua53", CallingConvention = CallingConvention.Cdecl)]
	internal static extern int luaopen_base(IntPtr luaState);
}

// create kera state
KeraLua.Lua luaState = new KeraLua.Lua(false);
luaState.RequireF("_G", ExtendedNativeMethods.luaopen_base, true);
luaState.DoString("luanet = {} for k, v in pairs(_G) do print(k) end");

// create lua state
Lua lua = new Lua(luaState);

// working NLua lua state with only base opened
```
```
ipairs
pcall
rawequal
select
dofile
_VERSION
print
rawget
rawset
assert
error
getmetatable
_G
next
xpcall
type
tostring
tonumber
rawlen
collectgarbage
luanet
pairs
setmetatable
loadfile
load
```

I like the API and the way NLua does things, but it would be nice if NLua had an option to disable the CLR/import bridging. In the end I still used just KeraLua as I don't want scripts to be able to use CLR types. It would also be nice if KeraLua had support to selectively require specific libraries without having to import the package functions myself from the so/DLL.
