### ISSUE TITLE
README.md is missing instructions for building and running

### ISSUE THREAD

**Issue by CraigCottingham** [NLua/NLua#217]
My specific interest is in Mac OS X, but there are no instructions for _any_ platform.

I have already downloaded and installed Mono, and have successfully built and run C# code with it, so I know it's working.

When I download the OS X package from the NLua home page here, all it contains is KeraLua.dll, NLua.dll, and liblua52.dylib. There's no .exe to run, and NLua.dll doesn't have an entry point defined.

I'm happy to PR an update to README.md, if someone else can explain to me _what_ I need to put in said update. 😃

**Comment by CraigCottingham** [comment]
Update: I decided to try building on OS X myself, to see if maybe the provided package is incomplete.

1. The section on building on OS X should indicate that `cmake` is required. It can be installed via Homebrew. (This is much a note to myself as anyone else.)
2. After installing `cmake`, I run `./run_all.osx.sh` and get (eventually)
```
Program.cs(46,24): error CS0234: The type or namespace name `Numerics' does not exist in the namespace `System'. Are you missing `System.Numerics' assembly reference?
Program.cs(47,24): error CS0234: The type or namespace name `Numerics' does not exist in the namespace `System'. Are you missing `System.Numerics' assembly reference?
```
Since I'm brand-new to C# and Mono, I don't know how to resolve this on my own. Yet.

**Comment by viniciusjarina** [comment]
Hi @CraigCottingham this used to work. 

I will take a look why is failing to build.

But the idea of NLua is to be used as a library in your C# application and not as a REPL.

**Comment by CraigCottingham** [comment]
Thanks, @viniciusjarina. I'm not intending to use it as a REPL in practice; I'm just looking for a way to confirm that what I have downloaded actually _works_. The README file shows what looks like a REPL in action, and it would be nice to be able to replicate the same thing myself. (And I think that goes for other users as well. 😄 )
