### ISSUE TITLE
After "DoFile",Chinese variable value become messy code

### ISSUE THREAD

**Issue by fgc0109** [NLua/NLua#219]
My code:
```
NLua.Lua luaFile = new NLua.Lua();
var data = luaFile.DoFile(m_FilePath);

name = (string)luaFile[nameof(name)];
description = (string)luaFile[nameof(description)];
```

Part of Lua File:
```
name = "击杀公告"
version = "160313.20.15" 
description = "当前版本: "..version.."\n修改内容如下：\n  海象、座狼、钢羊、电羊、蜘蛛女王和boss 击杀公告\n  击杀四季boss掉落远古豪华箱\n  威洛遭受攻击，攻击者会自燃\n 等...\n\n困难模式默认关闭（怪物提高血量和攻速）可以在设置开启\n友情提示：攻速和血量其中任何选项关闭将不掉落豪华箱子"
author = "Shang"
```

Result:

> name = "å\u0087»æ\u009d\u0080å\u0085¬å\u0091\u008a"
> version = "160313.20.15" 
> description =
> "å½\u0093å\u0089\u008dç\u0089\u0088æ\u009c¬: 160313.20.15\nä¿®æ\u0094¹å\u0086\u0085å®¹å¦\u0082ä¸\u008bï¼\u009a\n  æµ·è±¡ã\u0080\u0081åº§ç\u008b¼ã\u0080\u0081é\u0092¢ç¾\u008aã\u0080\u0081ç\u0094µç¾\u008aã\u0080\u0081è\u009c\u0098è\u009b\u009bå¥³ç\u008e\u008bå\u0092\u008cboss å\u0087»æ\u009d\u0080å\u0085¬å\u0091\u008a\n  å\u0087»æ\u009d\u0080å\u009b\u009bå­£bossæ\u008e\u0089è\u0090½è¿\u009cå\u008f¤è±ªå\u008d\u008eç®±\n  å¨\u0081æ´\u009bé\u0081­å\u008f\u0097æ\u0094»å\u0087»ï¼\u008cæ\u0094»å\u0087»è\u0080\u0085ä¼\u009aè\u0087ªç\u0087\u0083\n ç­\u0089...\n\nå\u009b°é\u009a¾æ¨¡å¼\u008fé»\u0098è®¤å\u0085³é\u0097­ï¼\u0088æ\u0080ªç\u0089©æ\u008f\u0090é«\u0098è¡\u0080é\u0087\u008få\u0092\u008cæ\u0094»é\u0080\u009fï¼\u0089å\u008f¯ä»¥å\u009c¨è®¾ç½®å¼\u0080å\u0090¯\nå\u008f\u008bæ\u0083\u0085æ\u008f\u0090ç¤ºï¼\u009aæ\u0094»é\u0080\u009få\u0092\u008cè¡\u0080é\u0087\u008få\u0085¶ä¸­ä»»ä½\u0095é\u0080\u0089é¡¹å\u0085³é\u0097­å°\u0086ä¸\u008dæ\u008e\u0089è\u0090½è±ªå\u008d\u008eç®±å­\u0090"
> author = "Shang"

It's not Unicode ,not ASCII  ,just messy code
the origin lua file is Encoding by UTF-8

https://github.com/fgc0109/DSTServerManager
This is my project
is there any one who can help me solve this problem?

**Comment by fgc0109** [comment]
https://github.com/fgc0109/DSTServerManager
This is my project
is there any one who can help me solve this problem?

**Comment by whc2001** [comment]
Check twice to make sure the file is encoded in UTF8. Try to read the file into memory, convert to UTF8 then use `DoString`.
```
    string script = File.ReadAllText("C:\\script.lua");
    byte[] scriptUtf8 = Encoding.Convert(Encoding.Default, Encoding.UTF8, Encoding.Default.GetBytes(script));    //Default is GB2312 on Chinese OS.
    lua.DoString(script);
```

**Comment by chenxuuu** [comment]
same problem
I run this code also cause the wrong result:

```csharp
NLua.Lua lua = new NLua.Lua();
lua["result"] = "";
lua.DoString("result = \"测试\"")
Console.WriteLine(lua["result"]);
```

output：

```
????
```

now I try to show the result what it become:

```csharp
NLua.Lua lua = new NLua.Lua();
lua["result"] = "";
lua.DoString("result = \"测试\"")
lua.DoString("result = string.gsub(result, \"(.)\", function(c) return string.format(\"%02X \", string.byte(c)) end)");
Console.WriteLine(lua["result"]);
```

output

```
B2 E2 CA D4
```

so it's very strange, because what I input should be a utf-8 string(`e6 b5 8b e8 af 95`), but in lua it's a GB2312/GBK string

now I convert all Chinese into Hex, to pass strings rightly

@viniciusjarina is this problem same as #48 ? How to solve this?

**Comment by whc2001** [comment]
NLua's `DoString` function accepts byte array as code input, so passing `Encoding.UTF8.GetBytes(yourLuaCode)` seems solve your problem.

**Comment by chenxuuu** [comment]
@whc2001 it works! thanks a lot!

**Comment by whc2001** [comment]
You are welcome!
