### ISSUE TITLE
long / UInt64 wrong number

### ISSUE THREAD

**Issue by Maufeat** [NLua/NLua#221]
Hello,

I have in my code a decrypt function which is:

`Blowfish:Decrypt(keyCheck.checkId)`

checkId is an unsigned 64bit integer and passes this value:
`17737349412413204480`
but in C# it passes this
`17737349412413205014`

which leads to wrong decryption.
so my check `if checkId == 1` gets false.

Any suggestions?

**Comment by felaugmar** [comment]
The fact is that your number is soo long, [https://www.lua.org/pil/2.3.html](check it).
You'll need to convert it to string to work properly.

**Comment by viniciusjarina** [comment]
Fixed by https://github.com/NLua/NLua/pull/290

**Comment by viniciusjarina** [comment]
Fixed: https://github.com/NLua/NLua/releases/tag/v1.4.11
