### ISSUE TITLE
Native Lua library output to x86/x64 folders

### ISSUE THREAD

**Issue by ghost** [NLua/NLua#224]
I started to use NLua and I am actually curious since the post build process is creating the folders x86 and x64 and copying the native libraries there. Isn't it possible to specifically select one of both architectures and have only one native library in the root folder of the application instead of both cluttering the system?

**Comment by viniciusjarina** [comment]
The idea of copying x64 and x86 dlls is to be able to work with both versions, native dependencies are really a problem to deal with. But you can just place the lua52.dll in the same folder of your KeraLua.dll
