### ISSUE TITLE
Calling extension methods that overload non-extension methods

### ISSUE THREAD

**Issue by adambiser** [NLua/NLua#225]
I have an extension method for Graphics as such:
```
public static void DrawImage2(this Graphics g, Bitmap srcImg, int x, int y, int srcX, int srcY, int width, int height)
{
    g.DrawImage(srcImg, x, y, new Rectangle(srcX, srcY, width, height), GraphicsUnit.Pixel);
}
```

Calling it from the lua script succeeds:
```
g:DrawImage2(image, 0, 0, 0, 0, 8, 8)
```

However, if I change "DrawImage2" to "DrawImage" in both places, I get this exception:
```
invalid arguments to method: Graphics.DrawImage,    at NLua.Lua.ThrowExceptionFromError(Int32 oldTop)
   at NLua.Lua.CallFunction(Object function, Object[] args, Type[] returnTypes)
   at NLua.LuaFunction.Call(Object[] args)
```

**Comment by viniciusjarina** [comment]
I am not following here, do you mind write a simple unit test with a couple of extension methods?

**Comment by adambiser** [comment]
It has been awhile, but I'll try to make up a test project, which I should have done when posting.  However, I'm getting the error mentioned in issue #267 when trying to install the NuGet package.

**Comment by adambiser** [comment]
I'm going to guess that I was trying to call the extension method in the Lua script as I would in C# (as a method of the object instance), but it appears they should be treated like a static method of the extension class.  I'm closing this.

ie:

`    public static class TestClassExtension
    {
        public static void DrawImage(this TestClass test, int x, int y, int z)
        {
            Console.WriteLine("Extension method call.");
        }
    }

    public class TestClass
    {
        public void DrawImage(int x, int y)
        {
            Console.WriteLine("TestClass.DrawImage was called.");
        }
    }
`
It looks like I was trying to do something like:
`test = TestClass()
test:DrawImage(1, 2)
test:DrawImage(1, 2, 3)
`
but I needed to do this instead.
`test = TestClass()
test:DrawImage(1, 2)
TestClassExtension.DrawImage(test, 1, 2, 3)
`
