### ISSUE TITLE
Using System.Drawing

### ISSUE THREAD

**Issue by Wiering** [NLua/NLua#226]
Hi, I'm trying to use NLua in c# to modify bitmaps and anything I try to use from System.Drawing gives an exception, see below. 

            Lua lua = new Lua();
            lua.LoadCLRPackage();
            lua.DoString(@" import('System') import('System.Drawing') import('System.Drawing.dll')
                            local c = Color.FromArgb(255,0,0,0);
                            local b = Bitmap(100, 100);
                            b.SetPixel(0, 0, c);
                        ");

[string "chunk"]:2: attempt to index global 'Color' (a nil value)

**Comment by adambiser** [comment]
I'm new to this as well, and have been dealing with getting something similar to work.

This work should work:
`import('System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
import('System.Drawing')
local c = Color.FromArgb(255,0,0,0);
local b = Bitmap(100, 100);
b:SetPixel(0, 0, c);`
The full assembly name needs to be used as per issue #50 .
A second import is used to load the namespace (my guess).
Also, be sure to use a colon : when calling regular/non-static methods (SetPixel).
The period is for static methods.

**Comment by Wiering** [comment]
Thanks, that works!
