### ISSUE TITLE
Unable to convert to int

### ISSUE THREAD

**Issue by abhijitnandy2011** [NLua/NLua#228]
So why does explicit type cast to int always fail in Unity 5.2?

I have to always explicitly type cast to double even if I have assigned an integer in Lua.

Of I have to do it as:
int id = (int)(double)env["id"];

**Comment by viniciusjarina** [comment]
How it fails? Do you have the stack trace ?

**Comment by Artum** [comment]
You can reproduce it by following code:
```
using System;
using NLua;

namespace Sample
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var l = new Lua())
            {
                l.DoString("function foo() return 1 end");

                var foo = l["foo"] as LuaFunction;
                var arr = foo.Call();

                Console.WriteLine($"Type of return value is: {arr[0].GetType()}");
            }
        }
    }
}
```
The console output is:
`Type of return value is: System.Double`

**Comment by viniciusjarina** [comment]
Yep. I think lua included integer types only on 5.3, before 5.3 every number was a double.

**Comment by viniciusjarina** [comment]
Added Lua 5.3 integer support 
Added `lua.GetInteger` and `lua.GetLong`

**Comment by viniciusjarina** [comment]
Fixed: https://github.com/NLua/NLua/releases/tag/v1.4.11
