### ISSUE TITLE
How to use iuplua in NLua?

### ISSUE THREAD

**Issue by Amaurijr** [NLua/NLua#233]
I have one integration between C# and Lua when C# call Lua script but when I run the application returns the error "module not found";

I tried set fullpath in one library iuplua53 but don't recognized.

my code
`require "iuplua"
require "iupluaim"
require "imlua"

img = iup.image {
		width = 1,
		height = 1,
		pixels = {1},
		colors = {"255 255 255"}
	}
	iup.SaveImage(img, "teste.png", "PNG");`

if I trade require by loadfile the error change for attempt to index nil value(iup);
dofile return same error that require

**Comment by AndyGFX** [comment]
I had same problem. For this solution I wrote my own lua extension for loading external lua file using standart C# IO methods and now I have full control for loading *.lua

**Comment by Amaurijr** [comment]
I understand, can you to teach me?

**Comment by AndyGFX** [comment]
I have implemented NLua in Unity. When is it ok for you here is sample of my code, but implementation is same in all other implementation.

```
using System.IO;

...
 public static string GetRoot()
        {
            return Path.GetDirectoryName(Application.dataPath);
        }
...

public static class uRetroLuaLibrary
    {
        public static void Require(string name)
        {
            string path = uRetroSystem.GetRoot() + "/uRetroEngine_Libs/" + name;

            if (File.Exists(path))
            {
                string code = File.ReadAllText(path);
                uRetroLua.script.DoString(code);
            }
            else
            {
                uRetroConsole.Show();
                uRetroConsole.Print("Library:Require ERROR: Missing file (" + path + ")");
            }
        }
    }
```
define new lua command:

`script["Library"] = new uRetroLuaClasses_Library();`

In lua code call:

`Library:Require(<lua fielname>)`

Include - command has set folder where is main lua code.
Require - command has set special folder where are all externa lua codes

But this is on you how to want work with files.

More about implementation you can find in my hobby project [uRetroEngine](https://github.com/AndyGFX/uRetroEngine)

I tried using MoonShapr too, but is slower like NLua.

Best Regards,
AndyGFX

**Comment by Amaurijr** [comment]
Hello AndyGFX, sorry for the delay in answer. I was able to solve the problem. I just compiled my .lua file using the .exe file luac52.

Thanks for help!

**Comment by viniciusjarina** [comment]
Why was reopened ?
