### ISSUE TITLE
.Net Core/Standard 2.0 and Lua 5.3.5

### ISSUE THREAD

**Issue by jmurdick** [NLua/NLua#235]
Any plans to port the project to .Net Core/Standard 2.0?  What about bringing it up to date with Lua 5.3.4?

**Comment by tluyben** [comment]
I have a build for Lua 5.3.4 and iOS 11.  I will make a pull request when I have some time to clean up.

**Comment by Happin3ss** [comment]
@tluyben : I'm curious about it :) . Pls do it !

**Comment by Artum** [comment]
I've some porting lua to 5.3.4 here:
https://github.com/artum/lua/tree/lua-5.3.4

I've also updated the Windows build script to be able to build both the "static runtime" and the "dynamic runtime".

To build in Windows just run 'Makefile.All.bat', the default build engine is "Visual Studio 15 2017" but you can pass custom build engine to the 'Makefile.All.bat' as a first parameter.
The output folder will contain 4 directories for x32/x64 and static/dynamic combinations.

Have fun.
