### ISSUE TITLE
NLua and REPL

### ISSUE THREAD

**Issue by xionglingfeng** [NLua/NLua#238]
I am trying to use NLua as REPL in a C# project. The basic idea of the code is to read a line in console, then pass the string to `lua.DoString(s)`.  However, I cannot type block statements, e.g. `if`, because the interpreter would take `if x == y` as a complete statement and try to evaluate it, which cause an exception.

Any suggestions?

**Comment by viniciusjarina** [comment]
I would take a look on lua.c (from original Lua) and try to mimic that on C#.
