### ISSUE TITLE
Cannot access .Net types

### ISSUE THREAD

**Issue by xionglingfeng** [NLua/NLua#239]
The following code try to call a 'System.Console.WriteLine()' in Lua

    this.engine = new Lua();
    this.engine.LoadCLRPackage();
    this.engine.DoString(@"import ('System')
    System.Console.WriteLine('aaa')");

However, it failed with

    [string "chunk"]:2: attempt to index global 'System' (a nil value)

Am I doing something wrong?

**Comment by SZ-MSFT** [comment]
Try this instead:

    var state = new Lua();
    state.LoadCLRPackage();
    state.DoString(@"
        import ('System')
        Console.WriteLine('hi from lua!')
    ");

Though I'm not certain, I think the problem is that you wrote System.Console.WriteLine instead of Console.WriteLine.
