### ISSUE TITLE
Dots in table indices

### ISSUE THREAD

**Issue by SinusPi** [NLua/NLua#240]
LuaTable t = Lua.DoString("return {}");
    t["autoexec.bat"]=1;
The above code will fail with "attempt to index a nil value", because NLua thinks I want to navigate into an "autoexec" table and set a "bat" key there, while all I want is a plain key with the name "autoexec.bat" set. I have since found that all dots in table keys need to be escaped with backslashes, but this is quite unexpected and unwieldy. Can this perhaps be made more user-friendly?

**Comment by viniciusjarina** [comment]
You can escape the dots with `\`

**Comment by SinusPi** [comment]
I know I can, but I shouldn't have to. It's a novelty feature that breaks the basic functionality of table key assignment. Now I have to run EVERY table key I assign through a backslashing function. This should be an optional feature, not a modification of the simple assignment.

**Comment by viniciusjarina** [comment]
AFAIK LuaInterface always worked this way 😕 I didn't design this way, but if I changed the default then I would break for other people expecting this behavior, sorry.
