### ISSUE TITLE
Limiting the Execution of Lua

### ISSUE THREAD

**Issue by Baaleos** [NLua/NLua#242]
Is it possible to limit the Execution of LUA opcodes etc?
My use case is for a game, where users can define their own event handlers and the such via LUA.
The risk is that we could get one or two bad people who want to try and bring the system down via writing an infinite loop or the like in Lua.

Is it possible to execute the Lua code async or something with a timeout?
Or even define the max amount of opcodes is allowed by Lua functions?

Eg: 
To protect against While(true) loops that never end - You can use a timeout.
To protect against excessively long scripts - you could measure the OPCode count of the method, and refuse to execute it if it goes over a certain limit?

**Comment by AndySingularity** [comment]
@Baaleos there is [debug.sethook](https://www.lua.org/pil/23.2.html) for such cases. You can execute specified code each N lua instructions with it. And you can use C# features to control script execution time.

**Comment by viniciusjarina** [comment]
Or you could use corotines. Either way is not a library issue.

**Comment by Neo-vortex** [comment]
use this fork by me :
https://github.com/Neo-vortex/NLua
