### ISSUE TITLE
Not a thread safe state allocation

### ISSUE THREAD

**Issue by Artum** [NLua/NLua#247]
I'm trying to run NLua in multi-threaded environment. 
I'm creating a new Lua state for each thread. 
The code below fails on multiple exceptions, it seems that Nlua.Lua.Init() is not a thread safe implementation.

    namespace Lua.Tests
    {
        using System;
        using System.Collections.Concurrent;
        using System.Collections.Generic;
        using System.Diagnostics;
        using System.Linq;
        using System.Threading.Tasks;
    
        class Program
        {
            static void Main(string[] args)
            {        
                Test_MultiThread1();
                Test_MultiThread2();
            }
            
            static void Test_MultiThread1()
            {
                var tasks = new List<Task>();
                for (int i = 0; i < 100; i++)
                {
                    tasks.Add(new Task(
                        () =>
                        {
                            var x = new NLua.Lua();
                        }));
                }
    
                foreach (var task in tasks)
                {
                    task.Start();
                }
    
                foreach (var task in tasks)
                {
                    task.Wait();
                }        
            }
            static void Test_MultiThread2()
            {
                var tasks = new List<Task>();
                for (int i = 0; i < 100; i++)
                {
                    tasks.Add(new Task(
                        () =>
                        {
                            for (int j = 0; j < 100; j++)
                            {
                                var x = new NLua.Lua();
                            }
                        }));
                }
    
                foreach (var task in tasks)
                {
                    task.Start();
                }
    
                foreach (var task in tasks)
                {
                    task.Wait();
                }        
            }
        }
    }

Some of the exceptions:

**IndexOutOfRangeException**
```
    at System.Collections.Generic.Dictionary'2.Insert(TKey key, TValue value, Boolean add)
    at NLua.Lua.Init()
    at NLua.Lua..ctor()
    at Lua.Tests.Program.<>c__DisplayClass0_0.<Main>b__0()
    at System.Threading.Tasks.Task.InnerInvoke()
    at System.Threading.Tasks.Task.Execute()
    
    System.IndexOutOfRangeException "Index was outside the bounds of the array."
        Data    {System.Collections.ListDictionaryInternal}   System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
            HResult     2146233080     int
            HelpLink    null            string
        InnerException    null    System.Exception
            Message     "Index was outside the bounds of the array."    string
            Source      "mscorlib"  string
```

**NullReferenceException**
```
   at NLua.ObjectTranslator.LoadAssembly(LuaState luaState)
   at KeraLua.NativeMethods.LuaNetPCall(IntPtr luaState, Int32 nArgs, Int32 nResults, Int32 errfunc)
   at NLua.LuaLib.LuaLDoString(LuaState luaState, String chunk)
   at NLua.Lua.Init()
   at NLua.Lua..ctor()
   at Lua.Tests.Program.<>c__DisplayClass0_0.<Main>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

 $exception    {"Object reference not set to an instance of an object."}   System.NullReferenceException
     Data  {System.Collections.ListDictionaryInternal} System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
        HResult -2147467261 int
        HelpLink    null    string
     InnerException    null    System.Exception
        Message "Object reference not set to an instance of an object." string
        Source  "NLua"  string
```
**ArgumentException**
```
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.Dictionary`2.Resize(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NLua.Lua.Init()
   at NLua.Lua..ctor()
   at Lua.Tests.Program.<>c__DisplayClass0_0.<Main>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

 $exception    {"Destination array was not long enough. Check destIndex and length, and the array's lower bounds."}    System.ArgumentException
     Data  {System.Collections.ListDictionaryInternal} System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
        HResult -2147024809 int
        HelpLink    null    string
     InnerException    null    System.Exception
        Message "Destination array was not long enough. Check destIndex and length, and the array's lower bounds."  string
        ParamName   ""  string
        Source  "mscorlib"  string
```

**Comment by trishp213** [comment]
I'm also having this issue.
