### ISSUE TITLE
How to use json methods inside lua script and execute lua script with c#?

### ISSUE THREAD

**Issue by AkibSiddiqui** [NLua/NLua#253]
I am trying to encode and decode json using lua using c#.I am using NLUA for executing lua script.

I am using [https://github.com/rxi/json.lua](url) file for json manupulation(encode and decode method) but i am not getting how to make it work with nlua in c#.
code :

```
static void Main(string[] args)
            {
                Lua state = new Lua();
                var jsonConcate = @"[{ ""firstName"":""John"" , ""lastName"":""Doe"", ""email"":""NHP@123.COM"" },{ ""firstName"":""Anna"", ""lastName"":""Smith"", ""email"":""ASD@123.COM"" },{ ""firstName"":""Peter"" , ""lastName"":""Jones"", ""email"":""ZXC@123.COM""}]";
                state.DoString(@"
                function ScriptFunc (input)
                    local json = require('json')
                    local JSON_string = input
                    return JSON_string end"
                 );
                var scriptFunc = state["ScriptFunc"] as LuaFunction;
                var res = scriptFunc.Call(jsonConcate);//Error here
            }
```

This line `var res = scriptFunc.Call(jsonConcate)` is throwing error :
![luaerror](https://user-images.githubusercontent.com/19324983/35274875-c7934ef4-0063-11e8-83fa-b30728e4ace8.png)

When i remove this line `local json = require('json')` then it is working fine.

I have install lua using this installer also :https://github.com/rjpcomputing/luaforwindows

Project : https://www.dropbox.com/s/hbf04d8kqpenzm0/LuaTest.zip?dl=0

Can you please help me with this?

**Comment by Artum** [comment]
I think that StackOverflow is more suitable place for this kind of questions.

Read the 'json.lua' file to string and call DoString before your script (and yes, remove the require('json') from your script).
