### ISSUE TITLE
LuaBase.GetHashCode() implementation is incorrect

### ISSUE THREAD

**Issue by krajzeg** [NLua/NLua#260]
I found this issue when trying to use `LuaTable` objects as keys in a Dictionary and encountering false misses.

The `GetHashCode()` implementation from `LuaBase` just returns the `_Reference`, which can result in two objects that are considered equal but have different hashcodes. This makes all LuaBase-derived objects misbehave when used as keys.

```C#
public override bool Equals (object o)
		{
			if (o is LuaBase) {
				var l = (LuaBase)o;
				return _Interpreter.CompareRef (l._Reference, _Reference);
			} else
				return false;
		}

		public override int GetHashCode ()
		{
			return _Reference;
		}
```

I'm not sure how the implementation can be improved (I'd do a pull request if I had an idea). If it's not possible to implement an efficient GetHashCode() for LuaBase, a better choice might be returning a constant value so that the implementation is at least correct as far as invariants go (albeit very slow when used as a key).

**Comment by viniciusjarina** [comment]
Where `LuaBase` is used as key ?
