### ISSUE TITLE
Nlua with KeraLua 5.3

### ISSUE THREAD

**Issue by RussellHaley** [NLua/NLua#264]
Hi, 

Thanks for updating KeraLua to 5.3. I started playing with it last night and everything I tried so far worked very well. I tried removing the KeraLua/KopiLua references in NLua and using the updated KeraLua. I perhaps have done something incorrectly, but it seems the API for KeraLua has changed and the LuaState and LuaCore Classes have been merged? 

As I went through NLua it seems like the LuaLib library has become redundant? There was also a few Libraries/Classes  I couldn't find like LuaNativeFunction and LuaHook.

Let me know if you have any thoughts or plans? It seems like adapting the library to KeraLua would be time consuming but not terribly difficult. I wouldn't mind taking a hack at it (I started last night), but I'm a notoriously distracted person. :-/

Is KopiLua going to be maintained? There is also NeoLua based on the Dynamic Runtime which I've used with great success in a one off application I wrote for a client. NeoLua already has a nice clean interface so adapting it to NLua might not be worthwhile. Is there a particular use case for KopiLua other than a re-implementation in C# (pardon my ignorance)?

**Comment by viniciusjarina** [comment]
I will do a full rework on NLua soon. I want to finish update KeraLua CI and auto package/publish as NuGet package.Multi-targeting net45/ios/watch/tvos/android/netcore 

Yes LuaLib will be droped and KopiLua as well. There is no point to keep then. NLua will be based on KeraLua which will point to latest Lua from lua.org. 

I've also droped the luanet_ patches on native Lua library, so KeraLua can be used with any binary people want to use. So If tomorrow Lua.org release a Lua 5.3.6 you would be able to do a drop-in replacement (if they don't break the ABI).

**Comment by viniciusjarina** [comment]
Thank you. I will la huge reshuffle/cleanup after that any patch will be welcome. I will also move to .NET coding convention style instead the Mono.

The Main reason of KopiLua was due some enviroment which lack P/Invoke like Silverlight and Windows Phone. But this is old. I have been using SkiaSharp as a reference to target KeraLua. So basically all platforms which can P/Invoke a native method.

**Comment by RussellHaley** [comment]
Awesome news. Let me know if I can help. I will be updating [WinLua ](https://github.com/WinLua )in the next few weeks and I'm very excited to be able to include modern .Net bindings.
