### ISSUE TITLE
Memory limit

### ISSUE THREAD

**Issue by nicodrive** [NLua/NLua#266]
Is it possible to set a limit on memory usage?

**Comment by viniciusjarina** [comment]
If you have such restriction I would use only KeraLua which is a think layer to binding C# you can create your Lua state and pass a memory allocator, which you could use to restrict the amount of memory in use https://github.com/NLua/KeraLua/blob/master/src/Lua.cs#L61

**Comment by flynicodrive** [comment]
` // allocator
    private static unsafe IntPtr Allocator(IntPtr ud, IntPtr ptr, UIntPtr osize, UIntPtr nsize)
    {
        if (osize == nsize)
            return ptr;


        int* inUse = (int*) ud;
        var newSize = (uint) nsize;
        var originalSize = (uint) osize;

        if (ptr == IntPtr.Zero)
        {
            if (*inUse - (int) newSize < 0)
            {
                return IntPtr.Zero;
            }

            var intPtr = Marshal.AllocHGlobal((int) newSize);
            *inUse -= (int) newSize;
            return intPtr;
        }


        if (nsize == UIntPtr.Zero)
        {
            Marshal.FreeHGlobal(ptr);

            *inUse += (int) originalSize;
            return IntPtr.Zero;
        }

        if (*inUse - ((int) nsize - (int) osize) < 0)
        {
            return IntPtr.Zero;
        }

        ptr = Marshal.ReAllocHGlobal(ptr, (IntPtr) newSize);

        if (ptr != IntPtr.Zero)
        {
            *inUse -= ((int) nsize - (int) osize);
        }

        return ptr;
    }`
`//create max memory variable
var memSize = Marshal.AllocHGlobal(4);
        unsafe
        {
            *(int*) memSize = maxMemory;
        }`

`///constructor for nlua 
 public Lua(LuaAlloc alloc, IntPtr ptr)
        {
            _luaState = new LuaState(alloc, ptr);
            _luaState.OpenLibs();
            Init();
            // We need to keep this in a managed reference so the delegate doesn't get garbage collected
            _luaState.AtPanic(PanicCallback);
        }
`

this work fine with nlua

**Comment by Neo-vortex** [comment]
> allocator
> 
> ```
>     private static unsafe IntPtr Allocator(IntPtr ud, IntPtr ptr, UIntPtr osize, UIntPtr nsize)
>     {
>         if (osize == nsize)
>             return ptr;
> 
> 
>         int* inUse = (int*) ud;
>         var newSize = (uint) nsize;
>         var originalSize = (uint) osize;
> 
>         if (ptr == IntPtr.Zero)
>         {
>             if (*inUse - (int) newSize < 0)
>             {
>                 return IntPtr.Zero;
>             }
> 
>             var intPtr = Marshal.AllocHGlobal((int) newSize);
>             *inUse -= (int) newSize;
>             return intPtr;
>         }
> 
> 
>         if (nsize == UIntPtr.Zero)
>         {
>             Marshal.FreeHGlobal(ptr);
> 
>             *inUse += (int) originalSize;
>             return IntPtr.Zero;
>         }
> 
>         if (*inUse - ((int) nsize - (int) osize) < 0)
>         {
>             return IntPtr.Zero;
>         }
> 
>         ptr = Marshal.ReAllocHGlobal(ptr, (IntPtr) newSize);
> 
>         if (ptr != IntPtr.Zero)
>         {
>             *inUse -= ((int) nsize - (int) osize);
>         }
> 
>         return ptr;
>     }
> ```
> 
> create max memory variable
> 
> ```
>        var memSize = Marshal.AllocHGlobal(4);
>         unsafe
>         {
>             *(int*) memSize = maxMemory;
>         }
> ```
> 
> constructor for nlua
> 
> ```
>         public Lua(LuaAlloc alloc, IntPtr ptr)
>         {
>             _luaState = new LuaState(alloc, ptr);
>             _luaState.OpenLibs();
>             Init();
>             // We need to keep this in a managed reference so the delegate doesn't get garbage collected
>             _luaState.AtPanic(PanicCallback);
>         }
> ```
> 
> this work fine with nlua

nlua does not have this constructor

**Comment by Neo-vortex** [comment]
use this fork by me :
https://github.com/Neo-vortex/NLua
