### ISSUE TITLE
NuGet package issue?

### ISSUE THREAD

**Issue by ixwt** [NLua/NLua#267]
I was attempting to use the NLua Nuget package, and I am getting the error

`Failed to add reference to 'lua53'.
  Please make sure that the file is accessible, and that it is a valid assembly or COM component.`

If I install the KeraLua dependency, I can see that lua53.dll is downloaded to {PROJECT}\packages\KeraLua.0.1.14\runtimes\win-x64\native.

I am able to successfully download the repo, build it, and import the references (and have to copy the lua53.dll file to the exe path).

Here is the full error output when just installing the NLua Nuget repo: 

> Attempting to gather dependency information for package 'NLua.1.4.1' with respect to project 'EmptyConsole', targeting '.NETFramework,Version=v4.6.1'
> Gathering dependency information took 3.75 ms
> Attempting to resolve dependencies for package 'NLua.1.4.1' with DependencyBehavior 'Lowest'
> Resolving dependency information took 0 ms
> Resolving actions to install package 'NLua.1.4.1'
> Resolved actions to install package 'NLua.1.4.1'
> Retrieving package 'KeraLua 0.1.14' from 'nuget.org'.
> Retrieving package 'NLua 1.4.1' from 'nuget.org'.
> Adding package 'KeraLua.0.1.14' to folder '{PROJECT}\packages'
> Added package 'KeraLua.0.1.14' to folder '{PROJECT}\packages'
> Added package 'KeraLua.0.1.14' to 'packages.config'
> Successfully** installed 'KeraLua 0.1.14' to EmptyConsole
> Adding package 'NLua.1.4.1' to folder '{PROJECT}\packages'
> Added package 'NLua.1.4.1' to folder '{PROJECT}\packages'
> Install failed. Rolling back...
> Package 'NLua.1.4.1 : KeraLua [0.1.14, )' does not exist in project 'EmptyConsole'
> Removed package 'KeraLua.0.1.14' from 'packages.config'
> Removing package 'NLua.1.4.1 : KeraLua [0.1.14, )' from folder '{PROJECT}\packages'
> Removed package 'NLua.1.4.1 : KeraLua [0.1.14, )' from folder '{PROJECT}\packages'
> Removing package 'KeraLua.0.1.14' from folder '{PROJECT}\packages'
> Removed package 'KeraLua.0.1.14' from folder '{PROJECT}\packages'
> Executing nuget actions took 1.96 sec
> Failed to add reference to 'lua53'.
>   Please make sure that the file is accessible, and that it is a valid assembly or COM component.
> Time Elapsed: 00:00:02.0156540
> ========== Finished ==========

**Comment by adambiser** [comment]
I also get a similar error message (less verbose) with VS Community 2015.

**Comment by viniciusjarina** [comment]
Steps to repro?

**Comment by ixwt** [comment]
Using Visual Studio 2017 Professional, Windows 10:

1. Create New Console Project
2. Make sure Project is compling x64, not Any CPU
2. In Solution Explorer, Right click references, choose "Manage NuGet Packages"
3. Search for NLua
4. Download & Install NLua (click Ok on prompt showing what it's going to download).
5. Get error message about not being able to find lua53.dll.

**Comment by viniciusjarina** [comment]
Oh it seems related to VS 2015. 😣

**Comment by ixwt** [comment]
I'm using VS 2017, not 2015.

**Comment by viniciusjarina** [comment]
Taking a looking. Thank you for the report.

**Comment by adambiser** [comment]
Could it be because it's trying to add lua53.dll as a reference to the project and it shouldn't be since that's not a .NET assembly?

**Comment by viniciusjarina** [comment]
It could, 😕 
But this does't make any sense. Since they are not under `lib` folder they should just copied as-is https://github.com/NLua/KeraLua/blob/master/KeraLua.nuspec#L36 this is the .NET Core convention for native references.

**Comment by ixwt** [comment]
When I built my test project that only had KeraLua installed (no NLua package), I think I noticed the lua53.dll was in the exe directory. I'm not at my machine to test right now though. So it was copied. It seems that NLua has issues with not finding the reference?

**Comment by viniciusjarina** [comment]
NLua doesn't need to reference the lua53 library, NLua is pure C#. the CLR/Mono only need to find lua53 at the runtime. This is nuget trying to being "smart".

**Comment by adambiser** [comment]
Could this line be causing lua53.dll to go into the NLua's lib/net45 folder?
https://github.com/NLua/NLua/blob/master/NLua.nuspec#L22

**Comment by viniciusjarina** [comment]
Couldn't figure why (yet) but maybe is a nuget bug? Using `PackageRefernce` seems to work.

**Comment by adambiser** [comment]
Is https://github.com/NLua/NLua/blob/master/NLua.nuspec#L22 not the culprit?
When I compile, I see lua53.dll in lib\Release\net45 causing it to go into lib\net45, right?

https://github.com/NLua/KeraLua/blob/master/KeraLua.nuspec#L36
has the lua53.dll files going into the runtimes folder.

**Comment by viniciusjarina** [comment]
Phew.. Fixed https://github.com/NLua/NLua/releases/tag/v1.4.4
