### ISSUE TITLE
NuGet old versions are removed

### ISSUE THREAD

**Issue by jessetabak** [NLua/NLua#268]
As of yesterday all older versions (<1.4.0) are removed.
My project depends on these older versions.

I tried using the 1.4.x version but my lua scripts use a lot of functions that are deprecated since lua 5.3, and I would prefer not to update all these scripts because they are maintained by our customer.

Would it be possible to make the older versions available again on NuGet?

To clarify, we use the Nlua.iOS and Nlua.Android packages

**Comment by viniciusjarina** [comment]
Yes I can, the ABI for the new one should be the same. and all the tests are passing. Also IIRC NLua_iOS is bundling a 32bit static library and will be soon deprecated by Apple.

I didn't remove the NuGet, you can't delete a package, only unlist so avoid people to add to new projects if you are using 1.3.x you should be able to keep using it.

**Comment by jessetabak** [comment]
Ok great, thanks!
