### ISSUE TITLE
NLua/KeraLua support .Net Framework 4.0

### ISSUE THREAD

**Issue by lishuangquan1987** [NLua/NLua#281]
Is any plan that NLua/KeraLua is support for .net framework 4.0?
My projects are most build in .net framework 4.0,so I  appreciate that this  can support for .net framework4.0 and Nuget package is available for .net 4.0 projects.Thank you!

**Comment by viniciusjarina** [comment]
Not really 😕 , I really hard to maintain all the targets + .net40 35
My suggestion is, fork it and add as submodule and build from the source.

Any reason you can't bump to .net 45 ?

**Comment by viniciusjarina** [comment]
.NET 4.5 is well supported on Vista and Windows 7. So unless you are running on XP you will be fine.
