### ISSUE TITLE
Support bit?

### ISSUE THREAD

**Issue by jaspergould** [NLua/NLua#283]
I think about 
`local bor = bit.bor`
bitwise operation

**Comment by viniciusjarina** [comment]
NLua runs Lua 5.3 the bit support is built in https://www.lua.org/manual/5.3/manual.html#3.4.2

**Comment by jaspergould** [comment]
it is not a solution..

**Comment by viniciusjarina** [comment]
What is your issue?

**Comment by jaspergould** [comment]
> What is your issue?

bit.bor doesn't support correctly. open editor and try.

**Comment by viniciusjarina** [comment]
```csharp
var x = new Lua();
var y = (int)(double)x.DoString("y = 0xBA | 0xC0; return y")[0];
System.Diagnostics.Debug.Assert(y == (0xBA | 0xC0));
```
