### ISSUE TITLE
How to create a timer?

### ISSUE THREAD

**Issue by chenxuuu** [NLua/NLua#287]
such as a function called `timerStart` or `timerLoopStart`:

```lua

--start this function after 1000ms
timerStart(function ()
    print("timer 1 run")
end, 1000)

--start this function after 1000ms, and pass a number and a string
timerStart(function (n,s)
    print("timer 2 run",n,s)
end, 1000, 12345, "something")

--start this function every 1000ms
timerLoopStart(function ()
    print("timer loop run")
end, 1000)
```

can I do this?

**Comment by viniciusjarina** [comment]
Hi @chenxuuu 
You can use the Timer from .NET 
https://docs.microsoft.com/en-us/dotnet/api/system.threading.timer?view=netframework-4.7.2

**Comment by chenxuuu** [comment]
thanks for reply

I mean, can I create a interrupt timer in my lua script

like this:

```
start --> create a timer [A] --> run to end --> two seconds later --[timer A interrupt]--> run the function in timer A --> other timers trigger...
```

**Comment by viniciusjarina** [comment]
I think would be easier to create the timers on C# side, and just trigger a `DoFile` or `DoString` from timer.
