### ISSUE TITLE
Error with NLua after upgrading to 1.4.x

### ISSUE THREAD

**Issue by Valleriani** [NLua/NLua#288]
```
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>EOServer.exe</AppDomain><Exception><ExceptionType>System.ArgumentException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Source array was not long enough. Check srcIndex and length, and the array's lower bounds.</Message><StackTrace>   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at NLua.Lua.DisposeInternal(Int32 reference, Boolean finalized)
   at NLua.LuaBase.DisposeLuaReference(Boolean finalized)
   at NLua.LuaBase.Dispose(Boolean disposeManagedResources)
   at NLua.LuaBase.Finalize()</StackTrace><ExceptionString>System.ArgumentException: Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at NLua.Lua.DisposeInternal(Int32 reference, Boolean finalized)
   at NLua.LuaBase.DisposeLuaReference(Boolean finalized)
   at NLua.LuaBase.Dispose(Boolean disposeManagedResources)
   at NLua.LuaBase.Finalize()</ExceptionString></Exception></TraceRecord>
```

I upgraded from 1.3.2 to 1.4.x and I am getting this error now. I do not know what the cause is at the moment.  I do have a fairly long 'RegisterFunction' for the states that could cause it, Not sure yet though.

--

        internal void AddFinalizedReference(int reference)
        {
            finalizedReferences.Enqueue(reference);
        }

Seems to be here it's having problems with, I think.

--

It seems to randomly error when I'm doing alot of state.RegisterFunction() calls. Different location every time. Not sure why that is, just relaying it though.

**Comment by Valleriani** [comment]
```
        internal void AddFinalizedReference(int reference)
        {
            finalizedReferences.Enqueue(reference);
        }

```

Seems to be here it's having problems with, I think.

**Comment by Valleriani** [comment]
It seems to randomly error when I'm doing alot of state.RegisterFunction() calls. Different location every time. Not sure why that is, just relaying it though.

**Comment by Valleriani** [comment]
I also see another issue from upgrading. Originally I do:

                        luaFunc = state.GetFunction("init")
                        If luaFunc IsNot Nothing Then
                            luaInit = luaFunc
                            luaInitEnabled = True
                        End If

And generally it works fine, but now it's always returning not nothing, even if the init function doesn't exist.

**Comment by viniciusjarina** [comment]
Hi @Valleriani 
Thank you for the bug report. The `AddFinalizedReference` was added to avoid memory leaks, if the LuaBase object is being Finalized and wasn't disposed correctly (using Dispose) the main Lua will try to add to a queue to be finalized later.

Can you create a small program or a small unit test which repro the issue?
Thanks

**Comment by viniciusjarina** [comment]
Also, IMHO I think if you are using only low-lever registration of method to be called, you should consider using only `KeraLua`. `NLua` is more suitable for scenarios where the types/methods are used dynamically (Which is done by reflection by NLua).

**Comment by Valleriani** [comment]
I will attempt to write a small program for you when I can (I had to go to the hospital cause of a sick puppy and dealing with him at the moment). I will try ASAP though. Thank you for the reply!

**Comment by Valleriani** [comment]
[ConsoleApp1.zip](https://github.com/NLua/NLua/files/3007707/ConsoleApp1.zip)

Okay this does work, try running it a few times, it will eventually happen. I tried to remove alot of the code and gunk but there is probably alot of unused vars (and obviously the lua functions aren't called/removed that etc too). There is a script called Generic.lua that should 'load' functions. It doesn't do that anymore. I might of made a mistake when doing this, but I included some temp functions in the file that should be loaded. 
Two things to note:

A. You will get the error as stated on the first one, just run it a few times to cause it. Does not always happen.
B. 
```
            luaFunc = state.GetFunction("ticktimer")
            If luaFunc IsNot Nothing Then
                luaTickTimer = luaFunc
                luaTickTimerEnabled = True
            End If
```
Even though the function isn't defined, it returns true. I see in the private variables that function is nothing though However:

```
            luaFunc = state.GetFunction("logoff")
            If luaFunc IsNot Nothing Then
                luaLogoff = luaFunc
                luaLogoffEnabled = True
            End If
```
This is defined in Generic.lua, so it SHOULD return true, however, it does not return the function and the function is claimed as nothing here too. The original 1.3.2 version works however and it's pretty heavy lua  based for everything game wise.

**Comment by Valleriani** [comment]
Let me know if you have any questions too. I assume the program should work OK though for test reasons.

**Comment by viniciusjarina** [comment]
Hi @Valleriani 
I look the program, and is quite bug, and is VB, I dont know VB very well. Would be great if you could write an unit test and make it fail, then we can try to find the fix for it.

😉

**Comment by Valleriani** [comment]
Sorry about the delay, I'll try to have one going soonish.

**Comment by viniciusjarina** [comment]
If the problem is still happening please reopen 😉
