### ISSUE TITLE
can't put clr object to script

### ISSUE THREAD

**Issue by xudongliai** [NLua/NLua#289]
when i run the demo,
state.LoadCLRPackage ();
state.DoString (@"
	 obj2 = SomeClass() -- you can suppress default values.
	 client = WebClient()
	");

the program have no problem.But when i use this to my own project,there comes a exception "attempt to call a nil value(global "SomeClass") “.Does this come somethings to you?

**Comment by viniciusjarina** [comment]
You need to call `import ('AssemblyName`, `Namespace`)`

https://github.com/NLua/NLua/blob/master/tests/src/LuaTests.cs#L1955

**Comment by xudongliai** [comment]
thanks,i did solve this.In my project,i forgot import the AssemblyName.
