### ISSUE TITLE
question about registering lua hooks and calling them

### ISSUE THREAD

**Issue by Shadowblitz16** [NLua/NLua#292]
I just have a quick question.
how do I register and then call a lua function from C# even if it doesn't exists?

**Comment by viniciusjarina** [comment]
I wish the documentation for NLua was more complete.

The best way to figure is seeing our tests.

https://github.com/NLua/NLua/blob/ad9dc28094d1e903b6effc7324bd1fd000323ab5/tests/src/LuaTests.cs#L1829

**Comment by Shadowblitz16** [comment]
wait what how does this tell it what function to call?
and what does KeraLua.LuaHookMask.Line mean?

**Comment by viniciusjarina** [comment]
NLua hooks relies on KeraLua, which relies on native Lua hooks. Take a look on Lua documentation https://www.lua.org/manual/5.3/manual.html#lua_gethookmask

**Comment by Shadowblitz16** [comment]
I still don't understand can you provide some code?
I am new to this and I can't find a video tutorial on how to use this library.

**Comment by viniciusjarina** [comment]
What are you trying to do?

**Comment by Shadowblitz16** [comment]
right now I am trying to register a print function for users to call in lua. 

my current script is

```
function init()
	print("HI")
end

function loop()
	print("...")
end
```

it didn't print anything so I assumed I needed to implement the print function

**Comment by viniciusjarina** [comment]
Oh... I am sorry. I thought you were trying to use the Hook/Debug from Lua 😅

You can just assign a Delegate to the `print` value.

https://github.com/NLua/NLuaBox/blob/master/NLuaBox/ScriptRunner.cs#L16

**Comment by Shadowblitz16** [comment]
is there a way to do it without passing a delegate?
I would like to just pass the method itself.
```
State.RegisterFunction("print", Print()); //error here
State.DoString("print("HelloWorld")");
```

**Comment by viniciusjarina** [comment]
You can also use the `MethodInfo`, but I think you should learn a bit more about delegates. 😉

**Comment by Shadowblitz16** [comment]
so there is no method to register a function and link it to a C# one?
its called `State.RegisterFunction` not `State.RegisterDelegate`

**Comment by viniciusjarina** [comment]
`state["print"] = Print; `

**Comment by Shadowblitz16** [comment]
oh ok thankyou
