### ISSUE TITLE
Issue with x64-x86 platform

### ISSUE THREAD

**Issue by lichutinm** [NLua/NLua#293]
Hello!

I have seen that you had fixed a bug with building and development on x64/x86 platforms.
But now I'm experiencing some troubles with the same situation. I'm working at x64 machine and I'm using NLua at AnyCpu project and everything is OK. 

But if I change Build Target to x86, Project will crash at "new Lua()" with System.BadImageFormatException. I have tried .net core and .net 4.7.1 with no luck.

How can I fix that issue?

**Comment by lichutinm** [comment]
It looks like build puts the wrong "lua53.dll" to output directory.
I have found a temp solution for this issue. 
At Post-build event command line add

`copy /Y "$(OutDir)\x86\lua53.dll" "$(OutDir)"`

**Comment by viniciusjarina** [comment]
Try to use the flag `Prefer32bit` in your final executable.
