### ISSUE TITLE
dofile/require error when path include Chinese

### ISSUE THREAD

**Issue by chenxuuu** [NLua/NLua#294]
when I use `require`,`dofile`,`io.open`,`os.rename`.....and some other functions, if my path include Chinese, it will become mess code and show errors
now I use pure English path to avoid this error

path such as `D:\OneDrive\同步文件夹\git项目`

Reference article : [https://blog.codingnow.com/2017/10/lua_windows_utf8.html](https://blog.codingnow.com/2017/10/lua_windows_utf8.html)

**Comment by viniciusjarina** [comment]
This seems to be an issue with the Lua library, not NLua 😕

**Comment by chenxuuu** [comment]
I find this: [http://lua-users.org/lists/lua-l/2012-08/msg00165.html](http://lua-users.org/lists/lua-l/2012-08/msg00165.html)

I'll try😁

**Comment by chenxuuu** [comment]
I solved it
convert my file path from utf8 to ascii, it works

before
```lua
local f = [[D:\测试\新建文本文档.txt]]
local file = io.open(file)
print(file)--nil
```

after
```lua
local f = string.char(0x44,0x3A,0x5C,0xB2,0xE2,0xCA,0xD4,0x5C,0xD0,0xC2,0xBD,0xA8,0xCE,0xC4,0xB1,0xBE,0xCE,0xC4,0xB5,0xB5,0x2E,0x74,0x78,0x74)
local file = io.open(file)
print(file)--file (0068C108)
```
