### ISSUE TITLE
Compatibility with Mono

### ISSUE THREAD

**Issue by Lautenschlager-id** [NLua/NLua#303]
Is there any possibility that it could be compatible with Mono?

**Comment by viniciusjarina** [comment]
What you mean? It's compatible with Mono

**Comment by Lautenschlager-id** [comment]
:thinking: I tried using it with mono but it simply didn't work
I'll try stressing it with more tests and reopen the issue if it persists in not working

**Comment by viniciusjarina** [comment]
What OS? What Mono version? What didn't work? 🤯

**Comment by Lautenschlager-id** [comment]
It simply throw an error saying that nlua wasn't compatible, win7 x86
I'm not home atm so I can't screenshot the msg
