### ISSUE TITLE
Error when trying to access a byte array by index.

### ISSUE THREAD

**Issue by ASgoPew** [NLua/NLua#306]
Accessing byte[] array by index now throws:
![](https://i.gyazo.com/12d800d4883d39b2c9ebb0b2b2691e40.png)
And I guess this is because there is no check for byte[] type here:
https://github.com/NLua/NLua/blob/3eb74adae6592bc548e992e328810653dd8df4b2/src/Metatables.cs#L395-L420

**Comment by viniciusjarina** [comment]
Do you mind write a little test for that? Thanks

**Comment by viniciusjarina** [comment]
Fix https://github.com/NLua/NLua/releases/tag/v1.4.21
