### ISSUE TITLE
System.NullReferenceException when call a C# method with coroutine

### ISSUE THREAD

**Issue by chenxuuu** [NLua/NLua#307]
Update:

a part of lua code (not include print function):

```lua
function test()
	print("start")
	coroutine.yield()
	print("dead")
end

y = coroutine.create(test)
coroutine.resume(y)

function run()
	coroutine.resume(y)
	y = coroutine.create(test)
	coroutine.resume(y)
end
```

a part of cs code:

```csharp
    class LuaTest
    {
        public static NLua.Lua lua;


        public static void init()
        {
            Task.Run(() =>
            {
                lua = new NLua.Lua();
                lua.State.Encoding = Encoding.UTF8;
                anything.Initial(lua);
                lua.DoFile("sys.lua");
                while (true)
                {
                    Task.Delay(500).Wait();
                    lua.GetFunction("run").Call();
                }
            });
        }
    }


    class anything
    {
        public static void Initial(NLua.Lua lua)
        {
            lua.RegisterFunction("apiPrintLog", null, typeof(anything).GetMethod("PrintLog"));
        }

        public static event EventHandler PrintLuaLog;

        public static void PrintLog(string log)
        {
            PrintLuaLog(DateTime.Now.ToString("[HH:mm:ss:ffff]") + log, EventArgs.Empty);
        }
    }
```

this will cause `System.NullReferenceException` fault.

And, if I delete `lua.RegisterFunction` method line, it will be ok.

full project here: 
[WpfApp1.zip](https://github.com/NLua/NLua/files/3323340/WpfApp1.zip)

-------

Original issue content:

I use `lua.GetFunction("tiggerCB").Call();` function in a task, got this error `System.NullReferenceException`.

codes here : [https://github.com/chenxuuu/llcom/blob/master/llcom/LuaEnv/LuaRunEnv.cs](https://github.com/chenxuuu/llcom/blob/master/llcom/LuaEnv/LuaRunEnv.cs)

all lua codes run in one task, no other task

full error information:
```
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 KeraLua.Lua.FromIntPtr(IntPtr luaState)
   在 NLua.MetaFunctions.RunFunctionDelegate(IntPtr luaState)
   在 KeraLua.NativeMethods.lua_pcallk(IntPtr luaState, Int32 nargs, Int32 nresults, Int32 errorfunc, IntPtr ctx, IntPtr k)
   在 NLua.Lua.CallFunction(Object function, Object[] args, Type[] returnTypes)
   在 NLua.LuaFunction.Call(Object[] args)
   在 llcom.LuaEnv.LuaRunEnv.runTigger() 位置 C:\Users\chenx\Desktop\llcom\llcom\LuaEnv\LuaRunEnv.cs:行号 67
```

how to solve this problem? should I add some judge codes?
thanks.

**Comment by viniciusjarina** [comment]
Can you debug and see what is the value of `translator` here https://github.com/NLua/NLua/blob/e51e35985aaa578e0ceec702f01017205d1db98f/src/Metatables.cs#L103 ?
Could be a race condition.

**Comment by chenxuuu** [comment]
I use `DoString` to instead now.....
also get this error

**Comment by chenxuuu** [comment]
> Can you debug and see what is the value of `translator` here
> 
> https://github.com/NLua/NLua/blob/e51e35985aaa578e0ceec702f01017205d1db98f/src/Metatables.cs#L103
> 
> ?
> Could be a race condition.

@viniciusjarina 
follow your way, I got an error in KeraLua
I don't know how to debug KeraLua😭
[NluaDebugPriject.zip](https://github.com/NLua/NLua/files/3320727/NluaDebugPriject.zip)

I found that, if I select any words in my window, it will have big chance to exception

```
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 KeraLua.Lua.FromIntPtr(IntPtr luaState)
   在 NLua.MetaFunctions.RunFunctionDelegate(IntPtr luaState) 位置 C:\Users\chenx\Desktop\NLua\src\Metatables.cs:行号 101
   在 KeraLua.NativeMethods.lua_pcallk(IntPtr luaState, Int32 nargs, Int32 nresults, Int32 errorfunc, IntPtr ctx, IntPtr k)
   在 KeraLua.Lua.PCall(Int32 arguments, Int32 results, Int32 errorFunctionIndex)
   在 NLua.Lua.CallFunction(Object function, Object[] args, Type[] returnTypes) 位置 C:\Users\chenx\Desktop\NLua\src\Lua.cs:行号 855
   在 NLua.Lua.CallFunction(Object function, Object[] args) 位置 C:\Users\chenx\Desktop\NLua\src\Lua.cs:行号 818
   在 NLua.LuaFunction.Call(Object[] args) 位置 C:\Users\chenx\Desktop\NLua\src\LuaFunction.cs:行号 46
   在 llcom.LuaEnv.LuaRunEnv.runTigger() 位置 C:\Users\chenx\Desktop\NLua\ltest\llcom\LuaEnv\LuaRunEnv.cs:行号 71
```

![image](https://user-images.githubusercontent.com/10357394/60017471-5fb10c00-96bb-11e9-8356-9a4c3334dc7d.png)

**Comment by chenxuuu** [comment]
is this a bug, or I use it in a wrong way?
I only want to make my script support timer operation....

**Comment by viniciusjarina** [comment]
Hi @chenxuuu I can't debug a large project. 
If you can repro in a small unit test we can have a regression test and would be easier to figure what is going on. Thanks

**Comment by chenxuuu** [comment]
sorry for that...
I created two new projects for testing

console version, works very well, no error:
[issue307test.zip](https://github.com/NLua/NLua/files/3321642/issue307test.zip)

wpf version, will report the error:
[WpfApp1.zip](https://github.com/NLua/NLua/files/3321643/WpfApp1.zip)

**Comment by chenxuuu** [comment]
I guess it's caused by `coroutine`, is it right?

I tested a simplest project:
a part of lua code (not include print function):
```lua
function test()
	print("start")
	coroutine.yield()
	print("dead")
end

y = coroutine.create(test)
coroutine.resume(y)

function run()
	coroutine.resume(y)
	y = coroutine.create(test)
	coroutine.resume(y)
end
```

a part of cs code:
```csharp
    class LuaTest
    {
        public static NLua.Lua lua;


        public static void init()
        {
            Task.Run(() =>
            {
                lua = new NLua.Lua();
                lua.State.Encoding = Encoding.UTF8;
                anything.Initial(lua);
                lua.DoFile("sys.lua");
                while (true)
                {
                    Task.Delay(500).Wait();
                    lua.GetFunction("run").Call();
                }
            });
        }
    }
```

full project here: 
[WpfApp1.zip](https://github.com/NLua/NLua/files/3323340/WpfApp1.zip)


this is very strange in wpf
I think I need to change the title of this issue😅

**Comment by viniciusjarina** [comment]
I spent some time debugging your WPF project. So I have a guess what is happening.
When you call a C# method from the KeraLua creates a new Lua object to wrap the Lua thread state. 
The LuaThread is probably being collected before you call the the timer again.

**Comment by chenxuuu** [comment]
@viniciusjarina you are right, I `lua.RegisterFunction` part of my code, it run's perfectly.
how to avoid this?

**Comment by chenxuuu** [comment]
code works well with neolua.😨
[WpfApp1.zip](https://github.com/NLua/NLua/files/3323522/WpfApp1.zip)

**Comment by chenxuuu** [comment]
Is this easy to fix? or won't fix this?

I'll waiting for this.

nlua is the best binding solution in my opinion😀

**Comment by icecolderino** [comment]
Im having same isue

[Lua]( public object Invoke(string function, params object[] args)
        {
            try
            {
                LuaFunction func = Engine.GetFunction(function);

                if(func != null)
                {
                    return func.Call(args);

                }
                Console.WriteLine("Hook isnt there");
                return null;
            }
            catch(LuaScriptException ex)
            {
                Console.WriteLine("Error happend at invoke, " + ex.Message);
                return null;
            })

**Comment by viniciusjarina** [comment]
@chenxuuu try this one https://github.com/NLua/NLua/releases/tag/v1.4.21

**Comment by chenxuuu** [comment]
@viniciusjarina perfect!😁
