### ISSUE TITLE
Unable to load DLL 'lua53' - ': The specified module could not be found

### ISSUE THREAD

**Issue by KevMacD** [NLua/NLua#310]
Using VS2017, Website in C#. Installed via NuGet, and the dependency KeraLua. Building to Framework 4.6.1.

NLua 1.4.118
KeraLua 1.0.14

System.DllNotFoundException: 'Unable to load DLL 'lua53': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

I have seen a few posts mentioning this, but I thought it was fixed in NLua 1.4.4

Any advice appreciated.

**Comment by viniciusjarina** [comment]
Hi @KevMacD this should be fixed. 
What happen if you create a new console application and add the NuGet ?

Thank you

**Comment by KevMacD** [comment]
It works fine in a console app. I developed the class I am working on in a console app then added the class to the webapp. I had installed Nlua in both before I started, using NuGet.

I have tried uninstalling both NLua and KeraLua and reinstalling them.

**Comment by viniciusjarina** [comment]
Maybe the WebApp doesn't have permission to p/Invoke into native libraries? 🤷‍♂

**Comment by KevMacD** [comment]
How do you change that?

**Comment by viniciusjarina** [comment]
Dunno, if you figure please post it here for future reference.

**Comment by KevMacD** [comment]
Moonsharp seems to work - Thanks.

**Comment by viniciusjarina** [comment]
There is pro and cons for everything.
Pro:
* MoonSharp - C# only code, works on WebApp
Cons:
* 10x slower
* Doesn't use official Lua, thus can't use official Lua libraries like LuaSocket
* Is abandoned, and using Lua 5.2
* Is not 100% compatible with Lua.
* https://www.lua.org/work/ Lua 5.4 is about to be released

But if it solves your problem. Go for it. 🍻

**Comment by KevMacD** [comment]
Passed all the automated testing and I don't need huge performance. If you figure out why Nlua doesn't work, let me know.
