### ISSUE TITLE
Unable to download older versions of NLua

### ISSUE THREAD

**Issue by 0-4** [NLua/NLua#312]
Issue #268 says that the old versions were unlisted from NuGet, but I was wondering if there was some sort of archive because I am using 3.5 and the current version runs on >4.5. I was trying to look around but was unable to find any older versions, is there any place that I can find this? NLua 1.3.2 and lower is still listed in the readme but there is no way for it to be downloaded.

**Comment by viniciusjarina** [comment]
NuGet actually never delete a package, I have enable the listing again https://www.nuget.org/packages/NLua/1.3.2.1
Is there any reason why you can't bump your project to 4.5 ? 
https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements

4.5 is compatible even with Windows Vista. Unless you are using Windows 2000 or XP you should be fine.
