### ISSUE TITLE
Add path from require function

### ISSUE THREAD

**Issue by tgiachi** [NLua/NLua#313]
It's possible add directory for search path? thanks!

**Comment by viniciusjarina** [comment]
You can use `package.path` from Lua itself https://stackoverflow.com/questions/5761229/is-there-a-better-way-to-require-file-from-relative-path-in-lua

**Comment by tgiachi** [comment]
Thank you!

Resolved!

**Comment by viniciusjarina** [comment]
Dont forget to ⭐️ the project. 😉

**Comment by tgiachi** [comment]
Done ! I ve Made a IoT framework using nlua! Check My repositories!
