### ISSUE TITLE
Error with GetFunction

### ISSUE THREAD

**Issue by icecolderino** [NLua/NLua#316]
So when i 'm trying to invoke a function

via 
var func = engine.GetFuction("On_Init");

if( func != null)
{
         return func.Call(args);
} 
Console.WriteLine("FUnction doesnt exist in the script);
return null;

it just throws a exception error and null checking doesnt work

**Comment by viniciusjarina** [comment]
Hi @icecolderino can you write a small unit test to repro your issue? 😉 
Like this one https://github.com/NLua/NLua/blob/8a34d2f48b86ff035c630aed26833bf71223236f/tests/src/LuaTests.cs#L60

Did you pushed the On_Init function to the stack?

**Comment by icecolderino** [comment]
No, on_init is a function in my modding platform

Op wo 21 aug. 2019 16:46 schreef Vinicius Jarina <notifications@github.com>:

**Comment by viniciusjarina** [comment]
Don't have info in order to help you.

**Comment by icecolderino** [comment]
> Don't have info in order to help you.

Nvm i fixed it via Luafunction func = Engine["On_Init"]

Getfunction always seemed to return a value
