### ISSUE TITLE
Can't create an instance of a class unless it comes from import()

### ISSUE THREAD

**Issue by JTinkers** [NLua/NLua#319]
Similar to the issue I've posted with static methods, I'm unable to create instances of classes unless they come from a reference imported via `import()`.

**Here's an example:**
I have a class that looks as such:
`public class Printer
{
	int X { get; set; }
	int Y { get; set; }
}`

**I register it the common way:**
`State["Printer"] = new Printer();`

**Then I execute the following Lua code:**
`print(type(Printer))`

The result: `userdata`

**Then I execute code to create a new instance of it:**
`inst = Printer()`

**The result:** `[string "chunk"]:1: attempt to call a LuaEnvTest.Types.Printer, LuaEnvTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null value (global 'Printer')`

Yet again, worth mentioning - importing `System.Drawing` and doing:
`o = Size()` 
works like a charm.

**Comment by viniciusjarina** [comment]
You just need to use `luanet.import_type` https://github.com/NLua/NLua/blob/master/tests/src/LuaTests.cs#L284 😉
