### ISSUE TITLE
Handling of ints seems to be broken on armeabi-v7a

### ISSUE THREAD

**Issue by MichaelSB** [NLua/NLua#320]
I'm using latest xamarin with latest stable NLua/KeraLua on Android. When calling a .NET-method from lua, that returns an int, we get strange results on inspecting the value lua received on armeabi-v7a devices.
Calling the method
        public int getMyInt()
        {
            return 0;
        }
via
                local x1 = Instance:getMyInt()
                Instance:Inspect("method", x1)
gives 1467109033 or similar values. They change when I restart the app I test with. The value does not depend on the int I return , 0 gives the same result as 108 as long as the app runs. These values look like some memory-address to me, but I might be wrong.
The Inspect-Method in the lua-code above is a simple method:
        public void Inspect(string what, object obj)
        {
            Console.WriteLine("{0}: {1}", what, obj.ToString());
        }
we use to inspect objects we have in lua-code. Some experiments have shown, that this seems to happen in NativeMethods.lua_pushinteger in KeraLua. Although n is 0 here, for some reason lua receives the values above.
Any idea what could be the cause of this and - even better - how to solve it? It seems to work properly on arm-v8. I can provide a simple VS-Solution (VS2019) that shows this problem.

**Comment by MichaelSB** [comment]
Doing 
Instance:Inspect("tointeger", math.tointeger(12))
in lua gives the correct value 12 in C#

**Comment by MichaelSB** [comment]
FWIW, I identified the problem. The type lua_Integer is defined to long via luaconf.h. This is a 32bit integer for armeabi-v7a. KeraLua defines it to System.Int64 in NativeMethods.cs, which causes the lua-side to see the bad values on that architecture. When I force lua_Integer to long long, everything works on armeabi-v7a and arm64-v8a.

**Comment by viniciusjarina** [comment]
Fantastic. Thank you for tracking down this problem. I will cherry-pick your fix this weekend and push the nuget.

**Comment by MichaelSB** [comment]
Great! Many thanks :)

**Comment by MichaelSB** [comment]
Feel free to close this issue whenever you feel the need to.

**Comment by viniciusjarina** [comment]
No problem. I will fix as soon I've push the NuGet package. Is only fixed if is released 😉
