### ISSUE TITLE
Setup automatic type conversion

### ISSUE THREAD

**Issue by JTinkers** [NLua/NLua#321]
There isn't any documentation on it.

Is there a way to set-up an automatic type conversion?

Ex: There's a method MyClass.TheMethod(byte[] array)

Then I run Lua code as such: `MyClass.TheMethod({5, 10, 15})` and it would be able to automatically convert LuaTable to byte array?

... or do I have to setup wrappers `ByteArray.FromTable({5, 10, 15})` etc. or accept LuaTable by default and just convert it in the method?

**Comment by viniciusjarina** [comment]
Is not possible since a Lua table is not a valid .NET object, 
But you can use `luanet.make_array(Double,{1,2})`
