### ISSUE TITLE
ExpandoObject doesn't work

### ISSUE THREAD

**Issue by Revan600** [NLua/NLua#322]
Accessing properties of ExpandoObject doesn't work, is it bug in new version? Worked well in 1.3x
Sample code:

	local obj = API:GetTestDynamic();
	local testField = obj.TestField;

	print(testField);

        public dynamic GetTestDynamic()
        {
            dynamic obj = new ExpandoObject();

            obj.TestField = "WOW!";

            return obj;
        }

**Comment by viniciusjarina** [comment]
What is `ExpandoObject` ?

**Comment by Revan600** [comment]
It is one of dynamic hand-crafted objects. We are using Newtonsoft.Json which returns one of these on anonymous deserialization.
https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.expandoobject?view=netframework-4.8

**Comment by viniciusjarina** [comment]
Fixed https://github.com/NLua/NLua/commit/83fb7adc67ab04c4200cd5cd25c703d033b2bf91
