### ISSUE TITLE
Stop running script?

### ISSUE THREAD

**Issue by Monotek18** [NLua/NLua#327]
Hello,

Sorry if I ask this question but I didn't find an answer.
Is it possible to force a running script to stop?

I know we can use `lua.IsExecuting` to get the status of the script but didn't find any function to stop the script.

If this is not implemented yet, would it be possible to add it?

Thanks!

**Comment by viniciusjarina** [comment]
Hi @Monotek18 
I guess the best way is to use some sandbox approach like creating a hook a halt the execution from the hook callback.

Remember NLua is just a layer on top of the original Lua code, try to figure how you can stop running a script using Lua C api and you can do the same using NLua.

**Comment by Monotek18** [comment]
Using a hook worked :)

Thank you for maintaining this project alive!
