### ISSUE TITLE
Non-existent member access always returns "invalid method" function

### ISSUE THREAD

**Issue by 0x0ade** [NLua/NLua#328]
Trying to access a member that doesn't exist in a CLR object should result in obtaining `nil`. Instead, it *always* results in obtaining a function that throws `Trying to invoke invalid method`.

I've tried to figure out what was going on, and found the following:

https://github.com/NLua/NLua/blob/83fb7adc67ab04c4200cd5cd25c703d033b2bf91/src/Metatables.cs#L358-L361

`PushInvalidMethodCall` (introduced in https://github.com/NLua/NLua/commit/a6721a31884d7b3a5be9ebfdc71eb5475d56cf59) is always called for non-existing members, probably because it cannot be known what "type" is expected (field / property value or function).

Wouldn't it make more sense to return `nil` when trying to access a field / property / method that doesn't exist, and resort to Lua throwing `attempt to call a nil value` when it's being used as a function?

**Comment by viniciusjarina** [comment]
Hi @0x0ade this change was added to avoid access a invlid member, and also to take advantage of the cache system. If we have to query all possible canditates to be called field/properties, interface implementations, extensions methods we will take too long.

Why exactly do you need to call invalid methods?

**Comment by 0x0ade** [comment]
I don't need to call invalid methods - let me try to give an example:

This is what I'm expecting:

```lua
local t = {}
print(t.something) -- This prints "nil"
```

This is what I'm getting:

```lua
local t = ... -- Let's assume that t is a CLR object with fields X and Y.
print(t.something) -- This prints "luaNet_function: 0BC65EC8"
```

I'm not trying to call it as a function at all, but NLua gives me a function that tells me that it's an invalid function. I would've expected it to be `nil` instead, or in the worst case, throw an exception.

Does this make more sense? 😅

**Comment by viniciusjarina** [comment]
I agree, maybe an exception would be a better case. Since `nil` could be a valid value for a field or property.
 I've changed to return a function which throw an exception to take advantage of the cache so if you call twice we don't do the lookup again.

But how this regressed for you. In this case doesn't matter if return an exception or a function since both will be invalid. Are you using this to test if the field is there or not?

**Comment by 0x0ade** [comment]
Exactly :D I was trying to do something similar to

```lua
-- Setting up a test object.
-- In my use case, this is a CLR object with only FieldB.
local obj = {}
obj.FieldB = "hello, world"

local found = obj.FieldA or obj.FieldB
print(found) -- this should've printed "hello, world"
```

where `value` could have *either* `FieldA` *or* `FieldB`. It worked fine with Lua tables, so I assumed that it should've worked fine with CLR objects as well, and was surprised to find the "invalid method" function instead :)

Just wondering, the caching code in question is the following, right?
https://github.com/NLua/NLua/blob/83fb7adc67ab04c4200cd5cd25c703d033b2bf91/src/Metatables.cs#L50-L68

Would it be possible to have an unique object as a value in the cache, and if the cached value is the unique object, return nil?

**Comment by viniciusjarina** [comment]
I understand since you are using Lua you expect some of the Lua idioms to work interoping with C#. But there is a trade that we have to do. 

If I return `nil` we would not know exactly if the value was in fact `nil` or the field/method doesn't exist.

One thing that you can do , you could use C# refrection from your Lua script and create your own `member_exist` method.

`local mm = ctype(LuaDLL):GetMethods(enum(BindingFlags,'Static,Public')) ... check inside mm`

or I think you could save the value returned by an invalid field. and use that to compare later
```
invalid_field = foo.inexistent_field

local a = nil
if x.Foo == invalid_field then
     a = bar
else
    a = x.Foo
end
```

I hope this can help you.

**Comment by 0x0ade** [comment]
Latter is what I was planning to do, but it feels more like a hack / workaround than a proper solution to me.  
The "`nil` can mean field is `nil` or non-existent issue" sounds like a non-issue as that's exactly how Lua behaves, but I understand if it doesn't fit in the design of NLua. Thanks for letting me know anyway :)

Are there any plans to make `LuaIndexFunction` itself throw the exception though? (Should I maybe submit a PR for that?) Or is this already set in stone? (Can the issue be closed?)

**Comment by viniciusjarina** [comment]
Hey @0x0ade so I was thinking. I really didn't want to change the behavior. But I think if you patch is simple and doesn't break any test we can merge it.

**Comment by viniciusjarina** [comment]
@0x0ade  I've fixed this issue

**Comment by 0x0ade** [comment]
I'm sorry for the very late reply. The project which I'm using NLua in is very slow when it comes to updates.

Thank you for fixing the issue! Sadly it seems to introduce a lot of cache misses. Upon further inspection, I noticed that this could be caused by the cache itself containing nil.

I've locally fixed the issue by changing the `LuaIndexFunction` to something similar to the following code:

```lua
local fakenil = {}

local function index(obj, name)
    local meta = getmetatable(obj)
    local cached = meta.cache[name]

    if cached ~= nil then
        if cached == fakenil then
            return nil
        end
        return cached

    else
        local value, isCached = get_object_member(obj, name)
        if isCached then
            if value == nil then
                meta.cache[name] = fakenil
            else
                meta.cache[name] = value
            end
        end
        return value
    end
end

return index
```

Please note how the cache itself doesn't contain `nil` but rather `fakenil`, and then *returns `nil` instead of `fakenil`*. This means that the information about the value always being `nil` is still being cached and there's no accidental cache miss. I hope it helps out :)

**Comment by viniciusjarina** [comment]
Thank you @0x0ade I've added your `Index` function to the latest version.
