### ISSUE TITLE
Pass function to Lua and Create String Array in Lua script

### ISSUE THREAD

**Issue by RussellHaley** [NLua/NLua#329]
Hi, 

From within C#, I just wanted to pass a function from an object to a lua script instead of the entire dotnet object. How would I do that? 

Also, how do I create an array of strings from within Lua?

Much thanks for this excellent library.

**Comment by viniciusjarina** [comment]
* You can pass the delegate like here: https://github.com/NLua/NLua/blob/83fb7adc67ab04c4200cd5cd25c703d033b2bf91/tests/src/LuaTests.cs#L2231
* You can use the helper function `luanet.make_array(String,{"foo","bar"})` like here https://github.com/NLua/NLua/blob/1cc743933ca4413e846ca0ac07bc6c8d4afa5723/extras/examples/error.lua#L3
