### ISSUE TITLE
How can I use lua package such as 'rapidjson' in Nlua?

### ISSUE THREAD

**Issue by sheng-jie** [NLua/NLua#330]
I have no idea on this, can someone give some tips on this? Thanks.

**Comment by viniciusjarina** [comment]
Yes. NLua is just a wrapper and runs on top of original (and native) Lua.
Just do:
```lua
local rapidjson = require('rapidjson')
```

and remember to configure you cpath variable so Lua can find and load the rapidjson library

**Comment by sheng-jie** [comment]
But I got error 'dynamic libraries not enabled; check your Lua installation' when require('luasql.mysql').

It works fine with lua.exe.

**Comment by viniciusjarina** [comment]
Are you using the NLua from NuGet package?

**Comment by sheng-jie** [comment]
Yes, and I run my app in the Linux container.

**Comment by viniciusjarina** [comment]
Hmm. 😕
This is quite confusing. That message is from KopiLua https://github.com/NLua/KopiLua/blob/11a565e182e8aebd01976d70f6f0969d9289e028/KopiLua/src/loadlib.cs#L258 NLua only used KopiLua for the WindowsPhone targets, about 5 years ago. (before the NuGet)

Doesn't seem like you are using the NLua from NuGet.

Also remember to ⭐️ the project. Thank you.

**Comment by sheng-jie** [comment]
@viniciusjarina 
I am pretty sure that I added NLua package in my project.
I write an simple demo for that. [https://github.com/sheng-jie/Samples.AllInOne/tree/dev/NLuaTest](NLua with Mysql demo). Can you help to check? Thanks again!

**Comment by viniciusjarina** [comment]
Can you attach the `.dll`  as well ? 😉

**Comment by GamesByJerry** [comment]
I've got the same issue, running Manjaro Linux with NLua 1.6.0 and I've only downloaded NLua using NuGet.
