### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by newpost** [NLua/NLua#332]
`static void Main(string[] args)
        {
            Lua state = new Lua();
            Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();
            Console.WriteLine("start");
            Dictionary<string, int> dic = new Dictionary<string, int> { { "a", 1 } };
            state.DoString(@"function ScriptFunc(dic) return dic[""a""] end");
            var scriptFunc = state["ScriptFunc"] as LuaFunction;

            for (int i = 0; i < 1000000; i++)
            {
                var r = scriptFunc.Call(dic).First();
            }
            stopwatch.Stop();
            Console.WriteLine(stopwatch.ElapsedMilliseconds);

        }`

**Comment by viniciusjarina** [comment]
Maybe you should use a Lua table instead a Dictionary
