### ISSUE TITLE
DllNotFoundException: lua53

### ISSUE THREAD

**Issue by dagoogle** [NLua/NLua#334]
After downloading the NuGet package on linux, making a new state throws this Exception: `DllNotFoundException: lua53`

lua53.dll does exist in the project however...
I also tried adding `msvcr110.dll` but that changed nothing.

**Comment by viniciusjarina** [comment]
NLua nuget contains the binary for Ubuntu `x86_64`.
If is not working for your distro/architecture I suggest you to build from the source your own lua53 shared library.

`msvcr110.dll` is  the CRT for windows.

**Comment by dagoogle** [comment]
That is my exact distro and architecture, but I built from the source and but I'm still getting the same exception.

**Comment by viniciusjarina** [comment]
Is probably something wrong on your `LD_LIBRARY_PATH`.  You can try to to set [`MONO_LOG_MASk=dll`](https://www.mono-project.com/docs/advanced/runtime/logging-runtime-events/)
