### ISSUE TITLE
Retrieve table variable name programmatically

### ISSUE THREAD

**Issue by Eastrall** [NLua/NLua#336]
Hello!

I am new to LUA language and wanted to try it to implement a quest script system for one of my game projects. 

I have the following LUA script:
```lua
QUEST_BEGIN = {
	title = 'quest title',
	-- more quest information
}

function QUEST_BEGIN:on_accept()
    -- do stuff
    return true
end
```

What I want to do is to retrieve the `QUEST_BEGIN` key programmatically, but I can't find any way to do it. I tried to use the `lua.Pop()` instrument to retrieve all instruments, but didn't worked out well.

Do you have any ideas how I can retrieve the `QUEST_BEGIN` key using the `Lua` class? Should I create a variable like `quest_id = 'QUEST_BEGIN'` and then use this value to access the table through the `LuaState` ?

Thank you

**Comment by viniciusjarina** [comment]
[`lua.GetTable`](https://github.com/NLua/NLua/blob/master/tests/src/LuaTests.cs#L835) Should work for you.
Or if you could load the fields globally like here https://github.com/NLua/NLua/blob/master/tests/src/LoadFileTests.cs#L79
