### ISSUE TITLE
Removal of a LuaFunction from a C# event Action throwing NullReferenceException

### ISSUE THREAD

**Issue by Mgarnold** [NLua/NLua#338]
`obj.Test:Add (funcA)` works perfectly fine and runs the code within funcA, but adding 
`obj.Test:Remove (funcA)` throws
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at NLua.CodeGeneration.GenerateDelegate(Type delegateType)
>    at NLua.CodeGeneration.GetDelegate(Type delegateType, LuaFunction luaFunc)
>    at NLua.DelegateGenerator.ExtractGenerated(Lua luaState, Int32 stackPos)
>    at NLua.MetaFunctions.MatchParameters(Lua luaState, MethodBase method, MethodCache methodCache, Int32 skipParam)
>    at NLua.Method.LuaMethodWrapper.CallMethodFromName(Lua luaState)
>    at NLua.Method.LuaMethodWrapper.Call(IntPtr state)
>    at NLua.MetaFunctions.RunFunctionDelegate(IntPtr luaState)
>    at KeraLua.NativeMethods.lua_pcallk(IntPtr luaState, Int32 nargs, Int32 nresults, Int32 errorfunc, 
>    IntPtr ctx, IntPtr k)
>    at NLua.Lua.DoString(String chunk, String chunkName)
>    at ConsoleApp.Program.Main(String[] args) in 
>   C:\Users\NAME\source\repos\ConsoleApp\Program.cs:line 76

with the code at line 76 being `lua.DoString("obj.Test:Remove (funcA)");`

**Comment by viniciusjarina** [comment]
Hi @Mgarnold the way that the event handlers works, it creates a C# delegate to wrap your Lua function event handler. 
To remove the event handler you need to pass the delegate and not the Lua function. The Add method will return the delegate, you can store the delegate to later remove the event handler.

I've created a small example here : https://github.com/NLua/NLua/commit/5bf3391964e865d0a9344ef30bc63a12ca456947#diff-8aa37412f4b48b161b9e772ef2a6e850R2652

**Comment by Mgarnold** [comment]
That actually makes a lot of sense. Thanks!
