### ISSUE TITLE
Unhandled exception on DoString kills the app process

### ISSUE THREAD

**Issue by esionov** [NLua/NLua#340]
Hello.

Current behaviour: executing a code sample under the try/catch block kills the process instead of throwing an exception.
Expected result: exception is thrown.

I prepared a project to demonstrate what's happening.
[LuaTest.zip](https://github.com/NLua/NLua/files/3944078/LuaTest.zip)

Could you help me resolving this problem. I assume if something wrong with a script, we should get a message over the exception (process must live).

**Comment by lichutinm** [comment]
I'm also waiting for fix :)

**Comment by viniciusjarina** [comment]
Hi this issue was a probem with enumeration array access and was fixed here https://github.com/NLua/NLua/releases/tag/v1.4.26

If you still can create a small program that kill the dotnet core process let me know.

I am leaving the issue open in case anyone still have any issue.
