### ISSUE TITLE
Get binary string from lua

### ISSUE THREAD

**Issue by whc2001** [NLua/NLua#349]
Just as #58 , I am trying to get a string containing binary data in lua to C#:

            Lua state = new Lua();
            state.DoString(@"
                testBytes = ""\xA5\x5A\x01\x8B\x26\xAA""
            ");

            string testBytesStr = state.GetString("testBytes");
            byte[] testBytes = Encoding.UTF8.GetBytes(testBytesStr);
            // 3F 5A 01 3F 26 3F
            // Would lose data whatever encoding I use to convert to byte[]

I noticed there was a pull request GH-331 which seems to fix the issue, which added `_extractValues.Add(typeof(byte[]), GetAsByteArray);`, so I tried this:

            Lua state = new Lua();
            state.DoString(@"
                testBytes = ""\xA5\x5A\x01\x8B\x26\xAA""
            ");

            byte[] testBytes = state["testBytes"] as byte[];
            // It's null

            testBytes = (byte[])state["testBytes"];
            // Exception: Unable to cast string to byte[]

Is there any workaround for it?

**Comment by viniciusjarina** [comment]
If the type is a Lua string the index operator will try to return as string.
The best approach is to create a callback with `byte[]` and invoke it from Lua.

https://github.com/NLua/NLua/commit/d8ae863aeae4cff6cdb6de48ddddb36a2940bf14#diff-8aa37412f4b48b161b9e772ef2a6e850R2610
