### ISSUE TITLE
Poor performance on indexers

### ISSUE THREAD

**Issue by CallumDev** [NLua/NLua#351]
Indexing a .NET Object from Lua (e.g. a `Dictionary<string,string>`) will always call `GetMethodFallback` making it incredibly slow

**Comment by viniciusjarina** [comment]
If this is a performance critical code path, is there any reason why you can't use a regular table instead ?

**Comment by jamespedid** [comment]
This is a very glaring leaky abstraction detail. It's hard to tell from the documentation what is supported in way that performs well, and what doesn't; it gives the appearance that it should work well with any managed C# object. Can you explain what you mean by using a 'regular table' instead? Creating a LuaTable object in C#? That seems a little bit restrictive, given that you have to pass the interpreter into it. Can you explain more on what you're talking about, @viniciusjarina
