### ISSUE TITLE
Calling a function with leading nil parameters causes error (invalid arguments to method call)

### ISSUE THREAD

**Issue by timothywalter** [NLua/NLua#353]
Hey there!

Thanks for the great repository! I've been having a load of fun implementing it in Unity (2019.3.0f6). There's a small bug somewhere though, but I'm stuck narrowing down what causes it.

**I get the error `invalid arguments to method call` when calling a method (through lua) with leading nil parameters.** I'm expecting other results from Lua (I'm comparing results with [lua.org/demo.html](lua.org/demo.html))

Example code that shows what does work as expected and what doesn't:

```csharp
var environment = new Lua();

// ... print function is registered here

// Note: a, b, c, d, e, f and g are never set
// Expected: 1 nil nil nil nil nil nil
// Works as expected!
environment.DoString("print(1, b, c, d, e, f, g)");

// Expected: 
// Works as expected!
environment.DoString("print()");

// Expected: nil nil nil nil nil nil 2
// Doesn't work: LuaScriptException: invalid arguments to method call
environment.DoString("print(a, b, c, d, e, f, 2)");

// Expected: nil nil nil nil nil nil nil
// Doesn't work: LuaScriptException: invalid arguments to method call
environment.DoString("print(a, b, c, d, e, f, g)");
```

The `print` function is registered like so:
```csharp
MethodInfo printMethod = typeof(CustomLuaFunctions).GetMethod(
    "Print",
    BindingFlags.NonPublic | BindingFlags.Static,
    null,
    new Type[] {
        typeof(object[])
    },
    null);
environment.RegisterFunction("print", printMethod);
```

and looks like this:
```csharp
public static char SYMBOL_PRINT_CONCAT = '\t';
private static void Print(params object[] arguments)
{
    string output = "";
        
    if(arguments != null)
    {
        foreach (object argument in arguments)
        {
            if (argument == null)
            {
                output += SYMBOL_PRINT_CONCAT + "nil";
                continue;
            }

            object[] toStringResults = LuaManager.Call("tostring", argument);

            output += SYMBOL_PRINT_CONCAT + toStringResults[0].ToString();
        }
    }
    else
    {
        output = "nil";
    }

    Debug.Log(output.TrimStart(SYMBOL_PRINT_CONCAT));
}
```

The relevant part of the stack trace with the error:
```
NLua.Lua.ThrowExceptionFromError(System.Int32 oldTop)(at Assets / System / UserScripting / NLua / Lua.cs:359)
NLua.Lua.DoString(System.String chunk, System.String chunkName)(at Assets / System / UserScripting / NLua / Lua.cs:497)
```

Why would I ever need this to work I hear you ask? One example: if I have a function `a` that returns many values, some of the first it returns may be nil (depending on the internal logic). This bug prevents me from debugging by just dumping the results into print. Simulated example (that has the same error occur):
```csharp
// Expected: nil nil 3
// Doesn't work: LuaScriptException: invalid arguments to method call
environment.DoString("function a() return nil, nil, 3 end");
environment.DoString("print(a())");
```

**Comment by viniciusjarina** [comment]
Thank you @timothywalter I will take a look later.

Would be nice if you could also push a test case

**Comment by timothywalter** [comment]
I've written some quick and dirty tests, but they all seem to pass. Can you verify that they are written correctly?

I'm unsure what aspect of my code is causing this if these tests pass fine...

**Comment by timothywalter** [comment]
So yes I was using an outdated version as a starting point and forgot all about that.

After updating NLua and KeraLua to the current versions everything is working as expected (and as a side-effect I'm now on Lua 5.3 which is great).

Again, my apologies for the false alarm.
