### ISSUE TITLE
1.3.2.1 Source?

### ISSUE THREAD

**Issue by Valleriani** [NLua/NLua#357]
Hello,

I was wondering about getting the 1.3.2.1 source as I'm using it in my current program and I believe I need to edit some things (I want a custom Require() function for the state).

I was not able to find it here. Thanks!

**Comment by viniciusjarina** [comment]
* I don't need patch the code to add your custom require, you could simple override the current require
* Also NLua repo contains the history since the first commit, just use git.
Thanks
