### ISSUE TITLE
How to convert lua table to json?

### ISSUE THREAD

**Issue by icecolderino** [NLua/NLua#361]
So i've been trying multiple lua scripts for this but none of them seem to work and all give the same error when their global variable gets called

  attempt to index a nil value (global 'json')

```CSharp
   Engine.LoadString(Properties.Resources.json, "json").Call();
```

Can anyone help me?

**Comment by chenxuuu** [comment]
it's easy, use this [Simple JSON Encode/Decode in Pure Lua](http://regex.info/blog/lua/json)
