### ISSUE TITLE
Table pairs in the wrong order

### ISSUE THREAD

**Issue by icecolderino** [NLua/NLua#362]
So i'm facing a isue when i create a table and loop trough it the pairs are not in the correct order as they should

Example

```Lua
local table = {
    Message1=  "Hello",
    Message2 = "World",
    Message3 = "Welcome"
}

for key, value in pairs(table) do
    print("Key:" .. key .. ", Value: " .. value)
end

```

it can come out like this
```
"Key: Message3, Value: Welcome"
"Key: Message1, Value: Hello"
"Key: Message2, Value: World"
```

Thanks for in advance

**Comment by triad-rom** [comment]
It has nothing to do with NLua. Its Lua's limitation, if you want to get the correct order. Do it in an indexed manner.

```lua
local table = {
   [1] = "Hellol",
   [2] = "World",
   [3] = "Welcome!"
}

-- and use ipairs, instead of pairs
for _, v in ipairs(table) do
    print(v)
end
```

**Comment by icecolderino** [comment]
> It has nothing to do with NLua. Its Lua's limitation, if you want to get the correct order. Do it in an indexed manner.
> 
> ```lua
> local table = {
>    [1] = "Hellol",
>    [2] = "World",
>    [3] = "Welcome!"
> }
> 
> -- and use ipairs, instead of pairs
> for _, v in ipairs(table) do
>     print(v)
> end
> ```
> 
> If you want to have a custom key and value you can do it like this
> 
> ```lua
> local table = {
>    [1] = { key = "Message 1", value = "Hello" },
>    [2] = { key = "Message 2", value = "World" },
>    [3] = { key = "Message 3", value = "Welcome!" }
> }
> 
> for _, v in ipairs(table) do
>    print(print("Key:" .. v.key .. ", Value: " .. v.value)
> end
> ```
> 
> Hope that helps you

Wil try it out when possible.

Thanks mate

**Comment by viniciusjarina** [comment]
AFAIK is like a Dictionary the order is not enforced, since it uses a hash for key.

https://stackoverflow.com/questions/19260423/how-to-keep-the-order-of-a-lua-table-with-string-keys
