### ISSUE TITLE
Accessing static C# functions after importing their classes doesn't work

### ISSUE THREAD

**Issue by SeleDreams** [NLua/NLua#367]
![image](https://user-images.githubusercontent.com/16335601/79177821-f9d97080-7e03-11ea-9e06-bcf294893d47.png)
![image](https://user-images.githubusercontent.com/16335601/79177855-08278c80-7e04-11ea-9489-5a5e3924eb11.png)

From what I can see, I didn't make specific errors when naming the import and the Debug.Log is a static functions so I really can't tell where the problem comes from

**Comment by tznind** [comment]
Is `Debug.Log("Test")` your lua code? Normally in Lua methods use the colon symbol e.g. `Debug:Log('123')` .  It would help to see the full method not just a screenshot of  3 lines.

(I'm quite new to Lua myself.)

**Comment by SeleDreams** [comment]
> 
> 
> Is `Debug.Log("Test")` your lua code? Normally in Lua methods use the colon symbol e.g. `Debug:Log('Test')` . It would help to see the full method not just a screenshot of 3 lines.
> 
> (Disclaimer: I'm quite new to Lua myself.)
> 
> You might be able to get an answer from looking at the tests e.g.
> 
> https://github.com/NLua/NLua/blob/f28dddd2762e23a929b47827eeb4d61e1ca0e7cb/tests/src/LuaTests.cs#L2542
> 
> This test also looks like it might be relevant:
> 
> https://github.com/NLua/NLua/blob/f28dddd2762e23a929b47827eeb4d61e1ca0e7cb/tests/src/LuaTests.cs#L1700

from the NLUA website it said to use . when it comes to static classes

but even by using : it doesn't change anything

**Comment by tznind** [comment]
Ah my mistake, have you tried copying one of the tests exactly and adapting it to your namespace/Type?

**Comment by viniciusjarina** [comment]
@SeleDreams can you repro the issue in a small program? or even better a unit test?

**Comment by JTinkers** [comment]
> @SeleDreams can you repro the issue in a small program? or even better a unit test?

I think he's right, I just tried with a plain console:

![image](https://user-images.githubusercontent.com/30983493/79883779-9c8d8280-83f4-11ea-8adc-14e438828441.png)

**Comment by tznind** [comment]
This works.  @JTinkers your example I think will set a global called "Con" to be a reference to the `System.Type` object.  So you would be able to access methods/properties of `System.Type` i.e. not what you are looking for.

```csharp
[Test]
public void TestStaticMethod()
{
    using (var lua = new Lua())
    {
        lua.LoadCLRPackage();
        lua.DoString($"import('{typeof(Console).Namespace}')");
        lua.DoString("Console.WriteLine('123')");

        lua.DoString($"import('{typeof(Math).Namespace}')");
        Assert.AreEqual(234,lua.DoString("return Math.Max(123,234)")[0]);
    }
}
```

**Comment by viniciusjarina** [comment]
Thank you @tznind
