### ISSUE TITLE
Trouble Accessing Items in List derived objects

### ISSUE THREAD

**Issue by MichaelSenko** [NLua/NLua#372]
I'm converting a project over from LuaInterface to NLua, and am struggling a bit accessing items in objects that are derived from List.  The particular problem is using ZedGraph, which is a .NET based charting library.  The example below accesses a ZedGraphControl in C#, and then it runs Lua code that attempts to mimic the C# code.  On the Lua side, I expect to get a GraphPane object when I index the PaneList, but instead I get a luaNet_function.  The Lua syntax previously worked with LuaInterface.

**C#:**
public static Lua luaState = new Lua();
public static ZedGraphControl cPlotControl = new ZedGraphControl();
[STAThread]
static void Main(string[] args)
{
  PaneList cPaneList = cPlotControl.MasterPane.PaneList;
  Console.WriteLine("cPaneList.GetType(): {0}", cPaneList.GetType());
  GraphPane cGraphPane = cPaneList[0];
  Console.WriteLine("cGraphPane.GetType(): {0}", cGraphPane.GetType());
  luaState.LoadCLRPackage();
  var res = luaState.DoFile("test.lua");
}

**test.lua:**
luanet.load_assembly ("ZedGraph")
local ZedGraphControl = luanet.import_type("ZedGraph.ZedGraphControl")
plotControl = ZedGraphControl()
local paneList = plotControl.MasterPane.PaneList
print ("PaneList: ", paneList)
print ("PaneList.Count: ", paneList.Count)
print ("PaneList.GetType(): ", paneList:GetType())
local pane0 = paneList[0]
print ("pane0: ", pane0)

**Console Output:**
cPaneList.GetType(): ZedGraph.PaneList
cGraphPane.GetType(): ZedGraph.GraphPane
PaneList:       ZedGraph.PaneList: 65204782
PaneList.Count:         1
PaneList.GetType():     ZedGraph.PaneList: 49972132
pane0:  luaNet_function: 00000241C1C557E8

**Comment by viniciusjarina** [comment]
this should work fine .
Try to reduce the problem into a small program or a small unit test.

Thanks 😉
