### ISSUE TITLE
Is there a limit/negative impact for having many Lua instances?

### ISSUE THREAD

**Issue by jamespedid** [NLua/NLua#376]
Hello, I'm trying to figure out how to appropriately create Lua instances for project to balance performance and ease of access. Is the number of lua instances intended to be low, or can you have many of them?

For example: I want to create an IDictionary<object, object> wrapper around a LuaTable. Can I have a Lua instance per dictionary instance in this way? Is there any known negative penalty for having multiple Lua environments communicate back and forth in this way?

Overall, I want to use Lua as a scripting language for a game, and have each event fired execute its own lua context for that. Is this going to be too slow?

What I'm leaning towards right now is to use a single lua instance and having all LuaTables be based off of that interpreter, using guids as their "fullPath". Is this a good strategy?

**Comment by viniciusjarina** [comment]
I guess how you will embed Lua in your application is up to you.

You can write your application in C# and expose a couple of entry-points in Lua.

There is no write or wrong, you need to experiment and see if works for you.

Cheers
