### ISSUE TITLE
How to build NLua properly from CLI with dotnet build?

### ISSUE THREAD

**Issue by 2kCarlos** [NLua/NLua#379]
I just started learning more command-line based approaches for building (especially recently learning CircleCI, Docker, and PowerShell).
**Note:** I am most interested in building for **.NET Core** (please tell me it's possible! 🙏)

However, I have no idea how to properly build NLua. I basically want to run NLua as easily as possible, so I can import the DLLs into the Unity game engine.

When I clone this repo and attempt a `dotnet build NLua.sln` from the root of my local version of the repo, I get tons of errors.

![image](https://user-images.githubusercontent.com/25470751/82721106-4ed09800-9c88-11ea-8621-9510510376cf.png)

**Comment by viniciusjarina** [comment]
Hello @2kCarlos  
Is there any reason you can't use the build from NuGet?

**Comment by viniciusjarina** [comment]
you need to restore the NuGet packages before build
`nuget restore NLua.Core.sln` `NLua.sln` contains the projects to the classic .NET Framework.

Also, I would recommend AzureDevops for CI

**Comment by 2kCarlos** [comment]
Ohh.. interesting, MSDN says installing the CLI  for NuGet.exe 5.0 would require .NET Framework 4.7.2.

Is it possible to restore these nuget packages without requiring Windows/.NET Framework?

**Comment by 2kCarlos** [comment]
Okay, I used the following from PowerShell 7:

```
K:\Git Projects\NLua> cd ..
K:\Git Projects> curl --output nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
K:\Git Projects> .\nuget.exe restore NLua/NLua.sln
K:\Git Projects> dotnet build NLua/NLua.sln
```

and I'm still getting the same errors 🤔

**Comment by viniciusjarina** [comment]
Try to build `NLua.Core.sln` 
So, why do you need to build from source instead of use the NuGet package? are you fixing anything?

**Comment by 2kCarlos** [comment]
Ohh, thanks so much, that worked!

Just for learning purposes, since I had never compiled programs through command line before. I'll needa be comfortable with it in order to work on virtual environment in CircleCI and automating my workflows.

'Still wondering where everyone learned all this stuff though haha.

**Comment by viniciusjarina** [comment]
Good luck 🙌
