### ISSUE TITLE
Creating UserData from C#

### ISSUE THREAD

**Issue by craftersmine** [NLua/NLua#383]
Hi everyone, is it possible to create UserData from C# code and return it from C# method?
I've found LuaUserData class and able to create an instance of it, but how to use it?
I can't assign anything via luaUserData["key"] = value and I don't know about method LuaUserData.Call(), how is that works?

Thanks

**Comment by viniciusjarina** [comment]
I am not sure what you trying to do.
Can you share more details of your issue?

**Comment by craftersmine** [comment]
I'm trying to emulate execution of scripts from mod, one of the function returns Java class, and in documentation it says that fucnction returns userdata, but in the mod itself it converts userdata to table.

Is it possible to return C# class to Lua?

**Comment by craftersmine** [comment]
Nevermind, I've read documentation wrong, it actually returns table, but in documentation it says it returns userdata. My bad...
But any way, is there any possible to return C# class to Lua?

**Comment by HgAlexx** [comment]
Hi,

In my .NET code I have the following function define:

```
    public static class HgConverter
    {
        public static DateTime UnixToDateTime(long unix)
        {
            return DateTimeOffset.FromUnixTimeSeconds(unix).LocalDateTime;
        }
    }
```
This class is exposed to lua via:
`lua.DoString(@" import ('MyAssembly', 'MyNamespace') ");`

Then in lua I can call:
```
local datetime = HgConverter.UnixToDateTime( some_int_value )
-- here datetime is a object of type DateTime from .NET
```
You can then call any function of class DateTime on the datetime variable.

As you can see, there is nothing particular to do to get .NET object from lua, other than importing what you want to use.

If you import a non-static class, you can create an instance on the lua side like this:
```
local d = DateTime()
```

You can find many example on the front page of the project. 

Regards,

**Comment by craftersmine** [comment]
Do I need use "import" in order to make it work? I don't wanna expose certain namespaces from my app and if I made some sort of plugin system, the plugins will not work if "import" needed until they add "import("assembly", "their.namespace")" on top of whole execution code.

**Comment by HgAlexx** [comment]
Hi,

I personally use "import" with sandboxing on top of that.
For example I import "System.IO" but then only whitelist certain classes: "Path", "File", etc..
I've also made a namespace specifically to expose part of my app code and I only import this one (+ whitelist of classes inside it).

I don't know if you can import specific classes one by one, I haven't done that myself.

Not knowing the project make it hard to provide a correct solution ;)

**Comment by craftersmine** [comment]
Well, the project is hosted on my GitHub, but it barely done. For specific classes I've doing wrapping with .lua, but some methods returns C# classes
