### ISSUE TITLE
NLua doesn't handle exceptions

### ISSUE THREAD

**Issue by craftersmine** [NLua/NLua#385]
Hello, I've a problem with handling .NET exceptions though Lua scripts, I've tried throw an exception in C# method, just return exception (using return, not throw). Every time when I try use pcall in Lua, C# method is being called, but exception doesn't being handled by Lua pcall, it always passes through it and being catched by C# try-catch block. Am I doing something wrong or what?
I've found old topic on StackOverflow with link to that repo with example but I've got 404.

Thanks

**Comment by viniciusjarina** [comment]
Can you write a small test reproing the issue?

**Comment by craftersmine** [comment]
The Lua code execution wrapped into try-catch
https://github.com/craftersmine/OCVM/blob/7c84832508beccd3f990ec0ab636f1fdc716f205/craftersmine.OCVM.Core/Base/LuaApi/LuaExecutionModule.cs#L121
And pcall occurs here https://github.com/craftersmine/OCVM/blob/7c84832508beccd3f990ec0ab636f1fdc716f205/craftersmine.OCVM.Resources/lua/component.lua#L11 but I didn't commited changes yet, so it will look like pcall(Component.invoke())
The Component.invoke method from .NET code https://github.com/craftersmine/OCVM/blob/7c84832508beccd3f990ec0ab636f1fdc716f205/craftersmine.OCVM.Core/Base/LuaApi/OpenComputers/Component.cs#L34

**Comment by craftersmine** [comment]
If needed more info I can provide it

**Comment by craftersmine** [comment]
```csharp
void SomeFunction()
{
    throw new Exception("Some error, I guess");
}

try
{
    lua.DoString("error, reason = pcall(SomeFunction())");
}
catch
{
    Console.WriteLine("Exception catched"); // pcall calls function but it goes there after throwing exception
}
```

**Comment by viniciusjarina** [comment]
`SomeFunction()` will be called before pcall and the result will be passed by pcall
you would need to do `error, reason = pcall(SomeFunction)`

**Comment by craftersmine** [comment]
Oh, crap, I forgot that in Lua you can just pass a name of function and it will be "object" that can be called somewhere else. Sorry, thanks anyway
