### ISSUE TITLE
Error while creating Lua via LuaState

### ISSUE THREAD

**Issue by Hromon** [NLua/NLua#387]
![image](https://user-images.githubusercontent.com/29508584/89100845-36f15f00-d403-11ea-85f0-1442891d051f.png)
![image](https://user-images.githubusercontent.com/29508584/89100866-70c26580-d403-11ea-8bce-b9fc8e5a251e.png)

**Comment by viniciusjarina** [comment]
HI @Hromon  what you want to do?

The overload version of the NLua ctor is meant to be used by Lua threads. 
Maybe would be better to move it to internal

Anyway. the panic callback will throw an Exception already.

If you need a low level manipulation of the Lua VM you should consider using only the KeraLua package instead.

**Comment by Hromon** [comment]
I would like to use NLua, but apparently I have to do just that.
Is there no way to write your own Allocate in NLua?

**Comment by viniciusjarina** [comment]
In theory you could do anything you could do with the regular Lua is just a binding to the original implementation.
Is there any reason why you cant'do 
```
var l = new Lua();
l.State.SetWhataverPropertyYouWantToChange(0);
```
?

**Comment by Hromon** [comment]
Yes, it's work, thanks.
