### ISSUE TITLE
I cannot define Lua lua = new Lua()) ...

### ISSUE THREAD

**Issue by karpiyon** [NLua/NLua#388]
I'm new to this...
Using visual studio with class application I added the NLua via NuGet.

My code is this:
```
...
using NLua;
...
using (Lua lua = new Lua())...
```

But when I run it I get an exception on the above line:

_System.BadImageFormatException
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
  Source=KeraLua
  StackTrace:
   at KeraLua.NativeMethods.luaL_newstate()
   at NLua.Lua..ctor()_
 

What am I doing wrong? I tried to search the internet and came up with solutions that it is since I am running a 64bit app while the one I am trying to load (NLUA) in 32bit.
Is that it? if yes them is there 64 version?

THANK YOU

**Comment by viniciusjarina** [comment]
Hi @karpiyon  yes the NuGet provides x64, x86, ARM and ARM64 binaries. This is actually KeraLua NuGet

Your issue seems like a dup of https://github.com/NLua/KeraLua/issues/65

Let me know if that works for you.

Thank you

**Comment by karpiyon** [comment]
Thank,
Is working now
I'm new to this, could you please send me a reference for an example of reading .lua file.

I managed to read the object like this:
var userFile = lua.DoFile(@"c:\Users\Chupi\Saved Games\DCS\Config\Input\F-16C_50\keyboard\Keyboard.diff.lua");

The lua file looks like below and I want to use it in C#.
Thanks


local diff = {
            ["keyDiffs"] = {
                        ["d1033pnilu1034cdnilvdnilvpnilvunil"] = {
                                    ["name"] = "Throttle Smoothly - Decrease",
                                    ["removed"] = {
                                                [1] = {
                                                            ["key"] = "Num-",
                                                },
                                    },
                        },
                        ["d15pnilunilcdnilvdnilvpnilvunil"] = {
                                    ["added"] = {
                                                [1] = {
                                                            ["key"] = "M",
                                                },
                                    },
                                    ["name"] = "F10 Theater map view",
                        },
                        ["d201pnilu202cdnilvdnilvpnilvunil"] = {
                                    ["added"] = {
                                                [1] = {
                                                            ["key"] = "J",
                                                },
                                    },
                                    ["name"] = "Aircraft Rudder Left",
                        },

**Comment by viniciusjarina** [comment]
Try to learn more about Lua first https://www.lua.org/docs.html
