### ISSUE TITLE
Best practices for managing  NLua.Lua object  in Aspnetcore？

### ISSUE THREAD

**Issue by dingsongjie** [NLua/NLua#397]
I found that instantiating a Lua object is expensive,so how do I manage Lua objects in a multithreaded environment？
Should I create an object pool, when the IsExecuting property of all Lua objects is true, create new objects?

**Comment by viniciusjarina** [comment]
Sorry @dingsongjie I am not a expert on ASP.NET Core, maybe you could try the ASP.NET Core repo.
