### ISSUE TITLE
Save back to stream

### ISSUE THREAD

**Issue by Andrioden** [NLua/NLua#399]
I would like to be able to parse a lua data file, then do changes to the lua data structure and then copy it to a stream.

Is this possible or considered implemented?

``` c#
using (Lua lua = new Lua())
{
    lua.State.Encoding = Encoding.UTF8;
    lua.DoFile(filePath);

    // Do changes
    // ...    

    lua.Save(stream);
}
```

**Comment by viniciusjarina** [comment]
You could try to load Lua table and modify the table and then save the Table as string

**Comment by Andrioden** [comment]
> then save the Table as string

How can i do this? I cant find any method that returns the string, or anything close to this. Do I have to write my own ToString method that recursively scans the Lua file and its tables to build a string?

``` c#
Lua lua = new Lua();
lua.State.Encoding = Encoding.UTF8;
lua.DoFile(filePath);

lua.ToString() // "NLua.Lua"
((LuaTable)lua["MyTableKey"]).ToString() // "table"
```

**Comment by viniciusjarina** [comment]
I would explore some pure Lua approaches.

http://lua-users.org/wiki/TableSerialization
https://www.lua.org/pil/12.1.1.html
