### ISSUE TITLE
Binary Data Lost When passing byte[] to lua.

### ISSUE THREAD

**Issue by moriyalb** [NLua/NLua#402]
`
//byte from the file. [0x28, 0x00, 0xDC, 0x61, 0x12, 0x7B, 0xE2, 0x25, 0x5B, 0x0F]
byte[] input = File.ReadAllBytes(f);

var state = new Lua()
state['str'] = Encoding.Default.GetString(input);
state.DoString("for i = 1, string.len(str) do print( string.byte(string.sub(str, i, i )) end")
//result 40 0 63(whoops, lost data) 97 18 123 63(error) 37 63(error) 91 15
`

I think those bytes ( > 127)  will be lost. How can I pass correct byte array or other things to lua. ?

**Comment by viniciusjarina** [comment]
Try to pass the byte[] directly
```
byte[] input = {0x28, 0x00, 0xDC, 0x61, 0x12, 0x7B, 0xE2, 0x25, 0x5B, 0x0F};

var state = new Lua();
state["str"] = input;
state.DoString("for i = 0, str.Length-1 do print( str[i]) end");
```
