### ISSUE TITLE
Question about perfomance

### ISSUE THREAD

**Issue by sebfischer83** [NLua/NLua#408]
Hi, I try to add some scripting to my project. Currently I use NLua and Jint.
I run some performance tests and the results are a bit strange, is there something wrong in what I doing here?

| Method | Size |       Mean |     Error |    StdDev |     Median | Kurtosis | Skewness | Rank | Baseline |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|------- |----- |-----------:|----------:|----------:|-----------:|---------:|---------:|-----:|--------- |-------:|-------:|------:|----------:|
|   Jint |   64 |   4.108 μs | 0.0985 μs | 0.1474 μs |   4.055 μs |    2.635 |   0.9259 |    1 |       No | 0.6409 |      - |     - |   5.24 KB |
|   NLua |   64 | 145.625 μs | 4.6038 μs | 6.6026 μs | 142.693 μs |    1.823 |   0.5698 |    2 |       No | 1.4648 | 0.4883 |     - |  12.54 KB |

`    internal class LuaScriptingEngine : IScriptingEngine
    {
        private readonly string _script;

        public LuaScriptingEngine(string script)
        {
            _script = script;
        }

        public T Execute<T>(object obj)
        {
            using var lua = new Lua();
            lua["dataObject"] = obj;
            lua.DoString(_script);
            return (T)lua.GetObjectFromPath("res");
        }

        public void Dispose()
        {
        }
    }`

When I only create one Lua object and use it often the times where much more worse.

`  [Benchmark(OperationsPerInvoke = 64)]
        public int NLua()
        {
            int a = 0;
            for (int i = 0; i < Size; i++)
            {
                var b = _luaScriptingEngine.Execute<bool>(_testClasses[i]);
                a += b ? 1 : 0;
            }

            return a;
        }`

**Comment by viniciusjarina** [comment]
Try to use a profiler to see where is the bottleneck

And be careful doing benchmarks, usually micro-benchmarks are very different from real life scenarios.

**Comment by viniciusjarina** [comment]
Hope you have found where was your bottleneck
