### ISSUE TITLE
Console NLua.exe

### ISSUE THREAD

**Issue by MScholtes** [NLua/NLua#409]
I guess this is not an issue, but I don't know where to ask.
With your great project it is very easy to access Lua from C#. I have created a few examples: great.

But on the readme page the animated GIF _NLuaCommand.gif_ shows a **NLua.exe** doing the reverse (Lua calling .Net), this would also be a great feature. But after compiling I didn't find this NLua.exe. 

Did I miss something or not understand? Or is it an example that I have to look for somewhere else?

Thank you very much, Markus

**Comment by viniciusjarina** [comment]
Hi @MScholtes 
That is actually LuaInLua from David Manura http://lua-users.org/wiki/LuaInterpreterInLua
Running inside of NLua, you can't call C# from plain lua.exe since you need to be running inside CLR

**Comment by MScholtes** [comment]
Hello @viniciusjarina,

thanks for the tip!

That's pretty simple again: you need a short C# wrapper program that pulls **_NLua.dll_**, and runs **_LoadCLRPackage_** method, and then executes _**lua.lua**_. Great!

**Comment by viniciusjarina** [comment]
We used to have that on the repo, I removed since was not part of the core library, was more an example:

https://github.com/NLua/NLua/blob/0d96ff03ddddd84648c84da9e862748a5cea459d/Applications/LuaRunner/LuaNetRunner.cs
