### ISSUE TITLE
NLua as a Unity Package?

### ISSUE THREAD

**Issue by 2kCarlos** [NLua/NLua#418]
Hi there!
I've been using NLua for my games made in Unity/C# and it's been amazing.
I created the file/folder structure for Unity to interpret it as a Unity package, since NuGet packages generally don't play well with Unity.

I want to share it with my friends though, and was wondering if it'd be okay for me to create a separate repo just to have KeraLua and NLua as Unity packages, where I'd update it every so often as releases come out?
Then, people can do one of the following to import the package into Unity without hassle! :) 

1. Add the package from Unity package manager using the Git URL option,
2. Clone the git repo, and add the package from Unity package manager using local files, or
3. Create a git submodule referencing the git repo, and add the package from Unity package manager using local files

---

If you have any suggestions or different way(s) of going about it, integrating it into your build pipeline, etc. -- I'm curious to hear your thoughts!
But I figured making a separate repo for it and just doing it manually would save a lot of programming work on your side haha.

Here's the `package.json` I used for NLua (it's using an old version, I'll be updating mine soon).
All credit to you @viniciusjarina of course!

```
{
	"name": "com.github.nlua.nlua",
	"version": "1.4.32",
	
	"displayName": "NLua",
	"description": "NLua is the bridge between the Lua and .NET worlds. NLua runs on top of KeraLua bindings.\nNLua 1.4.32 requires KeraLua >= 1.0.29, based on https://nuget.org. \n\nAccess the Github Repository at https://github.com/NLua/NLua",
	
	"keywords": [
		"scripting",
		"lua",
		"nlua",
		"programming"
	],
	"author": {
		"name": "Vinicius Jarina",
		"email": "viniciusjarina@gmail.com",
		"url": "https://github.com/viniciusjarina"
	},
	"dependencies": {
		"com.github.nlua.keralua": "1.0.29"
	}
}
```

It looks like this in Unity:

![image](https://user-images.githubusercontent.com/25470751/118338942-4a6e4200-b4cc-11eb-9240-6bfdc5992c05.png)

**NOTE:** I also wrote a custom Lua script importer for Unity with adorable icons.
It'd make a lot of sense to also publish that publicly for others to be able to use :).
Therefore, it'd be 3 Unity packages:

1. KeraLua
2. NLua
3. Unity Lua Scripts Support

Let me know your thoughts whenever you have some time!

**Comment by viniciusjarina** [comment]
Sure no problem

I guess some already did this in the past. People even bundled and sell it in the Asset Store 😅. Would be nice if Unity use the actual .NET and not a custom hacky-version that doesn't support NuGet out of the box.

**Comment by 2kCarlos** [comment]
Haha oh wow.
I would love if they did that 🙏 we'll see haha

Yay, thanks!
Once I create them, I'll link them here and close this issue :).

**Comment by 2kCarlos** [comment]
Woo! Got it up and running, hopefully it works on others' Unity projects.

I made 3 Unity packages related to this discussion:

1. [NLua (Unity Package)](https://github.com/2kpixelstudios/nlua-unity-package)
2. [KeraLua (Unity Package)](https://github.com/2kpixelstudios/keralua-unity-package)
3. [Unity Lua Script Support (ability to create lua scripts in Unity, and import as TextAssets)](https://github.com/2kpixelstudios/unity-lua-script-support)

I hope this helps someone! :)
Thanks again btw for letting me make those.

Not sure how often I'll update them, but this is a start!

**Comment by JoelCreatesGames** [comment]
these are great, would be nice if we could get something official to be included
