### ISSUE TITLE
How to extend imported c# class in lua code?

### ISSUE THREAD

**Issue by maikgreubel** [NLua/NLua#421]
Hello,

first want to say, I'm new to NLua and did not found a solution or example to achieve my attempt to extend a C# class by lua code. This is the situation:

- A class named "A" in namespace "Test".
- A class named "B" which is my lua interface, injecting lua code and call a lua script file.
- A lua script file which creates an instance of "A" and try to inject a new function by extending "A".

```csharp
namespace Test {
  class A {
    public void MethodY()
    {
      // do something
    }
  }

```

```csharp
class B {
  private Lua lua = new Lua(); // NLua object

  public B Register()
  {
    lua.DoString("import('A', 'Test') \n" +
      "function CreateInstanceOfA() \n" +
      "  return new A()\n"
      "end"
    )
    return this;
  }

  public void Execute()
  {
    lua.DoFile("c.lua");
  }
}
```

```lua
function Z(arg)
  -- do something with arg
end

a = CreateInstanceOfA()
a.MethodZ = Z
```

As I can tell, the DoString() call working well, as well as creating instance "a" by calling "CreateInstanceOfA()". The last line in lua script file failed with

```
System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at System.Type.GetMethod(String name)
   at NLua.MetaFunctions.SetFieldOrPropertyInternal(Lua luaState)
```

In debugging the method NLua.MetaFunctions.SetFieldOrPropertyInternal() I saw, that if the member could not be found, the "set_Item" method will be searched. I tried to implement it into my "A" class this way:

```csharp
            public void set_Item(string name, object value)
            {

            }
```

but it is still not found. Is there a way to implement this?

**Comment by viniciusjarina** [comment]
I am not sure what you are trying to do.

But in order to "extend"  a type you need to use `make_object` . That would the equivalent of create a derived class

**Comment by maikgreubel** [comment]
Thank you for pinpointing that. I could find my issue using example in Test classes:

https://github.com/NLua/NLua/blob/2722c72eb2d7b7e07dbbdce443b1fd1191de3186/tests/src/LuaTests.cs#L58

Solution was to use luanet.load_assembly and luanet.import_type. Then I implemented the method set_Item(string name, object o) and store the LuaFunction object o as private member in A. In an public method name "O" the private member is null-checked and then called.
