### ISSUE TITLE
Does it support LuaJit?

### ISSUE THREAD

**Issue by kkolyan** [NLua/NLua#422]
Hi! Cannot find out, does LuaJit support exists and maintained?

**Comment by viniciusjarina** [comment]
LuaJIT ABI is not compatible with Lua, and the project is pretty much dead.
I recomend to move code that require a lot of optimization to C# or native (C/C++) and use Lua to parts that are not bottleneck. Also I strongly recommend using a profiler to figure if executing the script is really the bottleneck.

**Comment by kkolyan** [comment]
Thanks for an answer and advices!
Hm. I see a fresh commits. How could it be dead?

**Comment by viniciusjarina** [comment]
Maybe Mike Pall changed his mind. But a while ago he was trying to find a new maintainer for the project. As you can see the latest stable release is from a few years ago.

LuaJIT is a great project, but is for a different scope. For embedding scripting in your application I guess the performance of the scripts shouldn't be the bottle neck.

**Comment by kkolyan** [comment]
Yeah, I see.

**Comment by kkolyan** [comment]
Hm, wait. You mean LuaJIT is dead? At first I've thought you've talked about NLua, which looks pretty alive.

As I see, LuaJIT is conserved in terms of language features (stuck around 5.1), but it looks maintained:
<details>
  <summary>Git log sample</summary>

   ![image](https://user-images.githubusercontent.com/3194236/122590304-0a215700-d06a-11eb-874f-056b0837a3fc.png)

</details>

Actually, In my case scripts are bottleneck (proven with profiler and experiments with reference Lua implementation), so LuaJIT is only way for me.
I'm trying to maintain [my own bindings](https://bitbucket.org/kkolyan/luah) and that's pretty joyful activity. That's not coupled explicitly to LuaJIT, but I used headers from luajit and do not test in on another implementations.

**Comment by viniciusjarina** [comment]
You could try to fork https://github.com/nlua/keralua and change the `NativeMethods.cs` to invoke the LuaJIT dll instead Lua dll..

**Comment by kkolyan** [comment]
That's not too clear. What's the benefits of KeraLua over NLua? better IDE/build configuration?

**Comment by viniciusjarina** [comment]
Get more familiar with the code and you will see it ;-)

**Comment by kkolyan** [comment]
sorry, I cannot afford _becoming familliar_ just to find out whether it worth attention or not.

**Comment by viniciusjarina** [comment]
KeraLua is a dependency of NLua they are not replacements.

This is stated in the first lines of the README

**Comment by kkolyan** [comment]
Hm, now I see.

KeraLua looks well crafted and documented. Even if I'll stick to my analog, KeraLua looks as exceptional source of clarification regarding how some Lua API functions works in corner cases.

Thanks you!
