### ISSUE TITLE
How to build for android?

### ISSUE THREAD

**Issue by friuns2** [NLua/NLua#432]
Hello i'm trying to build for android but i get this error

im downlaoded this code https://github.com/NLua/lua

![](https://user-images.githubusercontent.com/16543239/133411946-3f008a8f-95c1-4356-8ef0-c2568a5143d9.png)

**Comment by viniciusjarina** [comment]
Are you trying to build NLua ?

**Comment by friuns2** [comment]
Yes for android

**Comment by viniciusjarina** [comment]
Is there any reason why not use the nuget?

**Comment by friuns2** [comment]
nuget is missing android runtime
![image](https://user-images.githubusercontent.com/16543239/133572769-a2824b72-66f1-4574-8b06-1174efa10a73.png)

**Comment by viniciusjarina** [comment]
the runtimes are only used by `.NET Core/5` for Xamarin.iOS/Android the libraries are embedded inside the KeraLua assembly.

Which error did you get adding the NuGet on Android ?

**Comment by friuns2** [comment]
oh really? I guess on unity armv7 this not work because i'm getting missing Lua54 exception.

**Comment by friuns2** [comment]
for monoAndroid i'm getting error  
 

![](https://user-images.githubusercontent.com/16543239/133578042-68a4e248-bedf-432d-b8c4-84a8dc818020.png)

**Comment by friuns2** [comment]
yes still getting dllNotFoundException: liblua54.so  
  
are they both embended arm64 and  armv7 ?
