### ISSUE TITLE
Overwriting functions does not work

### ISSUE THREAD

**Issue by Auios** [NLua/NLua#433]
I have this file here:
```lua
function add(a, b)
	return a + b
end
```
I load this file with:
```cs
lua.DoFile("add.lua");
```
I can then expect that if I call `print(add(5,2))` that I will get `7` back.

If I modify that lua file to:
```lua
function add(a, b)
	return a + b + 100
end
```
and re call:
```cs
lua.DoFile("add.lua");
```
then I'd expect `print(add(5,2))` to return `107`.

But it still returns `7`.

Why?

**Comment by viniciusjarina** [comment]
IIRC Lua cache the loaded modules. You could try to invalidate Lua cache.. or you can use `DoString` instead

**Comment by Auios** [comment]
Actually I'll continue this question in a different issue. #435
