### ISSUE TITLE
How to invalidate lua cache?

### ISSUE THREAD

**Issue by Auios** [NLua/NLua#435]
Question from #433 . How can you invalidate lua cache?

**Comment by viniciusjarina** [comment]
You might have to reset `package.loaded` . I am not sure this is only affected by `require` of if `dofile` also affect this.
In any case this would be more a Lua issue than a NLua issue.

Remember NLua just P/Invokes into native Lua, you might consider sending a message to the Lua mailing list with specifics Lua questions

**Comment by Auios** [comment]
Thanks!
