### ISSUE TITLE
Can't pass byte[] from lua to .net function.

### ISSUE THREAD

**Issue by Kagamia** [NLua/NLua#438]
```
using (Lua lua = new Lua())
{
    lua.LoadCLRPackage();
    lua.DoString(@"
import 'System'
import 'System.IO'

local buf = Byte[2]
File.WriteAllBytes('out.bin', buf)
");
}
```

expected: success
actual: `NLua.Exceptions.LuaScriptException:“Invalid arguments to method: File.WriteAllBytes”`

----

From [CheckType.cs](https://github.com/NLua/NLua/blob/main/src/CheckType.cs#L117), when netParamType is one of `string`, `char[]`, `byte[]`, it checks if lua param is string type or nil (line 129), so that it can't go through the netObject parsing (line 171) if previous checking failed. 

I think it's better to always try convert param to netObject to fix this issue.

**Comment by viniciusjarina** [comment]
I guess this issue was already fixed

**Comment by Kagamia** [comment]
this was fixed in https://github.com/NLua/NLua/commit/db21506a2265a465def7ab61e3c60bec8f0438c2, I'll close this issue:)
