### ISSUE TITLE
Unable to load shared library 'lua54' when deployed to Azure App Services

### ISSUE THREAD

**Issue by jcbcn** [NLua/NLua#464]
I'm having issues when running my .net6 app using NLua 1.6.0 targeting linux-x64 on Azure App Services.

I can see the root directory contains lua54.so and I'm publishing as a self contained deployment.

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'lua54' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblua54: cannot open shared object file: No such file or directory
```

I looked at the logs for `LD_DEBUG=all` but there was nothing that mentioned `lua`

**Comment by viniciusjarina** [comment]
I am not sure how I can help you. Locally it works?

**Comment by jcbcn** [comment]
Works locally and hosted on Azure App Services with a Windows host

**Comment by viniciusjarina** [comment]
I would do a small app that loads a simple `.so` and test if this is a Azure limitation.

**Comment by jcbcn** [comment]
I did some more digging:

```
/home/site/wwwroot/runtimes/linux-x64/native>ldd liblua54.so --version
liblua54.so:
./liblua54.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./liblua54.so)
	linux-vdso.so.1 (0x00007ffecefbe000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fadd2385000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fadd21c5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fadd256e000)
```

Looks like their host doesn't have GLIBC_2.29
