### ISSUE TITLE
Class from imported namespace not working in Script.

### ISSUE THREAD

**Issue by robtherobot12** [NLua/NLua#473]
C#:
```
namespace KVSV.Metaverse
{ 

...

state.LoadCLRPackage();
state.DoString(@"import('VRProject', 'KVSV.Metaverse')
                             --import = function() end");
state.DoString(code);

...

}
```
Vector3 C#:
```
namespace KVSV.Metaverse
{
    public class Vector3
    {
    ...
    }
}
```

Lua:
```
x = Vector3()
```

Error (using MSTest unit testing):
```
Test method KVSV.Metaverse.WorldTest.StartTest threw exception: 
NLua.Exceptions.LuaScriptException: [string "chunk"]:1: global 'Vector3' is not callable (a nil value)
```

Any ideas what I'm doing wrong?

**Comment by viniciusjarina** [comment]
There are a test just like this and is passing, something must be wrong with your code 😕 
https://github.com/NLua/NLua/blob/4783440b6532837fb3a34b08dff3ef57d5f6a019/tests/src/LuaTests.cs#L2278

**Comment by robtherobot12** [comment]
Yeah, I was using the wrong name for the assembly. I knew I should've just given it some time, thanks a lot for your help.
`import('Metaverse', 'KVSV.Metaverse')`
