### ISSUE TITLE
Question about data types of arithmetic operations

### ISSUE THREAD

**Issue by davepruitt** [NLua/NLua#475]
I have a simple question about data types of arithmetic operations. 

In the Lua documentation, we only have 1 numeric type (https://www.lua.org/manual/2.2/section3_3.html), and that type is represented as a 64-bit double-precision floating point number (https://www.lua.org/pil/2.3.html).

I have tried running the following code in .NET:
```
public object Add(object a, object b)
{    
    object result = default;
    using (NLua.Lua state = new NLua.Lua())
    {
        state["x"] = a;
        state["y"] = b;
        var result = state.DoString("return x + y")[0];
    }
    
    return result;
}
```

When I pass two Int32 objects to this function, the resulting type is an Int64. When I pass an Int32 and a Double, or when I pass two Doubles, then the return type is Double. Based on the Lua documentation, I would expect NLua to always return a value of type Double no matter what input types I pass in from my C# code.

I was just curious what the precise defined behavior is for NLua for arithmetic operations? Can I always expect an Int64 to be returned if no floating point arguments are used, and a Double to be returned otherwise?

Thanks!

**Comment by MegaPiggy** [comment]
NLua uses Lua 5.4.
Lua 5.4 has 2 numeric types (float and integer).
https://www.lua.org/manual/5.4/manual.html#2.1

**Comment by davepruitt** [comment]
Thanks!
