### ISSUE TITLE
unicode

### ISSUE THREAD

**Issue by seanmars** [NLua/NLua#48]
is Nlua support unicode string?

**Comment by fizyk20** [comment]
There is still an issue with unicode literals in Lua code when they are read from C#.

Example:

script.txt:
```lua
function test()
	return "Pchnąć w tę łódź jeża lub ośm skrzyń fig"
end
```

C# code:
```csharp
Lua state = new Lua();
string script = System.IO.File.ReadAllText("script.txt"); // or ReadAllText("script.txt", Encoding.UTF8); - doesn't help
state.DoString(script);
LuaFunction fun = state["test"] as LuaFunction;
Console.WriteLine(fun.Call().First());
```

**Comment by Tenrys** [comment]
Can confirm.

On a Steam bot:
`19:54 - Tenrys: ] print("àààà")
19:54 - CGull#: ����

**Comment by viniciusjarina** [comment]
@Tenrys @fizyk20 
IIRC this is a limitation of Lua 5.2.x not from NLua.

I think you can escape your unicode strings, or specify them on your C# code and pass them to NLua.
