### ISSUE TITLE
luanet lua module?

### ISSUE THREAD

**Issue by CapsAdmin** [NLua/NLua#49]
The readme suggests theres a luanet module you can use 
(https://github.com/NLua/NLua#whats-new-in-luainterface-121)

But I cant find anything about this in this repository. Has this feature been removed?

**Comment by d-led** [comment]
any progress on this?

**Comment by viniciusjarina** [comment]
Not really. I am not having to much time to work on NLua. I want to create a "Lua version" independent, spliting the functionality of lnet.cpp into a separated dll, and be able to use NLua with Lua51, 52 or even 53.

But I am not working on this right now

**Comment by d-led** [comment]
I'm thinking of taking a look, but can't promise much effort either

**Comment by CWolfs** [comment]
Tempted to take a look at this too as I'd like to use LuaJIT with NLua instead of core Lua.

**Comment by hineios** [comment]
So there is no way to accomplish this?

I'm also trying to do something similar, trying to use a dll within a lua environment (let's say, vanilla lua with nothing on it).
I've searched and searched but I cannot find this 'luanet' anywhere...
