### ISSUE TITLE
How do you pass functions as delegates?

### ISSUE THREAD

**Issue by vlOd2** [NLua/NLua#491]
How do you pass functions as delegates to C# methods/classes that expect a delegate?
For example, there is the winforms method for controlls called Invoke that expects a Delegate
In C#, you'd normally pass your function as an instance of Action by doing Action(My Function)

But how can you do this in Lua? I tried just Invoke(My Function) but that gives `Invalid arguments to method: Control.Invoke` and I also tried creating an Action by doing Invoke(Action(My Function)) but that gives `System.Action does not contain constructor(.ctor) argument match`

Also `My Function` is just a placeholder

**Comment by viniciusjarina** [comment]
If is an `event` you can use `Add` to subscribe to it 
like here https://github.com/NLua/NLua/blob/main/extras/examples/form_alt.lua#L27

**Comment by vlOd2** [comment]
That is not the solution, I do know that events can be subscribed to with Add, I am asking how to create `Action` and pass that to the Invoke method on controls?

**Comment by vlOd2** [comment]
@viniciusjarina That is not the solution, I do know that events can be subscribed to with Add and unsubscribed from by passing the EventHandler returned from add to Remove, I am asking how to create delegate Action and pass that to the Invoke method on controls?

**Comment by vlOd2** [comment]
In the meantime, I wrote myself a quick work-around, but I wonder if there is any intended way to do what I asked

**Comment by viniciusjarina** [comment]
iirc Lua functions can be used to places you expecting a delegate

**Comment by viniciusjarina** [comment]
I am not sure what you trying to do. Write a small test case

**Comment by vlOd2** [comment]
I am trying to pass a method to a Delegate parameter, for example System.Windows.Forms.Control.Invoke() takes a delegate, and I tried passing the method directly (`Invoke(MyFunc)`) but it threw `Invalid arguments to method: Control.Invoke` and I also tried wrapping it in an Action (`Invoke(Action(MyFunc))`) as you'd normally do in C#, but that threw `System.Action does not contain constructor(.ctor) argument match`

**Comment by vlOd2** [comment]
Here is a test case, the method `MyMethodThatTakesADelegate` has the arguments as one of the overloads of `System.Windows.Forms.Control.Invoke`
```
class Program
{
    static void Main(string[] args)
    {
        MyMethodThatTakesADelegate(new Action(() => 
        {
            Console.WriteLine("Hello from C#!");
        }));

        Lua lua = new Lua();
        lua.LoadCLRPackage();
        lua["MyMethodThatTakesADelegate"] = (Action<Action>)MyMethodThatTakesADelegate;

        try
        {
            /*
             * MyMethodThatTakesADelegate(function() 
             *      print("Hello, world")
             * end)
            */
            lua.DoString("MyMethodThatTakesADelegate(function() print(\"Hello, world\")end)");
        }
        catch (Exception ex) { Console.Error.WriteLine($"First test case failed: {ex}"); }

        try 
        {
            /*
             * import("System")
             * MyMethodThatTakesADelegate(Action(function() 
             *      print("Hello, world")
             * end))
            */
            lua.DoString("import(\"System\") MyMethodThatTakesADelegate(Action(function() print(\"Hello, world\") end))");
        }
        catch (Exception ex) { Console.Error.WriteLine($"Second test case failed: {ex}"); }
        Console.ReadLine();
    }

    public static void MyMethodThatTakesADelegate(Delegate myDelegate) 
    {
        myDelegate.DynamicInvoke();
    }
}
```

**Comment by vlOd2** [comment]
Output of test case using the latest version of NLua on .NET 4.7.2 (also on .NET 4.6 where I first discovered this bug/lack of support)
```
Hello from C#!
First test case failed: NLua.Exceptions.LuaScriptException: [string "chunk"]:1: Cannot invoke delegate (invalid arguments for  MyMethodThatTakesADelegate)
Second test case failed: NLua.Exceptions.LuaScriptException: [string "chunk"]:1: System.Action does not contain constructor(.ctor) argument match
```
