### ISSUE TITLE
Get print() output

### ISSUE THREAD

**Issue by tomxp411** [NLua/NLua#51]
How can I catch the output from print() to use somewhere in my program? I have my own custom log window that redirects Console.Out, but I can't figure out how to trap Lua's print() function. 

Is that possible, or am I SOL?

**Comment by dagostinelli** [comment]
I realize this is an old issue, but the answer was not complete.  The `print` function has specific behavior that is not handled by simply replacing the function with a different one. I've documented the failed cases below.  The proper solution should be to redirect stdout or stderr.  How do we do that?

Deep down in KopiLua, it directly fetches stdout/stderr from Console.  [See this code](https://github.com/NLua/KopiLua/blob/e52b05d1075249057971e254a53114bc0b30d041/KopiLua/src/luaconf.cs)  How do we get in the middle of this?  

```
		public static Stream stdout = Console.OpenStandardOutput();
		public static Stream stdin = Console.OpenStandardInput();
		public static Stream stderr = Console.OpenStandardError();
```

This code shows the problem with replacing print.

```
public class Script
{
	public static void print(string s)
	{
		Console.WriteLine(s);
	}
}

<snip>

NLua.Lua lua;
lua = new NLua.Lua();
lua.LoadCLRPackage();
lua.RegisterFunction("print", typeof(Script).GetMethod("print"));

// works
lua.DoString(print('hello world'));

// throws exception (invalid arguments to method call)
lua.DoString("print('a', 'b', 'c', 3)");

// throws exception (invalid arguments to method call)
lua.DoString("print(16)");
```

We can do a variation that takes params.  This won't throw an exception (which is inconsistent behavior BTW). It just won't print the number

```
public class Script
{
	public static void print(params string[] others)
	{
		foreach (string s in others)
		{
			Console.WriteLine(s);
		}
	}
}

// won't print the number
lua.DoString("print('a', 'b', 'c', 3)");
```

**Comment by pro510** [comment]
From above, you could just use object rather than string and then call ToString on each parameter

**Comment by ITR13** [comment]
Trying to do this with a delegate: 
`
		private delegate void Print (params object[] others);
		private Print _print;
`

where I assign print with 
`
			_print = (others) => Console.WriteLine(string.Join("\t",
				others.Select (o => o.ToString ()).ToArray ()));
`

and register it with 
`
			lua.RegisterFunction("print",_print.Method);
`

If I call it by `print("Some Text")` I get a LuaScriptException with the message "1: Invalid arguments to method call"

Is there any way to fix this? I'd prefer not to use static methods so I can put the output different places for different instances.

**Comment by belucha** [comment]
Since there seems no solution if found a work around that works for any number and type of parameters.
I just register a lua function as print, which calls the registered function with all arguments as a single table!
This is a wild card argument registration ....
```cs
        void _print(LuaTable luaTable)
        {
            var b = new StringBuilder();
            foreach (var v in luaTable.Values)
            {
                if (b.Length > 0)
                {
                    b.Append(' ');
                }
                b.Append(v.ToString());
            }
            var text = b.ToString();
            Console.WriteLine(text);
        }
        _lua.RegisterFunction(nameof(_print), this, typeof(SimulationMachine).GetMethod(nameof(SimulationMachine._print), System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance));
            _lua.DoString(@"print = function(...) _print({...}); end");
```
