### ISSUE TITLE
NET8 support

### ISSUE THREAD

**Issue by ShortArrow** [NLua/NLua#512]
[Download page](https://web.archive.org/web/20231222213925/https://dotnet.microsoft.com/en-us/download) is now .NET8.

- .NET8 support is on loadmap?
- Will supporting NET8 come at the expense of NET 7 support?
- Need to wait for KeraLua to support NET8? 
- And would is code change will [like this](https://github.com/NLua/NLua/commit/ea506a7353852efbf1c69de6edef0978fd3efe5c)?

This package is looks good to me. Thanks for maintainers.
my experimental app is good to work with NET7 and NLua yesterday.
So I will goto use this package from now.
And I want use with NET8 if possibly.

**Comment by viniciusjarina** [comment]
.NET 7 libraries are forward compatible. Is something broken in your scenario running on .NET 8 ?

**Comment by ShortArrow** [comment]
I didn't know they are forward compatible.
It seems that my ignorance has been proven.

After I was knew NET8 is LTS, think NET8 is better for my product. 
But when I was see [supported frameworks list](https://www.nuget.org/packages/NLua/1.6.3#supportedframeworks-body-tab) NET8 is not there.

My product's `dotnet build` are said `*.csproj : error NU1100: Unable to resolve 'NLua (>= 1.6.3)' for 'net8.0-windows7.0'.`.
And I fork this repo and KeraLua repo, then tried to migrate NET8 from NET7 to make PR, but my skill was nothing.

At the moment, I can't think of any other way other than using `sed -e 's/net7/net8/g'` to replace.
My force is little. May the Force be with you.
