### ISSUE TITLE
How to call C# async functions

### ISSUE THREAD

**Issue by 632575987** [NLua/NLua#514]
# UWP code

```csharp

 public async Task<bool> AskAsync(string content, string title = "Ask", string primaryTxt = "Yes", string sndTxt = "No")
 {
     try
     {
         var dia = new ContentDialog() { Title = title, Content = content, PrimaryButtonText = primaryTxt, SecondaryButtonText = sndTxt };
         var ds = await dia.ShowAsync();
         return ds == ContentDialogResult.Primary;
     }
     catch (Exception ex)
     {
         Debug.WriteLine(ex.Message);
         return false;
     }
 }

public void RunLua(string code)
{
    using (Lua lua = new Lua())
    {
        lua.State.Encoding = Encoding.UTF8;
        lua["ui"] = this;
        lua.LoadCLRPackage();
        lua.DoString(code);
    }
}
```

# Lua code
```lua
--import csharp namespace...
result=ui:AskAsync("how r u?")
--or result=await ui:AskAsync("how r u?") ??
print(result)
```

When the lua code is executed, the code immediately returns result nil without waiting for the dialog button to be clicked.  So I don't know how to make lua wait for the return value in the async method

**Comment by viniciusjarina** [comment]
NLua relies on .NET reflection to invoke methods. There is no await in Lua. I would suggest to "wrap" the async method in a way that you can callback a Lua method after is done.

Something like 
```csharp
using System;
using System.Threading.Tasks;
using NLua;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Lua lua = new Lua();
            lua["obj"] = new Program();
            lua.DoString(@" 
                           obj:InvokeAsk('Hello', function(res)
                            if res then
                                print('AskAsync: true')
                            else
                                print('AskAsync: false')
                            end
                           end)
");
            Console.ReadKey();
        }

        public void InvokeAsk(string param, LuaFunction callback)
        {
            AskAsync(param).ContinueWith(t =>
            {
                bool result = t.Result;
                callback.Call(result);
                return true;
            });
        }

        private static async Task<bool> AskAsync(string param)
        {
            await Task.Delay(1000);
            return false;
        }
    }
}

**Comment by 632575987** [comment]
> NLua relies on .NET reflection to invoke methods. There is no await in Lua. I would suggest to "wrap" the async method in a way that you can callback a Lua method after is done.
> 
> 
> 
> Something like 
> 
> ```csharp
> 
> using System;
> 
> using System.Threading.Tasks;
> 
> using NLua;
> 
> 
> 
> namespace ConsoleApp1
> 
> {
> 
>     internal class Program
> 
>     {
> 
>         static void Main(string[] args)
> 
>         {
> 
>             Lua lua = new Lua();
> 
>             lua["obj"] = new Program();
> 
>             lua.DoString(@" 
> 
>                            obj:InvokeAsk('Hello', function(res)
> 
>                             if res then
> 
>                                 print('AskAsync: true')
> 
>                             else
> 
>                                 print('AskAsync: false')
> 
>                             end
> 
>                            end)
> 
> ");
> 
>             Console.ReadKey();
> 
>         }
> 
> 
> 
>         public void InvokeAsk(string param, LuaFunction callback)
> 
>         {
> 
>             AskAsync(param).ContinueWith(t =>
> 
>             {
> 
>                 bool result = t.Result;
> 
>                 callback.Call(result);
> 
>                 return true;
> 
>             });
> 
>         }
> 
> 
> 
>         private static async Task<bool> AskAsync(string param)
> 
>         {
> 
>             await Task.Delay(1000);
> 
>             return false;
> 
>         }
> 
>     }
> 
> }
> 
> 
> 
> 

Thanks very much. This is very useful to me.
