### ISSUE TITLE
Unhandled Exception: System.DllNotFoundException for 'lua54' Library on Linux Deployment

### ISSUE THREAD

**Issue by William-Laverty** [NLua/NLua#516]
**Issue Context:**

The error occurs while attempting to run a simple .NET console application developed in Visual Studio Code. The application executes without errors on MacOS but crashes on Linux, raising an exception related to the inability to load the 'lua54' shared library or its dependencies.

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'lua54' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/debian/.dotnet/shared/Microsoft.NETCore.App/8.0.0/lua54.so: cannot open shared object file: No such file or directory
/home/debian/LinuxLuaCompiler/LinuxLuaCompiler/bin/Debug/net8.0/lua54.so: cannot open shared object file: No such file or directory
/home/debian/.dotnet/shared/Microsoft.NETCore.App/8.0.0/liblua54.so: cannot open shared object file: No such file or directory
/home/debian/LinuxLuaCompiler/LinuxLuaCompiler/bin/Debug/net8.0/liblua54.so: cannot open shared object file: No such file or directory
/home/debian/.dotnet/shared/Microsoft.NETCore.App/8.0.0/lua54: cannot open shared object file: No such file or directory
/home/debian/LinuxLuaCompiler/LinuxLuaCompiler/bin/Debug/net8.0/lua54: cannot open shared object file: No such file or directory
/home/debian/.dotnet/shared/Microsoft.NETCore.App/8.0.0/liblua54: cannot open shared object file: No such file or directory
/home/debian/LinuxLuaCompiler/LinuxLuaCompiler/bin/Debug/net8.0/liblua54: cannot open shared object file: No such file or directory

   at KeraLua.NativeMethods.luaL_newstate()
   at KeraLua.Lua..ctor(Boolean openLibs)
   at NLua.Lua..ctor(Boolean openLibs)
```

**Environment:**

Operating System: Linux Debian 12 (Failed to work on Ubuntu also)
.NET Core Version: 8.0.0
IDE: Visual Studio Code 

**Additional Information:**

The program runs successfully on MacOS but encounters the shared library loading issue on Linux deployment.
No modifications were made to the code specifically targeting different OS environments.
Attempts to locate the 'lua54' shared library in specified paths resulted in "No such file or directory" errors on Linux.

Any guidance or suggestions to resolve this discrepancy in library loading between MacOS and Linux environments would be appreciated.

**Comment by viniciusjarina** [comment]
Well .. Linux binary distribution of libraries is a real pain. I added a build of Lua binaries to the NuGet to make the life of those using the NuGet easier. The binary is built using Azure Pipelines, running on Ubuntu and using some version of gcc. Unfortunately deploying binaries on Linux is not that simple. All others systems (macOS, Windows, Android, iOS) is buttery smooth. SkiaSharp also have to deal with similar problem a few years ago and they endup building multiple distros binary nugets. 
NLua is mostly used by Windows users so this was never a real problem. Luckily NLua is 100% compatible with unmodified binary Lua 5.4. 
In theory what you could do is install Lua 5.4 using the package manager, and during your deploy tweak your .NET application to not deploy KeraLua Lua binaries. This way whenever the CLR tries to do dlopen, the version loaded will be the one installed by the package manager.

**Comment by William-Laverty** [comment]
Would you be able to evaluate on your solution? The .NET application compiles, but upon execution it encounters errors related to locating shared libraries.

As I've recently started programming in .NET, I'm not entirely certain about the necessary fixes.

**Comment by viniciusjarina** [comment]
Try to load Lua natively using a C program on your end. and see why `dlopen` fails. There is probably a dependency missing. The tests on CI are passing fine on Ubuntu 20.04.

**Comment by William-Laverty** [comment]
I have tried running NLua on a fresh boot of Ubuntu 20.04 with the same simple program but still get this errror:

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'lua54' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 

   at KeraLua.NativeMethods.luaL_newstate()
   at KeraLua.Lua..ctor(Boolean openLibs)
   at NLua.Lua..ctor(Boolean openLibs)
```

It is less than on Debian but still the same problem occurs. I got a C program to execute Lua and it didn't work unless I told it where the Lua.h file was located. Do you know any thing I'm doing wrong that could cause NLua to still not be working.

**Comment by William-Laverty** [comment]
I've discovered that the NLua library causes the errors when executing on a ARM based Linux environment. Switching to a AMD64x Linux environment works with NLua, not exactly sure what the problem is with ARM execution but the best solution is to just use a 64x version of Linux.

**Comment by William-Laverty** [comment]
I've discovered that the NLua library causes the errors when executing on a ARM based Linux environment. Switching to a AMD64x Linux environment works with NLua, not exactly sure what the problem is with ARM execution but the best solution is to just use a 64x version of Linux.

**Comment by viniciusjarina** [comment]
NLua "should" be compatible with ARM arch. I didn't have time or hardware to test it on Linux. But in other environments (Windows, Mac. iOS etc) NLua works fine.

**Comment by sanny-io** [comment]
@viniciusjarina there indeed appears to be some problem with ARM. I had this same error when using an ARM docker image. Simply changing it to use AMD64 like @William-Laverty said solved it immediately.
