### ISSUE TITLE
[Question/Suggestion] .NET 4.5 async methods

### ISSUE THREAD

**Issue by Choonster** [NLua/NLua#52]
Would it be possible to add support for the [async methods](http://msdn.microsoft.com/en-us/library/vstudio/hh191443%28v=vs.110%29) in .NET 4.5 using Lua coroutines?

e.g. calling an async method from within a coroutine would cause NLua to yield and then resume when the method completes, imitating the behaviour of `await` in C#.

I can understand if there's no easy way of doing this.

**Comment by cmisztur** [comment]
I have not been able to figure [this one out yet](https://stackoverflow.com/questions/30169009/how-to-task-wait-when-everything-is-happening-on-thread-1).

**Comment by SwiTool** [comment]
@cmisztur sorry to ping you... But what was the link refering to? The question is no more available... Thanks
