### ISSUE TITLE
UTF-8 encoding with accents

### ISSUE THREAD

**Issue by ShiiniiDev** [NLua/NLua#542]
Hello,

I'm not succeeding to get the right uppercase of my letters

```
using var lua = new Lua();

lua.State.Encoding = Encoding.UTF8;

var script = @"
            function upper_case(input)
                return string.upper(input)
            end
        ";
        
lua.DoString(script);
var upperCaseFunc= lua.GetFunction("upper_case");
var inputStr = "élève";
var result = upperCaseFunc.Call(inputStr)[0];
```

Output

`éLèVE`

Expected

`ÉLÈVE`

I've attempted to rewrite script in this way

```
 var script = @"
            utf8 = require('utf8')
            function upper_case(input)
                return utf8.upper(input)
            end
        ";
```

But I've a nil error, I guess it can't reach utf8.

If I remove `lua.State.Encoding = Encoding.UTF8;`
I'll get `?L?VE`

Thanks for your time

**Comment by viniciusjarina** [comment]
Does that work on Lua CLI ?

**Comment by ShiiniiDev** [comment]
> Does that work on Lua CLI ?

`print(string.upper("élève"))` will output `éLèVE`

**Comment by ShiiniiDev** [comment]
Here a workaround for anyone wants the feature

Via https://github.com/artemshein/luv/tree/master

You will need
- utf8data.lua
- utf8.lua

Load them in NLua

```
using var _lua = new Lua();

lua.DoFile("<your_path>/utf8data.lua");
lua.DoFile("<your_path>/utf8.lua");
```

Then, use in this way

```
function upper_case(input)
    return string.utf8upper(input)
end
```
