### ISSUE TITLE
What is the correct way to round trip binary data from Lua to C#?

### ISSUE THREAD

**Issue by niklasfrykholm** [NLua/NLua#58]
If I have binary data (say a .png file) in a Lua string and what to get that data as a byte[] in C#, what is the correct way?

On my machine, this worked, but it didn't work on a different machine with russian locale:

```
Encoding.GetEncoding(1252).GetBytes(s)
```

This seems to work consistently on the machines where I've tried it:

```
Encoding.Default.GetBytes(s)
```

But it feels brittle. What if the Lua string is not a valid encoding of anything in the default encoding. Do I have to base-64 encode my binary data?

**Comment by chenxuuu** [comment]
I have a test about this:

```csharp
Lua state = new Lua();
string s = (string)state.DoString("return string.char(1,2,3,0x3f,0x40,0xff,0xf3,0x9f)")[0];
state["r"] = s;
state.DoString("for i=1,#r do print(r:byte(i)) end");
```

output:
```
1
2
3
63
64
63
63
63
```

`0xff`,`0xf3`and`0x9f` are lost.

**Comment by RussellHaley** [comment]
Hi @chenxuuu , perhaps you should open a new issue on what you are seeing? I was able to reproduce your results.
