### ISSUE TITLE
"." in key causes error

### ISSUE THREAD

**Issue by MikeSenko** [NLua/NLua#68]
Although sloppy, the following is valid in Lua:
local junk = {}                                                           -- Create table
key = "dot.dot"                                                         -- Create the key
junk[key] = 1                                                            -- assign value

Attempting the same thing from the C# side of NLua seems to cause an error:

LuaTable junk = (LuaTable) lua.DoString("return {}")[0];  // Create the table
string key = "dot.dot";                                                // Create the key
junk[key] = 1;                                                            // This causes a Lua error

**Comment by willzhanglala** [comment]
I don't think it's a fix.  We don't want a implicit split a dot.
it't junk["dot.dot"] = 1, that should not means junk.dot.dot = 1
junk.dot = junk.dot or {}
junk.dot.dot = 1

The behaviour should be same
This crash still occurs in the LuaTable
LuaTable tb= Lua.NewTable("abcdefg")
tb["dot.dot"]= 1  will also crashes
